ALTER TABLE `core_member` ADD `ssn_no` VARCHAR(36) NOT NULL AFTER `member_id`;

ALTER TABLE `company_info` ADD `id` INT NOT NULL DEFAULT '1' FIRST, ADD PRIMARY KEY (`id`) ;
ALTER TABLE `core_notification` ADD `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE `enable_module` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`) ;