<?php  foreach ($result as $data) {
  if ($module_name=='leaves'){
      $leave_stt=$data['leave_status'];
   
 ?>
<!--<div class="showcenter">
<form>
    <fieldset>
        <legend><?php echo $data['member_login_name'];?></legend>
        <p>
            <?php
                                if($data['member_profile']==null){
                                     $img = "profile_black.png";}
                                  else{
                                       $img=$data['member_profile'];
                                   }
                        ?>                                                 
                        <img src="../../uploads/<?php echo  $img;?>"  class="img-circle" style="margin-left: 150px;" width="100px" alt="Image"/>
        </p>
		<table id="tableshow">					
                    <tr>
                        <td>User Name   </td> <td><br><input type="text" value="<?php echo $data['member_login_name'];?>"></td>
                    </tr>												
                    <tr>
			<td>Start Date  </td><td><br> <input type="text" value="<?php echo $data['start_date'];?>" ></td>
                    </tr>
                    <tr>
			<td>End Date  </td><td><br> <input type="email" value="<?php echo $data['end_date'];?>"></td>
                    </tr>
                    <tr>
                        <td>Leave Status  </td><td><br> <input type="text" value="<?php if($leave_stt==0){echo 'pending';}else if($leave_stt==1){echo 'Confirmed';}else{echo 'Rejected';}?>"></td>
                    </tr>
                    <tr>
                        <td>Leave Days </td><td><br>  <input type="text" value="<?php echo $data['leave_days'];?>"></td>
                    </tr> 
                    <tr>
                        <td>Leave Category  </td><td><br>  <input type="text" value="<?php echo $data['leave_category'];?>"></td>
                    </tr> 
                    <tr>
                        <td>Leave Description  </td><td><br>  <input type="text" value="<?php echo $data['leave_description'];?>"></td>
                    </tr> 
                    <tr>
                        <td></td>
			<td><a href="#" class="button" id="noti_accept">Accept</a><a href="#" class="button" id="noti_reject">Reject</a></td>
                    </tr>
		</table>	
    </fieldset>
</form>
</div>-->



<form id="noti_detail" width="10px" height="300px" >
<!--    <table border>
        <tr>
            <th>aa</th>
            <th>bb</th>
            <th>cc</th>
            <th>dd</th>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa</td>
            <td>aa</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa</td>
            <td>aa</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa</td>
            <td>aa</td>
            <td>aa</td>
        </tr>
    </table>-->
    
   <fieldset>
       <legend>
           <?php
                                if($data['member_profile']==null){
                                     $img = "profile1.jpg";}
                                  else{
                                       $img=$data['member_profile'];
                                   }
                        ?>                                                 
                        <img src="../../uploads/<?php echo  $img;?>"  class="img-circle" style="margin-left: 350px;box-shadow: 0px 0px 5px #3c8dbc;" width="100px" alt="Image"/>
       </legend>
<!--       <img src="../../uploads/aa.png" style="margin-left: 200px;margin-top: -20px;">-->
      
       <table width="500px" height="290px" style="margin-left: 400px;background-color: whitesmoke;border-radius: 20px;box-shadow: 0px 0px 5px #3c8dbc;" > 
           <tr><td></td><td><b>User Name </b></td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['member_login_name'];?>" disabled> </span><b style="font-size:13px;"></b></td><td ></td></tr>
<tr><td></td><td><b>Start Date </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['start_date'];?>" > </span><b style="font-size:13px;"></b></td></tr>
<tr><td></td><td><b>End Date </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['end_date'];?>"> </span><b style="font-size:13px;"></b></td></tr>
  <tr><td></td><td><b>Leave Status </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php if($leave_stt==0){echo 'pending';}else if($leave_stt==1){echo 'Confirmed';}else{echo 'Rejected';}?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
<tr><td></td><td><b>Leave Days </b> </td><td><span style="color:black"><input style="margin-top: 10px;" type="text" value="<?php echo $data['leave_days'];?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
<tr><td></td><td><b>Leave Category </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['leave_category'];?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
<tr><td></td><td><b>Leave Description </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['leave_description'];?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
<tr><td></td><td><input type="hidden" value="<?php echo $data['member_id'];?>"  name="id"></td><td></td></td></tr>
<tr><td></td><td><input type="hidden" value="<?php echo $data['end_date'];?>"  name="end_date"></td><td></td></td></tr>
<tr><td></td><td><input type="hidden" value="<?php echo $data['leave_days'];?>"  name="leave_days"></td><td></td></td></tr>
<tr><td></td><td><input type="hidden" value="<?php echo $data['start_date'];?>"  name="start_date"></td><td></td></td></tr>
<tr><td></td><td><input type="hidden" value="<?php echo $data['noti_id'];?>"  name="noti_id"></td><td></td></td></tr>
<tr><td></td><td></td><?php if ($this->session->permission_code=='ADMIN'){ ?><td colspan="2"><br><a href="#" class="button" id="noti_accept" style="background: #3c8dbc;color:white;">Accept</a><a href="#" class="button" id="noti_reject" style="color:#3c8dbc;">Reject</a>
    <?php }else { ?><td colspan="2"><br><a href="#" class="button" id="noti_ok">Back</a>
    </td></tr><?php }?>
    </table>
        
   </div>
    </div>   
   </fieldset></form>
    
<!--            <div id="leftside">
                <span>For Apply Leave</span>
                
                 <?php  foreach ($result as $data) { ?>
                       <input style="margin-top: 10px;" type="text" value="<?php echo $data['member_login_name'];?>">
                 <?php      
                 }
                 ?> 
                       <ul class="nav nav-pills nav-stacked col-sm-12" id="left-scroll">
         <?php
            foreach ($result as $result) {
                ?>
            <li class="addbtnn"> <input style="margin-top: -2px;margin-left: 10px;" type="checkbox" class='case' name='checkbox[]' value="<?= $result[member_login_name]; ?>" ><?php echo " ".$result['member_login_name']; ?></li>
                <?php
            }
            ?>
        </ul>
                       
            </div>
        
            <div id="rightside">
                    <form id="noti_detail" width="10px" height="300px" >
                            <fieldset>
                                <legend>
                                    <?php
                                                         if($data['member_profile']==null){
                                                              $img = "profile1.jpg";}
                                                           else{
                                                                $img=$data['member_profile'];
                                                            }
                                                 ?>                                                 
                                                 <img src="../../uploads/<?php echo  $img;?>"  class="img-circle" style="margin-left: -500px;box-shadow: 0px 0px 5px #3c8dbc;" width="100px" alt="Image"/>
                                </legend>
                                <img src="../../uploads/aa.png" style="margin-left: 200px;margin-top: -20px;">

                                <table width="500px" height="290px" style="margin-left: 300px;background-color: whitesmoke;border-radius: 20px;box-shadow: 0px 0px 5px #3c8dbc;" > 
                                    <tr><td></td><td><b>User Name </b></td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['member_login_name'];?>" disabled> </span><b style="font-size:13px;"></b></td><td ></td></tr>
                         <tr><td></td><td><b>Start Date </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['start_date'];?>" > </span><b style="font-size:13px;"></b></td></tr>
                         <tr><td></td><td><b>End Date </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['end_date'];?>"> </span><b style="font-size:13px;"></b></td></tr>
                           <tr><td></td><td><b>Leave Status </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php if($leave_stt==0){echo 'pending';}else if($leave_stt==1){echo 'Confirmed';}else{echo 'Rejected';}?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
                         <tr><td></td><td><b>Leave Days </b> </td><td><span style="color:black"><input style="margin-top: 10px;" type="text" value="<?php echo $data['leave_days'];?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
                         <tr><td></td><td><b>Leave Category </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['leave_category'];?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
                         <tr><td></td><td><b>Leave Description </b> </td><td><span style="color:black"> <input style="margin-top: 10px;" type="text" value="<?php echo $data['leave_description'];?>" disabled> </span><b style="font-size:13px;"></b></td></tr>
                         <tr><td></td><td><input type="hidden" value="<?php echo $data['member_id'];?>"  name="id"></td><td></td></td></tr>
                         <tr><td></td><td><input type="hidden" value="<?php echo $data['end_date'];?>"  name="end_date"></td><td></td></td></tr>
                         <tr><td></td><td><input type="hidden" value="<?php echo $data['leave_days'];?>"  name="leave_days"></td><td></td></td></tr>
                         <tr><td></td><td><input type="hidden" value="<?php echo $data['start_date'];?>"  name="start_date"></td><td></td></td></tr>
                         <tr><td></td><td><input type="hidden" value="<?php echo $data['noti_id'];?>"  name="noti_id"></td><td></td></td></tr>
                         <tr><td></td><td></td><?php if ($this->session->permission_code=='ADMIN'){ ?><td colspan="2"><br><a href="#" class="button" id="noti_accept" style="background: #3c8dbc;color:white;">Accept</a><a href="#" class="button" id="noti_reject" style="color:#3c8dbc;">Reject</a>
                             <?php }else { ?><td colspan="2"><br><a href="#" class="button" id="noti_ok">Back</a>
                             </td></tr><?php }?>
                             </table>
            </div>
    <div  id="clear"></div>-->
        <?php }}?>  

