
<form width="650px" height="300px" action="../../leavedays/index/decide" method="post">
	<table width="650px" height="300px">
            <?php foreach($detail as $Result){?><input type="hidden" name="member_id" value="<?php echo $Result['member_id'];?>">
                <input type="hidden" name="start_date" value="<?php echo $Result['start_date'];?>">
                <input type="hidden" name="days" value="<?php echo $Result['leave_days'];?>">
	<tr>
                
		<td>User Name :</td>
		<td><?php echo $Result['member_login_name'];?></td>
		<td></td>
		<td>ID:</td>
		<td name="id" ><?php echo $Result['member_id'];?></td>
	</tr>
	<tr>
		<td>Start Date :</td>
		<td id="sdate"><?php echo date("d-m-Y", strtotime( $Result['start_date']));?></td>
		<td></td>
		<td>End Date	:</td>
		<td><?php echo date("d-m-Y", strtotime( $Result['end_date']));?></td>
	</tr>
	<tr>
		<td>Leave Status :</td>
		<td><?php 
                 switch($Result['leave_status']){
                            case "0" : echo "Pending" ; break;
                            case "1" : echo "Confirmed";break;
                            case "2" : echo "Rejected";break;
                               
                        }?></td>
		<td></td>
		<td>Days :</td>
		<td><?php echo $Result['leave_days']?></td>
	</tr>
	<tr>
		<td>Leave Description:</td>
		<td colspan="4"><?php echo $Result['leave_description']?></td>
	</tr>
	
	<tr> 
		
            <td colspan="5"> <?php if($this->session->user['member_login_name']=="admin"){?><input type="submit" value="Yes" name="submit" class="buttonn">
		 <input type="submit" name="submit" value="No"  class="buttonn">
            <a href="#" class="button" id="notidetail_cancel">Cancel</a></td><?php } else{?>
            <a href="#" class="button" id="notidetail_cancel">OK</a><?php }?>
            
		
	</table>
            <?php }?>
</form>