<div class="forscroll">
<?php foreach( $noti as $noti){
    foreach ($noti as $noti){
        ?>
        <?php switch($noti['module_name']){ case "leaves": {?>
        <li>
       <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li>
                <?php if($this->session->permission_code=="ADMIN"){?>
                    
                <a href="../../notification/index/detail?id=<?php echo $noti['noti_id'];?>&mname=<?php echo $noti['module_name'];?>" class="" id="<?php echo  $noti['member_id']; echo","; echo $noti['start_date'];?>">
                <img src="../../common/img/notid.png"> 
                <b><i style="color:red"><?php echo $noti['member_login_name'];?></i></b> apply  leave for <?php echo "<b>".date("d-m-Y", strtotime( $noti['start_date']))."</b>";
                }else {?>
                <span class="foruser">
                    <a href="../../notification/index/detail?id=<?php echo $noti['noti_id'];?>&mname=<?php echo $noti['module_name'];?>" class="" id="<?php echo  $noti['member_id']; echo","; echo $noti['start_date'];?>">
                    <img src="../../common/img/notid.png"> <b>admin</b><?php echo $noti['leave_status'];
                    switch($noti['leave_status']){
                        case "1" : echo " Confirmed";break;
                        case "2" : echo " Rejected";break;
                }?> <?php echo "leave days for <b>".date("d-m-Y", strtotime( $noti['start_date']))."</b>";}?></a></span>
                </li>
            </ul>
        </li>
            
        <?php break; }// end of file for case "leaves"
        case "calendar" :{?> 
        <li>
       <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li>
               
                    
                <a href="" class="calendar" id="<?php echo  $noti['noti_id'];?>">
                <img src="../../common/img/notid.png"> 
                <b><i style="color:red"><?php echo $noti['member_login_name'];?></i></b> marked calendar for  <?php echo $noti['title']; echo " at <b>".date("d-m-Y", strtotime( $noti['startdate']))."</b> ";
               ?></a></span>
                </li>
            </ul>
        </li>
        
        
<?php } }// end of file for switch
}// end of file for second for each 
 } // end of file for first for each?>
</div>
