   <style>.ui-dialog-titlebar-close {
  visibility: hidden;
}</style>
   <h3><b>Apply Leave Lists</b></h3>
<section class="content">
          <!-- Info boxes -->
          <div class="row">              
             <ul class="noti">
                 <?php foreach($all as $result){?>                    
                      <li type="1">
                        <a  class="adminnotidetail" id="<?php echo $result['member_id'] ?>">
                          <i class="fa fa-users text-aqua"></i> <?php echo "<b>".$result['member_login_name']."</b>"?> applied <?php echo "<b style='color:red;'>".$result['leave_days']."</b>"?>
                          leave days from <?php echo "<b>".date("d-m-Y", strtotime( $result['start_date']))."</b>";?> to <?php echo "<b>".date("d-m-Y", strtotime( $result['end_date']))."</b>"; ?> under the category   <?php echo " <i style='color:red'> \"  ".$result['leave_category']." \"</i> . "?>
                        </a>
                         
                      </li>
                 <?php }?>

                    
                    </ul>
          </div><!-- /.row -->
<div id="notidetail" style="display:none;" class="navbar">

		  
        </section>