<!--
 @author Su Zin Kyaw
 @since  2015/11 /06-->
<?php
date_default_timezone_set('UTC');
?>



<!-- Main content -->
<section class="content" style="height:580px">
    <div id="veiwallnotification">
    <label id="noti_title">Notifications</label>
    <hr id="hrstyle">
    <div class="forscroll">
        <?php foreach ($Noti as $Noti) {
            ?>
            <?php
            switch ($Noti['module_name']) {
                case "leaves": {
                        ?>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="">
                                <li style="list-style-type: circle">
                                    <?php if ($permission == "admin") { ?>

                                        <a href="<?php echo $baseUri; ?>notification/index/detail?id=<?php echo $Noti['noti_id']; ?>&mname=leaves" class="" id="<?php
                                        echo $Noti['member_id'];
                                        echo",";
                                        echo $Noti['start_date'];
                                        ?>">

                                                                                           
                                            <b><i style="color:red"><?php echo $Noti['member_login_name']; ?></i></b> apply  leave for <?php
                                            echo "<b>" . date("d-m-Y", strtotime($Noti['start_date'])) . "</b> created by " . $Noti['creator_name'];
                                        } else {
                                            ?>
                                            <span class="foruser">
                                                <a href="<?php echo $baseUri; ?>notification/index/detail?id=<?php echo $Noti['noti_id']; ?>&mname=<?php echo $Noti['module_name']; ?>" class="" id="<?php
                                                echo $Noti['member_id'];
                                                echo",";
                                                echo $Noti['start_date'];
                                                ?>">
                                                    <img src="<?php echo $baseUri; ?>common/img/notid.png"> <b>admin</b><?php
                                                    switch ($Noti['leave_status']) {
                                                        case "1" : echo " Confirmed";
                                                            break;
                                                        case "2" : echo " Rejected";
                                                            break;
                                                    }
                                                    ?> <?php
                                                    echo "leave days for <b>" . date("d-m-Y", strtotime($Noti['start_date'])) . "</b>";
                                                }
                                                ?></a></span>
                                </li>
                            </ul>
                        </li>

                        <?php
                        break;
                    }// end of file for case "leaves"
                case "calendar" : {
                        ?> 
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul>
                                <li style="list-style-type: circle">


                                    <a href="<?php echo $baseUri; ?>notification/index/noticalendar?id=<?php echo $Noti['noti_id']; ?>" class="calendar" id="<?php echo $Noti['noti_id']; ?>">
                                        <img src="<?php echo $baseUri; ?>common/img/notid.png"> 
                                        <b><i style="color:red"><?php echo $Noti['creator_name']; ?></i></b> marked calendar for <i style="color:red"> <?php echo $Noti['member_login_name']; ?></i><?php echo " at <b>" . date("d-m-Y", strtotime($Noti['startdate'])) . "</b> ";
                        ?></a></span>
                                </li>
                            </ul>
                        </li>


                        <?php
                        break;
                    }
                case "attendances" : {
                        ?> 
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul >
                                <li style="list-style-type: circle">               

                                    <a href="<?php echo $baseUri; ?>notification/index/notiattendances?id=<?php echo $Noti['noti_id']; ?>" class="attendances" id="<?php echo $Noti['noti_id']; ?>">
                                        <img src="<?php echo $baseUri; ?>common/img/notid.png"> 
                                        <b><i style="color:red"><?php echo $Noti['member_login_name']; ?></i></b> is Late for   <?php
                                        echo $Noti['notes'];
                                        echo " at <b>" . date("d-m-Y", strtotime($Noti['checkin_time'])) . "</b> ";
                                        ?></a></span>
                                </li>
                            </ul>
                        </li>


                        <?php
                    }
            }// end of file for switch
        }
        foreach ($old_noti as $Noti) {
            ?>
            <?php
            switch ($Noti['module_name']) {
                case "leaves": {
                        ?>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul >
                                <li style="list-style-type: circle">
                                    <?php if ($permission == "admin") { ?>


                                                                                      
                                        <b><i ><?php echo $Noti['member_login_name']; ?></i></b> apply  leave for <?php
                                        echo "<b>" . date("d-m-Y", strtotime($Noti['start_date'])) . "</b> created by " . $Noti['creator_name'];
                                    } else {
                                        ?>
                                        <span class="foruser">
                                            <img src="<?php echo $baseUri; ?>common/img/notid.png"> <b>admin</b><?php
                                            switch ($Noti['leave_status']) {
                                                case "1" : echo " Confirmed";
                                                    break;
                                                case "2" : echo " Rejected";
                                                    break;
                                            }
                                            ?> <?php
                                            echo "leave days for <b>" . date("d-m-Y", strtotime($Noti['start_date'])) . "</b>";
                                        }
                                        ?></a></span>
                                </li>
                            </ul>
                        </li>

                        <?php
                        break;
                    }// end of file for case "leaves"
                case "calendar" : {
                        ?> 
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul >
                                <li style="list-style-type: circle">
                                                                                   


                                    <b><i ><?php echo $Noti['creator_name']; ?></i></b> marked calendar for <i style="color:red"> <?php echo $Noti['member_login_name']; ?></i><?php echo " at <b>" . date("d-m-Y", strtotime($Noti['startdate'])) . "</b> ";
                                    ?></span>
                                </li>
                            </ul>
                        </li>


                        <?php
                        break;
                    }
                case "attendances" : {
                        ?> 
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul>
                                <li style="list-style-type: circle">               
                                                                                  

                                    <b><i><?php echo $Noti['member_login_name']; ?></i></b> is Late for   <?php
                                    echo $Noti['notes'];
                                    echo " at <b>" . date("d-m-Y", strtotime($Noti['checkin_time'])) . "</b> ";
                                    ?></span>
                                </li>
                            </ul>
                        </li>


                        <?php
                    }
            }// end of file for switch
        }
//
//// end of file for second for each 
// end of file for first for each
        ?>
    </div>
</div>

</section><!-- /.content -->
