   <style>.ui-dialog-titlebar-close {
  visibility: hidden;
}</style>
<section class="content">
          <!-- Info boxes -->
          <div class="row">
             <ul class="noti">
                 <?php foreach($all as $result){?>
                      <li >
                        <a  class="notidetail" id="<?php echo $result['member_id'] ?>">
                          <i class="fa fa-users text-aqua"></i> <?php echo $result['member_login_name']?> applied <?php echo $result['leave_days']?>
                          leave days from <?php echo date("d-m-Y", strtotime( $result['start_date']));?> to <?php echo date("d-m-Y", strtotime( $result['end_date'])); ?> under the category   "<?php echo $result['leave_category']?>"
                          
                        </a>
                      </li>
                 <?php }?>

                    
                    </ul>
          </div><!-- /.row -->
<div id="notidetail" style="display:none;border: 1px solid;background-color: white;" class="navbar">

		  
        </section>