<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}  
use Phalcon\Filter;
?>

<a name="Group"> </a>
<div class="row">
    <div class="col-sm-2 link change-bg"> 
        <aside class="sidebar-menu visited_color"> 
            <li class=""><a href="#Group"><?= $t->_("grouprulesetting"); ?> </a></li>    
            <li class=""><a href="#Page"><?= $t->_("pagerulesetting"); ?></a></li>
            <li class=""><a href="#User"><?= $t->_("userrulesetting"); ?></a></li>
        </aside> 
    </div>

    <!-- content-wrapper-content -->

    <div class="col-sm-10">
        <div class=col-md-12">
            <h3 link="#Group" ><?= $t->_("grouprulesetting"); ?></h3>

            <a href="#" style="float:right;" onclick="addGroup.apply(this);
                    return false;" class="btn addgn" type="black" id=""> <?= $t->_("addgroupname"); ?></a>  

            <div id="addGroup" title="<?= $t->_("addgroupname"); ?>" style="display: none;">
                <form method="POST" action="index/AddGroupRule">
                    <table>
                        <tr>
                            <td><?= $t->_("groupname"); ?></td>
                            <td><input type="text" style="margin-top:10px;" name="name_of_group" value=""  placeholder="<?= $t->_("writegroupname"); ?>"></td>
                        </tr>
                    </table>
                </form>
            </div>  
            <br>
            <table class="listtbladmin listtbl" >

                <thead style="text-align:center;">
                <br>

                <th width="5px" style="text-align:center;">Group ID</th>
                <th width="300px" style="text-align:left;"><?= $t->_("groupname"); ?></th>
                <th width="5px" style="text-align:center;"><?= $t->_("action"); ?></th>

                </thead>

                <tbody style="text-align:center;">

                    <?php
                    $filter = new Filter();
                    $i = 1;
                    foreach ($coreid as $data) {
                        ?>
                        <tr>
                            <td><?= $data->group_id ?></td>
                            <td style="text-align:left;"><?= $data->name_of_group ?></td>
                            <td>                                                    
                                <a href="#" onclick="showDialog.apply(this);
                                        return false;" class="insettingedit" type="black" id="<?= $data->group_id ?>">  </a>                                                                                                           
                            </td> 
                        </tr>                                                                                                   
                    <div id="open<?= $data->group_id ?>" title="<?= $t->_("changegrouprule"); ?>" style="display: none;">
                        <form method="POST" action="index/GroupRuleSetting">

                            <input type="hidden" name="group_id" value="<?= $data->group_id ?>" >

                            Group ID   <input type="text" style="margin-left: 100px;" value="<?= $data->group_id ?>" disabled><br>
                            <?= $t->_("groupname"); ?>    <input type="text" style="margin-left: 78px;" name="name_of_group" value="<?= $data->name_of_group ?>">
                        </form>
                    </div>                                                                                                

                    <?php
                    $i++;
                }
                ?>
                </tbody>     
            </table>    

            <?php
            require_once 'page.phtml';
            require_once 'user.phtml';
            ?>

        </div>
        <!-- /.content-wrapper-content -->
        <!-- Top Menu -->
        <!-- /Top Menu -->

    </div>




