<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
   

use Phalcon\Filter;
?>

<a name="Group"> </a>
<div class="row">


    <div class="col-sm-2 link"> 
        <aside class="sidebar-menu"> 
            <li style="border-bottom:1px solid #aaa;"><a href="#Group">Group Rule Setting </a></li>    
            <li style="border-bottom:1px solid #aaa;"><a href="#Page">Page Rule Setting</a></li>
            <li style="border-bottom:1px solid #aaa;"><a href="#User">User Rule Setting</a></li>
        </aside> 
    </div>

    <!-- content-wrapper-content -->

    <div class="col-sm-10">
        <div class=col-md-12">
            <a href="<?php echo $baseUri; ?>setting/user"  style="float:right;" id="viewprofile">View Profile</a>

            <h3 link="#Group" >Group Rule Setting </h3>

            <a href="#" style="float:right;" onclick="addGroup.apply(this);
                    return false;" class="btn addgn" type="black" id=""> Add Group Name  </a>  

            <div id="addGroup" title="Add Group Rule" style="display: none;">
                <form method="POST" action="index/AddGroupRule">
                    <table>
                        <tr>
                            <td>Group Name</td>
                            <td><input type="text" style="margin-top:10px;" name="name_of_group" value="" ></td>
                        </tr>
                    </table>
                </form>
            </div>  
            <br>
            <table class="listtbladmin listtbl" >

                <thead style="text-align:center;">
                <br>

                <th width="5px" style="text-align:center;">Group ID</th>
                <th width="300px" style="text-align:left;">Group Name</th>
                <th width="5px" style="text-align:center;">Action</th>

                </thead>

                <tbody style="text-align:center;">

                    <?php
                    $filter = new Filter();
                    $i = 1;
                    foreach ($coreid as $data) {
                        ?>
                        <tr>
                            <td><?= $data->group_id ?></td>
                            <td style="text-align:left;"><?= $data->name_of_group ?></td>
                            <td>                                                    
                                <a href="#" onclick="showDialog.apply(this);
                                        return false;" class="insettingedit" type="black" id="<?= $data->group_id ?>">  </a>                                                                                                           
                            </td> 
                        </tr>                                                                                                   
                    <div id="open<?= $data->group_id ?>" title="Change Group Rule" style="display: none;">
                        <form method="POST" action="index/GroupRuleSetting">

                            <input type="hidden" name="group_id" value="<?= $data->group_id ?>" >

                            Group ID   <input type="text" style="margin-left: 100px;" value="<?= $data->group_id ?>" disabled><br>
                            Group Name      <input type="text" style="margin-left: 72px;" name="name_of_group" value="<?= $data->name_of_group ?>">
                        </form>
                    </div>                                                                                                

                    <?php
                    $i++;
                }
                ?>
                </tbody>     
            </table>    

            <?php
            require_once 'page.phtml';
            require_once 'user.phtml';
            ?>

        </div>
        <!-- /.content-wrapper-content -->
        <!-- Top Menu -->
        <!-- /Top Menu -->

    </div>




