<?php
/**
 * @author Yan Lin Pai  <> <wizardrider@gmail.com>
 * @page.html
 */
?>

<a name="Page"></a>
<br>
<h3>Change Page Rule </h3>

<a href="#" style="float:right;" onclick="addPage.apply(this);
        return false;" class="btn addpp" type="black" id=""> Add Page Permission  </a>                                                                                                                                           
<br>
<div id="addPage" title="Add Page Rule" style="display: none;">
    <form method="POST" action="AddPageRule">
        <table>
            <tr>
                <td> Page Name</td>
                <td>
                    <input list="browsers" name="permission_code" value="" id="page_rule">
                    <datalist id="browsers">
                        <?php foreach ($coreuser2 as $datauser2) {
                            ?>

                            <option value="<?= $datauser2->permission_code ?>">
                                <?php
                            }
                            ?>
                    </datalist>
                </td>
            </tr>
            <tr>
                <td></td>
                <td><br></td>
            </tr>
            <tr>
                <td>
                    Group Name  
                </td>
                <td>
                    <select type="text" name='page_rule_group' id="page_rule">
                        <?php
                        foreach ($coreid as $data) {
                            ?>
                            <option value="<?= $data->group_id . "_" . $data->name_of_group ?>" >
                                <?= $data->name_of_group ?>                                       
                            </option>                                                       
                            <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
        </table>




    </form>
</div>   

<table class="listtbladmin listtbl" id="page_role">

    <thead>
    <br>
    <tr>
        <th width="5px" style="text-align:center;">User ID</th> 
        <th width="200px">Page Name</th>
        <th width="250px">G Name</th>
        <th width="5px" style="text-align:center;">Action</th>

    </tr>
</thead>
<tbody style="text-align:center;">
    <?php foreach ($coreuser2->items as $datauser2) { ?>
        <tr>   
            <td style="text-align:center;"><?= $datauser2->idpage ?></td>
            <td style="text-align:left;"><?= $datauser2->permission_code ?></td>                                       
            <?php
            foreach ($coreid as $data) {

                if ($datauser2->page_rule_group == $data->group_id) {
                    ?>
                    <td style="text-align:left;"> 
                        <?= $data->name_of_group ?>  
                        (<?= $datauser2->page_rule_group ?>)
                    </td>
                    <?php
                }
            }
            ?>
            <td>

                <a href="#" onclick="PageRuleSetting.apply(this);
                        return false;" class="insettingedit" type="black" id="<?= $datauser2->idpage ?>">  </a>  
            </td> 

        </tr>
    <?php
}
?>        
</tbody>
<tfoot>
    <tr>
        <td colspan="4">
    <ul class="pagination" style="margin-left:15px;">
        <?php
        if ($coreuser2->last === 1) {
            
        } else {
            ?>
            <li><a href="admin">First</a></li>
            <li><a href="admin?page=<?= $coreuser2->before; ?>">Previous</a></li>
            <li><a href="admin?page=<?= $coreuser2->next; ?>">Next</a></li>
            <li><a href="admin?page=<?= $coreuser2->last; ?>">Last</a></li>
            <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $coreuser2->current, " of ", $coreuser2->total_pages; ?></span></li>
            <?php
        }
        ?>
    </ul>
        </td>
    </tr>
</tfoot>
    
</table>  
