<div class="row">
    <div class="col-sm-3">        
        <ul class="nav nav-pills nav-stacked">
        <?php 
        $count = 0;        
        echo "<li class='active'><a href='' onclick='return false;'>Select Permission under</a></li>";
        foreach ($member as $name){            
            if($count==4 || $count==7)
            echo "<li><a href=''>".$name['member_login_name']."</a></li>";
            $count++;
        }
        
        ?>                  
        </ul>
    </div>
    <div class="col-sm-8">
        Manage user module permission by setting this in advance and secure.<br>
        Good manage control by DV.
    </div>
</div>