<?php
    use Phalcon\Filter;
?>

<a name="User"></a>
                                     <br>
                                <h3><kbd>Change User Rule  </kbd></h3>
                                
                                <br>
                             
                                
                                <table class="listtbladmin listtbl" id="user_role">
                        
                        <thead>
                        <br>
                                <tr>                                  
                                <th width="100">Group ID</th>                                
                                <th width="175">User Name</th>
                                <th width="">Group Name</th>
                                <th width="">Action</th>
                                 
                                </tr>
                        </thead>
                        <tbody style="display:none;">
                   <?php 
                   foreach($coreuser as $datauser){ 
                       if($datauser['deleted_flag'] == 0){
                       ?>
                                <tr>                                        
                                        <td><?= $datauser['group_id'] ?></td>
                                        <td><?= $datauser['member_login_name'] ?></td>
                                        
                                        
                                       <?php
                                        foreach($coreid as $data){ 
                                            
                                            if( $datauser['group_id']  == $data->group_id){
                                                
                                          
                                        ?>
                                        <td> 
                                       
                                            
                                        <?=  $data->name_of_group ?>  
                                        (<?=  $datauser['group_id']  ?>)
                                        </td>
                                        <?php
                                         }
                                        }
                                         
                                         
                                         ?>
                                        
                                        
                                        <td>        
            <a href="#" onclick="showDialoguser.apply(this);return false;" class="btn" type="black" id="<?= $datauser['member_id'] ?>"> Edit </a>  
                                        </td> 
                                         
                                </tr>
                                
                                <div id="openu<?= $datauser['member_id'] ?>" title="Change User Rule" style="display: none;">
                                       <form method="POST" action="index/UserRuleSetting">    
                                           <br> 
                                        
                                        User Name  : 
                                        <input type="text" name="member_login_name" value="<?= $datauser['member_login_name'] ?>" disabled>
                                        <br><br>
                                           Group Rule
                                           
<!--                                        <input type="hidden" name="member_login_name" value="<?= $datauser['member_login_name'] ?>" >-->
                                           <select type="text" name='user_rule' value='' id="changeuser<?= $datauser['member_id'] ?>">
                                        <?php
                                        foreach($coreid as $data){
                                          ?>
                                        <option value="<?= $data->group_id ?>" <?php if( $datauser['group_id']  == $data->group_id){ ?>selected <?php } ?>>
                                            
                                                  <?= $data->name_of_group ?>
                                            
                                        </option>
                                        <?php
                                         }
                                         ?>
                                        </select>
                                        </form>
                                            
                              </div>
                                
                                
                                
                                
                                
                   <?php
                   }
                   else{
                       
                   }
                   
                                        }
                   ?></tbody>
                       <tfoot></tfoot>
            </table>  
                                