<?php

use Phalcon\Filter;
?>

<a name="User"></a>
<br>
<h3>Change User Rule </h3>

<br>


<table class="listtbladmin listtbl" id="user_role">

    <thead>
    <br>
    <tr>                                  
        <th width="10px" style="text-align:center;">Group ID</th>                                
        <th width="200px">User Name</th>
        <th width="200px">Group Name</th>
        <th width="10px">Action</th>                               
    </tr>
</thead>
<tbody style="text-align:center;" >
    <?php
    foreach ($coreuser->items as $datauser) {        
            ?>
            <tr>                                        
                <td><?= $datauser->group_id ?></td>
                <td style="text-align:left;"><?= $datauser->core->member_login_name ?></td>


                <?php
                foreach ($coreid as $data) {

                    if ($datauser->group_id == $data->group_id) {
                        ?>
                        <td style="text-align:left;"> 


                            <?= $data->name_of_group ?>  
                            (<?= $datauser->group_id ?>)
                        </td>
                        <?php
                    }
                }
                ?>


                <td>        
                    <a href="#" onclick="showDialoguser.apply(this);
                                    return false;" class="insettingedit" type="black" id="<?= $datauser->core->member_id ?>"> </a>  
                </td> 

            </tr>

        <div id="openu<?= $datauser->core->member_id ?>" title="Change User Rule" style="display: none;">
            <form method="POST" action="UserRuleSetting">   
                User Name   
                <input type="text" style="margin-left:50px;" name="member_login_name" value="<?= $datauser->core->member_login_name ?>" disabled>
                <br><br>
                Group Rule

                <select type="text" style="margin-left:50px;" name='user_rule' value='' id="changeuser<?= $datauser->core->member_id ?>">
                    <?php
                    foreach ($coreid as $data) {
                        ?>
                        <option value="<?= $data->group_id ?>" <?php if ($datauser->group_id == $data->group_id) { ?>selected <?php } ?>>

                            <?= $data->name_of_group ?>

                        </option>
                        <?php
                    }
                    ?>
                </select>
            </form>

        </div>


        <?php    
}
?></tbody>
<tfoot>
    <tr>
        <td colspan="4">
            <ul class="pagination" style="margin-left:15px;">
                <?php
                if ($coreuser->last === 1) {
                    
                } else {
                    ?>
                    <li><a href="admin">First</a></li>
                    <li><a href="admin?page1=<?= $coreuser->before; ?>">Previous</a></li>
                    <li><a href="admin?page1=<?= $coreuser->next; ?>">Next</a></li>
                    <li><a href="admin?page1=<?= $coreuser->last; ?>">Last</a></li>
                    <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $coreuser->current, " of ", $coreuser->total_pages; ?></span></li>
                        <?php
                    }
                    ?>
            </ul>
        </td>
    </tr>
</tfoot>
</table>  

