<!--
  @author Su Zin Kyaw
  @since  2015/11 /06-->
<!--Show Drop Down list for month-->

<?php
    //calculate the user time offset
   
    if ($offset<0){
    $sign='-';
    $value=$offset*(-1);
    
  
  }
    else{
    $value=$offset*(-1);
    $sign='+';
} 


?> 
<section class="content-header">
          <h1>
           Attendance list
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"> attendance list</li>
          </ol>
</section>
<section class="content">
        <!-- Main content -->
        <div class="buttons">
            <form id="frm_search" onsubmit="return false;">
             <select class="select" data-toggle="select" name="month" id="month">
            <option value="">Month</option>
            <option value="01">January</option>
            <option value="02">February</option>
            <option value="03">March</option>
            <option value="04">April</option>
            <option value="05">May</option>
            <option value="06">June</option>
            <option value="07">July</option>
            <option value="08">Augusts</option>
            <option value="09">September</option>
            <option value="10">Octobers</option>
            <option value="11">November</option>
            <option value="12">December</option>
        </select>
            <input type="submit" class="buttonn" value="Search" id="search">
            <!--       <a href="#" class="button" id="search">Search</a>-->
            <a href="" class="button export" onclick="Export.Export.apply(this, [$('table.listtbl'),'attendance_list.csv']);">Export</a>
        </form>
        </div><!--Button-->
<div class="demo-content" style="padding-top:2%;">
<table class="listtbl">
<thead>
    <tr>
        <th>Date</th>
	<th>User Name</th>
	<th>Check In</th>
	<th>Check Out</th>
        <th>Late</th>
	<th>Working Time</th>
	<th>OverTime</th>
        <th>Check In Place</th>
    </tr>
  </thead>
  <tbody>
  <?php
	foreach ($attlist->items   as $result) {
  ?>
    <tr>
	<td><?php echo $result['att_date']; ?></td>
	<td><?php echo $result['member_login_name']; ?></td>
<!--        check in time-->
	<td><?php $checkintime=$result['checkin_time'];
        if ($sign=='-'){
            $cintime = new DateTime($checkintime);
        $cintime->add(new DateInterval('PT' . $value . 'M'));
        echo $cintime->format('Y-m-d H:i:s A');
        }
        else{
         $cintime = date("Y-m-d H:i:s A",strtotime($value." minutes",strtotime($checkintime)));
            echo $cintime;
        }
     ?>
        </td>
        
<!--        check out time -->
        <td><?php $checkouttime= $result['checkout_time'];
        if($checkouttime==0){
        echo "-";}
        else{
            if($sign=='-'){
        $time = new DateTime($checkouttime);
        $time->add(new DateInterval('PT' . $value . 'M'));
        echo  $time->format('Y-m-d H:i:s A');}
        else {
            $time = date("Y-m-d H:i:s A",strtotime($value." minutes",strtotime($checkouttime)));
            echo $time;
        }
        }
?></td>
        
<!--        Late-->
        <td><?php  
      $time = date("H:i:s",strtotime($value." minutes",strtotime($checkintime)));
//           
        $office_start_time='08:00:00 ';
      
        if($time>$office_start_time){
            $start=strtotime($office_start_time);
            $end=strtotime($time);
            $late=$end-$start;
        
            echo "<font color='red'>". gmdate("H:i:s",$late)." Hours</font>";
            
        }
        ?></td>
        
<!--        Working Hour-->
	<td>
	<?php
	$start_time=strtotime($result['checkin_time']);
	$end_time=strtotime($result['checkout_time']);
        if ($end_time==0){
            echo "-";
        }
        else{
          $workingHour=$end_time-$start_time;
             $hours = floor($workingHour / 3600);
            $minutes = floor(($workingHour / 60) % 60);
             $seconds = $workingHour % 60;
            echo "$hours:$minutes:$seconds";echo " Hours";
          
	}	?>  
	</td>
        
<!--        Overtime-->
	<td><?php
      	
        if($result['overtime']!=0){
            
            echo $result['overtime'];echo " Hours";
        }
        else{
            echo "-";
        }
	 ?> </td>
        <td><?php $lat= $result['lat'];
                $lng=$result['lng'];
                $url = 'http://maps.googleapis.com/maps/api/geocode/json?latlng='.trim($lat).','.trim($lng).'&sensor=false';
                $json = @file_get_contents($url);
                $data=json_decode($json);
                $status = $data->status;
                if($status=="OK"){
                echo  $data->results[5]->formatted_address;
//                    print_r($data);
                }
                else{
                echo "-";}
        ?></td>
    </tr>
    <?php
    
        }
    ?>
</tbody>
</table>
    
</div>
</section>
<?php
if ( isset($_POST['month'])) {    
    $m = $_POST['month'];   
} 

else{
    $m=date('m');
}
if ( isset($_GET['month']) ){
    
    $m = $_GET['month'];
    
}

?>
<ul class="pagination pagination-sm">
    <li><a href="attendancelist" >First</a></li>
    <li><a href="attendancelist?page=<?= $attlist->before; ?>&month=<?php echo ((isset($m)) ? $m : ''); ?>">Previous</a></li>
    <li><a href="attendancelist?page=<?= $attlist->next; ?>&month=<?php echo ((isset($m)) ? $m : ''); ?>" >Next</a></li>
    <li><a href="attendancelist?page=<?= $attlist->last; ?>&month=<?php echo ((isset($m)) ? $m : ''); ?>" >Last</a></li>

<?php echo "You are in page ", $attlist->current, " of ", $attlist->total_pages; ?>
 

   
