<section class="content-header">
    <h1>
        <?= "Add New Company"; ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= "home" ?></a></li>
        <li class="active"><?="Add New Company"; ?></li>
    </ol>
</section>


 
<!--  <input id="tags" size="50">-->


        <!-- Main content -->
        <section class="content">
         
         <div class="row">
	 <div class="col-md-12"><!--start add user form--->
        
	<div id="form_div">
	<div style="height:30px; background-color:#3c8dbc; padding:5px 0 5px 15px;"><font color="#fffff">Add New Company Form</font></div>
        
        <form id="apply_form" action="<?php echo $baseUri ?>managecompany/index/addnew"width="650px" height="300px" style="padding:5px 0 5px 15px;" > 
            <form id="saveuser" method="post" enctype="multipart/form-data">
                   <table class="row-fluid" style="font-size:13px;"><tr><td class="">Company ID</td><td>
                   <input style="margin-top:10px ; width:50%" type="text" name="com[id]" id="uname" class="col-sm-10" placeholder="Write Company ID"></td></tr>
               <tr><td></td><td id="existId"></td></tr>
                   <tr><td style="width:20%">Company Name</td><td><input style="margin-top:10px ; width:50%" type="text" name="com[name]" class="col-sm-10" id="full_name" placeholder="Wirte Company Name"></td></tr>
                  <tr><td>Starting Date</td><td><input style="margin-top:10px; width:50%" type="text" name="com[sdate]" class="datepicker col-sm-10" id="pass" placeholder="Write Company Starting Date"></td></tr>
                  <tr><td>Email</td><td><input style="margin-top:10px ; width:50%" type="email" name="com[email]" class=" col-sm-10" id="pass" placeholder="Write Email "></td></tr>
                  <tr><td>Phone Number</td><td><input style="margin-top:10px ; width:50%" type="number " name="com[phno]" class=" col-sm-10" id="pass" placeholder="Write Phone Number "></td></tr>
                  <tr><td>Database Name</td><td><input style="margin-top:10px ; width:50%" type="text" name="com[db]" class=" col-sm-10" id="pass" placeholder="Write Database Name "></td></tr>
                  <tr><td>DB UserName</td><td><input style="margin-top:10px ; width:50%" type="text" name="com[dbun]" class=" col-sm-10" id="pass" placeholder="Write Database Username "></td></tr>
                  <tr><td>DB Password</td><td><input style="margin-top:10px ; width:50%" type="password" name="com[dbpsw]" class=" col-sm-10" id="pass" placeholder="Write Database Password"</td></tr>
                  <tr><td>Host</td><td><input style="margin-top:10px ; width:50%" type="text" name="com[host]" class=" col-sm-10" id="pass" placeholder="Write Host Name "></td></tr>
                  <tr><td>User Limit</td><td><input style="margin-top:10px ; width:50%" type="text" name="com[limit]" class=" col-sm-10" id="pass" placeholder="Write User Limit "></td></tr>
                  <tr><td>Module Flag</td><td><input type="checkbox" name="com[check]"  id="checkall1" value="Dashboard" style="margin-bottom: 5px">Dashboard <br>
                          <input type="checkbox"   name="com[check2]" id="checkall1" value="" style="margin-bottom: 5px">Attendance<br>
                          <input type="checkbox"   id="checkall1" value="" style="margin-bottom: 5px">Leave Days<br>
                          <input type="checkbox"   id="checkall1" value="" style="margin-bottom: 5px">Manage User<br>
                          <input type="checkbox"   id="checkall1" value="" style="margin-bottom: 5px">Document<br>
                         <input type="checkbox"   id="checkall1" value="" style="margin-bottom: 5px">Salary</td></tr>
                  <tr><td></td><td ><input style="margin-top:10px" type="submit" class="buttonn submit_useradd" id="add_user" value="Add Company"> <input style="margin-top:10px" type="reset" class="buttonn" id="addinguser_close" value="Cancel"></td>
                  </tr></table></form>
	
</form>
			</div>
          </div><!--end add user form--->
          </div><!-- /.row -->
		  
        </section><!-- /.content -->
    
