 
<?php

use Phalcon\Tag as Tag;
?>
    
    <footer id="cmn_footer" style="margin-left:0;">
        <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.
        <div id="cmn_lang_box">
            <?php echo $t->_("Change_Language"); ?> : 
            <span id="cmn_lang_mm" class="cmn-icons cmn-icons-contry mm"></span>
            <span id="cmn_lang_jp" class="cmn-icons cmn-icons-contry jp"></span>
            <span id="cmn_lang_en" class="cmn-icons cmn-icons-contry en"></span>
        </div>
    </footer>
        <div id="notidetail" style="display:none;" class="navbar"></div>
    </body>
</html> 