<!DOCTYPE html>
<?php
if (!ini_get('date.timezone')) {
    date_default_timezone_set('UTC');
}
?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Notification</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <?php $this->assets->outputCss() ?>
    </head>
    <?php
//     var_dump($this->session->auth);
//     exit();

    if ($type == "noti") {
        ?>

        <section class="content">
            <?php echo $this->getContent() ?>
            <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script>
            <?php $this->assets->outputJs(); ?>
        </section>

        <?php
    } else {
        ?>

        <?php
        $this->partial('../../core/views/partials/header');
        ?>


        <?php $this->partial('../../core/views/partials/footer'); ?>




    <?php } ?>

</body>
</html>
