<!DOCTYPE html>

<?php

use Phalcon\Tag as Tag;
$this->partial('../../core/views/partials/header');

</div>
                                  <div id="notificationFooter"><a href="<?php echo $baseUri?>/notification/index/viewall"><span style="color:white"><?= $t->_("View All"); ?></span></a></div>
                                </div>
                            </li>
                            <!-- Tasks: style can be found in dropdown.less -->

                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 20px;">
                                   <!-- <img src="../../uploads/<?php echo  $this->session->user['member_profile'];?>" class="user-image" alt="User Image"/>-->
                                                                                  
                                    <span class="hidden-xs"><?php echo $this->session->user['member_login_name']; ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <!--<img src="../../common/img/profile.png" class="img-circle" alt="User Image" />-->
                                       
                                        <!--<img src="../../uploads/<?php echo  $this->session->user['member_profile'];?>" class="img-circle">-->
                                         <?php
                                                if($Noti['member_profile']==null){
                                                   $img = "profile1.jpg";}
                                                else{
                                                     $img=$Noti['member_profile'];
                                                      if(file_exists('./uploads/'.$img)){                                                            
                                                           $img=$img;                                                            
                                                      }else{  
                                                          $img = "profile1.jpg";                                                                 
                                                      }
                                                 }
                                      ?>                                                
                                        <img src="<?php echo $baseUri?>uploads/<?php echo  $img;?>"  class="img-circle" class="user-image" width="30px" alt="User Image"/>
                                        <p>
                                            <b><?php echo $this->session->user['member_login_name']; ?></b>
                                           <!-- <small><b>Member since Nov. 2012</b></small>-->
                                            <!--<small><b>Member since <?php echo "<i style='color:black'> \" ".$this->session->user['created_dt']." \"</i>";?></b></small>-->
                                            <small><b><?= $t->_("Member Since"); ?> </b><?php echo "<b style='color:white;font-size:13px;'>".date("M - Y", strtotime( $this->session->user['created_dt']))."</b>";?></small>
                                        </p>
                                    </li>

                                    <!-- Menu Footer-->
                                       <li class="user-footer">
                                              
                                 <?php 
         if($permission==1){
                
                
                ?>
                 <div class="pull-left">
                     <a href="<?php echo $baseUri;?>setting/index/admin" class="btn btn-default btn-flat" id="setting"><b><?php echo $t->_("Setting"); ?></b></a>
                                        </div>
                <?php
               
               } 
                  else {
               
                    ?> 
                      <div class="pull-left">
                                                    <a href="<?php echo $baseUri;?>setting/user" class="btn btn-default btn-flat"  id="setting"><b><?php echo $t->_("Setting"); ?></b></a>
                                                </div>
                <?php 
                         }
               
                
             
                ?>
                                        
                                        <div class="pull-right">
                                            <a href="#" class="btn btn-default btn-flat" id="btn_logout"><b><?= $t->_("Sign out"); ?></b></a>

                                        </div>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>                
                </nav>
        </header>
            
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar" id="sidepage" style="display:none;height: auto;">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar" >
                    <!-- Sidebar user panel -->                   

                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <aside>
                    <ul class="sidebar-menu">
                        <li class="header"><b>MAIN NAVIGATION</b></li>
                       <?php
           $count=1;
                        foreach ($this->session->auth as $key_name => $key_value) {                            
                       
                                                                                    $top = explode(" ", $key_value["link0"]);
                                                                                    $top_link = explode(" ", $key_value["link1"]);
                                                                                    if (strpos($key_name, 'user') !== false) {
                                                                                         if($key_name != 'show_user_notification' && $key_name != 'show_user_setting'){
                                                                                               if (count($key_value) > 2) {
                                                                                                 if (isset($top_link[1])) {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/user/' . strtolower($top_link[0] . $top_link[1]) . '"><img src="'.$baseUri.'common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                } else {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/index"><img src="'.$baseUri.'common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                          }
                                                                                          else{
                                                                                                if (isset($top[1])) {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/user/' . strtolower($top[0] . $top[1]) . '"><img src="'.$baseUri.'common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                } else {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/index"><img src="'.$baseUri.'common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                          }
                                                                                         }                                                                                          
                                                                                    } else {
                                                                                        if($key_name != 'show_admin_notification' && $key_name != 'show_admin_setting'){
                                                                                               if (count($key_value) > 2) {
                                                                                                 if (isset($top_link[1])) {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/index/' . strtolower($top_link[0] . $top_link[1]) . '"><img src="'.$baseUri.'common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                } else {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/'.strtolower($top_link[0]).'"><img src="'.$baseUri.'common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                               }
                                                                                                else{
                                                                                                 if (isset($top[1])) {
                                                                                                 echo '<li><a href="' . $baseUri . strtolower($top[0].$top[1]) . '/index/index"><img src="'.$baseUri.'common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                                else{
                                                                                                echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index"><img src="'.$baseUri.'common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                        }
                                                                                                $count++; 
                                                                                        }
                        }
                        }
                        ?>
                    </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">                     

            <?php
            echo $this->getContent();
            $this->assets->outputJs();
            ?>
        </div><!-- /.content-wrapper -->
    
<?php $this->partial('../../core/views/partials/footer'); ?>
