<?php $leavetypelength = count($Leavetype); ?> 
        <section class="content-header" >
          <h1>
            <?= $t->_("applyleave"); ?>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
            <li class="active"><?= $t->_("applyleave"); ?></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
         
         <div class="row">
	 <div class="col-md-12"><!--start add user form--->
         <?php $this->flashSession->output() ?>
	<div id="form_div">
	<div style="height:30px; background-color:#3c8dbc; padding:5px 0 5px 15px;"><font color="#fffff">Apply Leave Form</font></div>
        
        <form id="apply_form" width="650px" height="300px" style="padding:5px 0 5px 15px;" enctype="multipart/form-data"> 
            <table style="margin-left: 30px;" >
          
	<tr>
            
            <td width="200px"><?= $t->_("name"); ?></td>
           
            <td style="height:40px;" >
                    <input class="applyauto form-control" data-toggle="select" name="username" style="height:39px; width: 260px;" id="apply_form_name" placeholder="<?php echo $t->_("searchusername"); ?>" ><br>
                     <span id="apply_form_username_error"></span>
                     <input type="hidden" value="" id="formemberid" name="member_id" >
		</td>                
        </tr>        
        <tr>
		
		<td><?= $t->_("start_date"); ?></td>
                <td style="height:40px;">
                    <input type="text" class="datetimepicker form-control" name="sdate" id="apply_form_sdate" placeholder="Start Date" style="height:39px; width: 260px;">
                    <span id="apply_form_sdate_error"></span>
                </td>                
	</tr>
        
	<tr>
		<td><?= $t->_("end_date"); ?> </td>
                <td style="height:40px;">
                    <input type="text" class="datetimepicker form-control" name="edate" id="apply_form_edate" placeholder="End Date" style="height:39px; width: 260px;">
                    <span id="apply_form_edate_error"></span>                
                </td>
                
        </tr>
        <tr>
          
		<td><?= $t->_("leave_category"); ?></td>
                <td style="height:40px;">
                    <select class="select" data-toggle="select" name="leavetype">
                    <?php
                    foreach ($Leavetype as $data) {
                    ?>
                         <option value="<?php echo $data['leavetype_name']; ?>"><?php echo $data['leavetype_name']; ?></option>
                    <?php
                    }
                    ?> </select>    
                </td>
	</tr>
	<tr>
		<td><?= $t->_("leave_desc"); ?></td>
                <td >
                    <textarea name="description" id="apply_form_desc" style="width:260px;" rows="5" cols="30"  placeholder="Write Description"></textarea>
                    <span id="apply_form_desc_error"></span>
               </td>
	</tr>
        
	<tr>
		<td></td>		
                <td><br><input type="submit" value="Apply" class="buttonn" onclick="return false;" name="submit" id="apply_form_submit"><input type="reset" id="apply_cancel" class="buttonn" value="Cancel"></td>
		<td></td>
	</tr>
	</table>
	
</form>
			</div>
          </div><!--end add user form--->
          </div><!-- /.row -->
		  
        </section><!-- /.content -->
    
