<?php
    use Phalcon\Filter;
use Phalcon\Tag as Tag;
$length = count($Month);
//print_r(count($leave_result));

?>

<!-- Content Header (Page header) -->
<section class="content-header" id="showleavelist">
    <h1>
        Leave Lists
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home </a></li>
        <li class="active">Leave Lists</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <form id="frm_search" onsubmit="return false;">
            <select class="select" data-toggle="select" name="ltype" id="ltype">
                <option value="">Leave Type</option>
                <?php
                for($i=1;$i<=count($leave_result);$i++){
                ?>
                <option value="<?php echo $leave_result[$i]; ?>"><?php echo $leave_result[$i]; ?></option>
                <?php
                }
                ?>

            </select>
            <select class="select" data-toggle="select" name="month" id="month">
                <option value="">Month</option>
                <?php
                for ($i = 1; $i <= $length; $i++) {
                    ?>
                    <option value="<?php
                    if ($i < 10) {
                        echo '0' . $i;
                    }
                    else {
                        echo $i;
                    }
                    ?>"><?php echo $Month[$i]; ?></option>
                            <?php
                        }
                        ?>

            </select>
            <select class="select" data-toggle="select" name="namelist" id="namelist">
                <option value="">User Name</option>
                <?php
                foreach ($Getname as $result) {
                    ?>
                <option value="<?php echo $result->member_login_name; ?>"><?php echo $result->member_login_name; ?></option>

                    <?php
                }
                ?>


            </select>
            <input type="submit" class="buttonn" value="Search" id="search">
            <!--       <a href="#" class="button" id="search">Search</a>-->
            <a href="#" class="button export" onclick="Export.Export.apply(this,[$('table.listtbl'),'Leave_List.csv']);">Export</a>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px">Date</th>
                        <th width="150px">Name</th>
                        <th width="150px">Start Date</th>
                        <th width="150px">End Date</th>
                        <th width="150px">Leave days</th>
                        <th width="150px">Leave type</th>
                        <th width="150px">Leave description</th>
                        <th width="150px">Leave status</th>
                        <th width="150px">Leave day left</th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                   //print_r($Result);
                    
                    $filter = new Filter();
                    
                    $days=0;
                    foreach ($Result as $item) {
                       // print_r($item);exit;
                        ?>
                        <tr>
                            <td><?php  $dt=  explode(" ",$item->leaves->date);
                                echo $dt[0];
                                ?></td>                            
                            <td><?php echo $filter->sanitize($item->core->member_login_name, "string"); ?></td>
                            <td><?php $start_date= explode(" ", $item->leaves->start_date); 
                                      echo $start_date[0];
                                ?></td>                            
                            <td><?php $end_date= explode(" ", $item->leaves->end_date); 
                                      echo $end_date[0];
                                
                                ?></td>
                            <td><?php
                                echo $filter->sanitize($item->leaves->leave_days, "int");                                
                                //echo $days;
                                ?></td>
                            <td><?php
                                echo $filter->sanitize($item->leaves->leave_category, "string");
                                ?></td>
                            <td><?php
                                echo $filter->sanitize($item->leaves->leave_description, "string");
                                ?></td>
                             
                            <td><?php
                                
                        switch($filter->sanitize($item->leaves->leave_status, "string")){
                            case "0" : echo "Pending" ; break;
                            case "1" : echo "Confirmed";break;
                            case "2" : echo "Rejected";break;
                               
                        };
                                ?></td>
                            <td><font color="red"><?php
                    if($filter->sanitize($item->leaves->total_leavedays, "int") >=$max){
                            echo ($filter->sanitize($item->leaves->total_leavedays, "int"));
                            echo " left";
                    }
                    else{
                                
                    echo $max-($filter->sanitize($item->leaves->total_leavedays, "int"));}
                        
                                ?></font></td>
                        </tr>
                        </tr>
                        <?php
                    }
                    ?>

                </tbody>
                <tfoot style="display:none;"></tfoot>
            </table> 
          
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
