
<section class="content-header" style="height:auto;margin-top: 5px;">
    <h1>
        Leave Setting
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#"><i class="fa fa-dashboard"></i> Leave Days</a></li>
        <li class="active"> Leave Setting</li>
    </ol>
</section>

<br>
<div class="search-box">
            <form name="setting" id="search_frm" method="post" action="editleavesetting">
                <div id="Menu">
                    <?php foreach($leave_setting as $data){?>
                    <div id="leave_setting_div1">Maximum Leavedays allowed: 
                        <span>
                            <input type="text" value="<?php echo $data['max_leavedays']; ?>"  id="max_leavedays" name="max_leavedays" style="width: 31px; height: 26px;" disabled> Days
                        </span>
                    </div>
                    <div id="leave_setting_div2">Percentage of Fine On Basic Salary: 
                        <span>
                           <input type="text" value="<?php echo $data['fine_amount']; ?>" id="fine_amount" name="fine_amount" style="width: 31px; height: 26px;" disabled> %
                        </span>
                    </div>
                    <div id="leave_setting_div3">
                        <span>
                            <input type="button" class="btn btn-default editsetting" onclick="return false;" id="" value="Edit">
                            <input type="submit" class="btn btn-default savesetting" id="savesetting" value="Save" disabled>
                        </span>
                    </div>
                       
                    <?php }?>
                </div>
               <!--search btn-->
            </form>
</div><br>
<div class="buttons">
            <input type="button" class="addbtn add" onclick="return false;" value="Add New Leave Categories">
			
			
	 </div>
<form action="" method="post">
    
       
      <table class="listtbl">
  <thead>
    <tr>
			<th width="120px">ID</th>
			<th>Leave Type </th>
			
			
			
			<th width="50px"></th>
	</tr>
	
  </thead>
  <tbody>
      <?php $n=0;foreach($leave_typelist as $result){$n++;?>
      
        <tr>
			<td width="120px"><?php echo $n;?></td>
			<td><?php echo $result['leavetype_name'];?> </td>
			
			
			
			<td width="50px"><input type="button" class="btn btn-default ltypepopup" onclick="return false;" id="<?php echo $result['leavetype_id'];?>" value="Delete"></td>
	</tr>
      <?php } ?>
  </tbody>
      </table></form>
        <div id="edit_ltype_dia" class="navbar"></div>
        <div id="add_new_ltype" class="navbar"></div>
        
   

  

</body>