<?php
use Phalcon\Tag as Tag;
$length = count($Month);
?>
<!-- Content Header (Page header) -->
<section class="content-header" id="showleavelist"">
    <h1>
        <?= $t->_("leave_list"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?> </a></li>
        <li class="active"><?= $t->_("leave_list"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <form id="frm_search" onsubmit="return false;">
            <select class="select" data-toggle="select" name="ltype" id="ltype">
                <option value=""><?= $t->_("leave_type"); ?></option>
                <?php
                foreach ($Leavetype as $result) {
                    ?>
                <option value="<?php echo $result['leavetype_name']; ?>"><?php echo $result['leavetype_name']; ?></option>

                    <?php
                }
                ?>

            </select>
            <select class="select" data-toggle="select" name="month" id="month">
                <option value=""><?= $t->_("month"); ?></option>
                <?php
                for ($i = 1; $i <= $length; $i++) {
                    ?>
                    <option value="<?php
                    if ($i < 10) {
                        echo '0' . $i;
                    }
                    else {
                        echo $i;
                    }
                    ?>"><?php echo $Month[$i]; ?></option>
                            <?php
                        }
                        ?>

            </select>
<!--            <select class="select" data-toggle="select" name="namelist" id="namelist">
                <option value="">User Name</option>
                <?php
                foreach ($Getname as $result) {
                    ?>
                <option value="<?php echo $result->member_login_name; ?>"><?php echo $result->member_login_name; ?></option>

                    <?php
                }
                ?>


            </select>-->
            <input class="userauto" name="namelist" id="namelist" placeholder="<?= $t->_("searchusername"); ?>" autocomplete="off">

            <input type="submit" class="buttonn" value="<?= $t->_("search"); ?>" id="search">
            <!--       <a href="#" class="button" id="search">Search</a>-->
            <a href="#" class="button export" onclick="Export.Export.apply(this,[$('table.listtbl'),'Leave_List.csv']);"><?= $t->_("export"); ?></a>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px"><?= $t->_("date"); ?></th>
                        <th width="150px"><?= $t->_("name"); ?></th>
                        <th width="150px"><?= $t->_("start_date"); ?></th>
                        <th width="150px"><?= $t->_("end_date"); ?></th>
                        <th width="150px"><?= $t->_("leave_day"); ?></th>
                        <th width="150px"><?= $t->_("leave_category"); ?></th>
                        <th width="150px"><?= $t->_("leave_desc"); ?></th>
                        <th width="150px"><?= $t->_("leave_status");?></th>
                        <th width="150px"><?= $t->_("leave_left"); ?></th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                   //print_r($Result);
                    $days=0;
                    foreach ($Result as $item) {
                       // print_r($item);exit;
                        ?>
                        <tr>
                            <td><?php  $dt=  explode(" ",$item->leaves->date);
                                echo $dt[0];
                                ?></td>                            
                            <td><?php echo $item->core->member_login_name; ?></td>
                            <td><?php $start_date= explode(" ", $item->leaves->start_date); 
                                      echo $start_date[0];
                                ?></td>                            
                            <td><?php $end_date= explode(" ", $item->leaves->end_date); 
                                      echo $end_date[0];
                                
                                ?></td>
                            <td><?php
                                echo $item->leaves->leave_days;
                                ;
                                //echo $days;
                                ?></td>
                            <td><?php
                                echo $item->leaves->leave_category;
                                ?></td>
                            <td><?php
                                echo $item->leaves->leave_description;
                                ?></td>
                             
                            <td><?php
                                
                        switch($item->leaves->leave_status){
                            case "0" : echo "Pending" ; break;
                            case "1" : echo "Confirmed";break;
                            case "2" : echo "Rejected";break;
                               
                        };
                                ?></td>
                            <td><font color="red"><?php
                    if($item->leaves->total_leavedays >=$max){
                            echo ($item->leaves->total_leavedays-$max);
                            echo " Days  in absent";
                    }
                    else{
                                
                    echo $max-($item->leaves->total_leavedays);}
                        
                                ?></font></td>
                        </tr>
                        </tr>
                        <?php
                    }
                    ?>

                </tbody>
                <tfoot style="display:none;"></tfoot>
            </table> 
          
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
