<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    


use Phalcon\Tag as Tag;

$length = count($Month);
?>
<!-- Content Header (Page header) -->
<section class="content-header" id="showleavelist">
    <h1>
        <?= $t->_("leave_dayleft"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?> </a></li>
        <li class="active"><?= $t->_("leave_list"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
      
        
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px"><?= $t->_("name"); ?></th>
                         <th width="150px">Leave Day Carry</th>
                         <th width="150px">Total Leave Days</th>
                        <th width="150px"><?= $t->_("leave_left"); ?></th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                    //print_r($Result);
                    $days = 0;
                    foreach ($Result->items as $item) {
                        ?>
                        <tr>
                                                     
                            <td><?php echo $item->member_login_name; ?></td>
                             <td><font color="red"><?php
                                 echo $item->leaveday_carry;
                              
                                ?></font></td>
                             <td><font color="red"><?php
                                 echo ($max+$item->leaveday_carry);
                              
                                ?></font></td>
                            <td><font color="red"><?php
                                $absent_day = 0;
                                if (isset($absent[$item->member_id])) {
                                    $absent_day = $absent[$item->member_id];
                                }
                                if ($absent_day >= ($max+$item->leaveday_carry)) {
                                    echo (( $absent_day) - ($max+$item->leaveday_carry));
                                    echo " Days  in absent";
                                } else {
                                    echo ($item->leaveday_carry+$max) - ( $absent_day);
                                }
                                ?></font></td>
                        </tr>
                        </tr>
                        <?php
                    }
                    ?>

                </tbody>                
            </table> 

        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content">
        <ul class="pagination" style="margin-left:15px;">
            <?php
            if ($Result->last === 1) {
                
            } else {
                ?>
                <li><a href="leavedayleft">First</a></li>
                <li><a href="leavedayleft?page=<?= $Result->before; ?>">Previous</a></li>
                <li><a href="leavedayleft?page=<?= $Result->next; ?>">Next</a></li>
                <li><a href="leavedayleft?page=<?= $Result->last; ?>">Last</a></li>
                <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $Result->current, " of ", $Result->total_pages; ?></span></li>
                    <?php
                }
                ?>
        </ul>
    </div>
