<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    

?>
<section class="content-header" style="height:auto;margin-top: 5px;">
    <h1>
        <?= $t->_("leavesetting"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
        <li class="active"><?= $t->_("leavesetting"); ?></li>
    </ol>
</section>
<br>
<div class="search-box">
    <form name="setting" id="search_frm" method="post" action="editleavesetting">
        <div id="Menu" class="leaveallow">
            <?php foreach ($leave_setting as $data) { ?>
                <div id="leave_setting_div1"><?= $t->_("max_leavedays"); ?>: 
                    <span>
                        <input type="text" value="<?php echo $data['max_leavedays']; ?>"  id="max_leavedays" name="max_leavedays" style="width: 31px; height: 26px; margin-top: 8px;" disabled> <?= $t->_("days"); ?>
                    </span>
                </div>

                <div id="leave_setting_div3">
                    <span>
                        <input type="button" class="btn editsetting" onclick="return false;" id="editsetting" value="<?= $t->_("edit"); ?>">
                        <input type="submit" class="btn  savesetting" id="savesetting" value="<?= $t->_("save"); ?>" disabled>
                    </span>
                </div>

            <?php } ?>
        </div>
        <!--search btn-->
    </form>
</div><br>
<div class="buttons">
    <a href="#" class="buttonn add" id="addinguser"><?= $t->_("addleavetype"); ?></a>		
</div>
<form action="" method="post">

    <table class="listtbl">
        <thead>
            <tr>
                <th width="120px">ID</th>
                <th><?= $t->_("leave_type"); ?></th>
                <th width="50px"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $n = 0;
            foreach ($leave_typelist as $result) {
                $n++;
                ?>

                <tr>
                    <td width="120px"><?php echo $n; ?></td>
                    <td><?php echo $result['leavetype_name']; ?> </td>
                    <td width="50px"> <a href="#" onclick="return false;" style="float:right;margin-top: 5px;" class="indelete ltypepopup" id="<?php echo $result['leavetype_id']; ?>"></a></td>   
                </tr>
            <?php } ?>
        </tbody>
    </table></form>
<div id="edit_ltype_dia" class="navbar"></div>
<div id="add_new_ltype" class="navbar" style="display:none;" title="<?= $t->_('addleavetype'); ?>">
    <form id="Add_new_ltype"><table>
            <tr><td></td></tr><tr><td><?= $t->_("leave_type"); ?>:</td><td><input type="text" value="" name="ltype_name" placeholder="<?= $t->_("leavetype"); ?>"></td>                       
            <tr><td></td></tr>
            <tr><td></td><td colspan="3"><a href="#" class="button" id="Add_ltype"><?= $t->_("save"); ?></a><a href="#" class="button" id="cancel_ltype"><?= $t->_("applycancel"); ?></a></td></tr>
        </table></form>
</div>

</body>
