<?php

use Phalcon\Tag as Tag;

//print_r(count($leave_result));

?>

<!-- Content Header (Page header) -->
<section class="content-header" id="showleavelist"">
    <h1>
        <?= $t->_("People who take no leave"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?> </a></li>
        <li class="active"> <?= $t->_("People who take no leave"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
<!--                        <th width="150px"><?= $t->_("Working Start Date"); ?></th>-->
                        <th width="150px"><?= $t->_("name"); ?></th>
                        <th width="150px"><?= $t->_("Department"); ?></th>
                        <th width="150px"><?= $t->_("Position"); ?></th>
                        <th width="150px"><?= $t->_("Email"); ?></th>
                        <th width="150px"><?= $t->_("Phone"); ?></th>
                        <th width="150px"><?= $t->_("Address"); ?></th>      
                    </tr>

                </thead>
                <tbody>
                    <?php foreach($Result as $item){    
                            foreach ($item as $item ) {
                      ?>
                    <tr>
<!--                        <td> 
                                <?php  echo $item['working_start_dt'];?>
                        </td>-->
                        <td> 
                                <?php  echo $item['member_login_name'];?>
                        </td>
                        <td> 
                                <?php  echo $item['member_dept_name'];?>
                        </td>
                        <td> 
                                <?php  echo $item['position'];?>
                        </td>
                         <td> 
                                <?php  echo $item['member_mail'];?>
                        </td>
                        <td> 
                                <?php  echo $item['member_mobile_tel'];?>
                        </td>
                        <td> 
                                <?php  echo $item['member_address'];?>
                        </td>
                    </tr>
                <?php } }?>

                </tbody>
                <tfoot style="display:none;"></tfoot>
            </table> 
          
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
