 <?php use Phalcon\Tag as Tag; ?>

<!-- <link href='../css/fullcalendar.css' rel='stylesheet' />
<script src='../js/moment.min.js'></script>
<script src='../js/fullcalendar.min.js'></script>
<script src='../js/gcal.js'></script>
<script src='../js/cld.js'></script> -->
 <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Dashboard
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
        

          <div class="row">
		  <div class="col-md-12">
		  <div class="top_row"><?php echo Tag::image(array('img/Check-32.png', 'width' => 30)) ?><font style="color:red;">100 </font>staffs attended</div>
		  <div class="top_row"><?php echo Tag::image(array('img/absence.png', 'width' => 30)) ?><font style="color:red;">2</font>staffs absent</div>
		  </div>
            <div class="col-md-12">
			<div style="height:30px"></div>
              <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua" onclick="window.location.href='userlist'" id="pointer_style1">
                  <?php echo Tag::image(array('img/User-128.png')) ?>
                 Manage User
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green" onclick="window.location.href='todaylist'" id="pointer_style2">
                <?php echo Tag::image(array('img/View-List-128.png')) ?>
                 Attendance List
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow" onclick="window.location.href='leavelist'" id="pointer_style3">
                <?php echo Tag::image(array('img/Calendar-Date-02-128.png')) ?>
                 Leave Days
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red" onclick="window.location.href='salarylist'" id="pointer_style3">
                <?php echo Tag::image(array('img/Dollar-128.png')) ?>
                 Salary
              </div>
            </div><!-- ./col -->
          </div><!-- /.row -->
		  
            </div><!-- /.col -->
          </div><!-- /.row -->
		<div style="height:30px;"></div>
          <!-- Main row -->
          <div class="row">
            <!-- Left col -->
             <div class="col-md-8">
              <!-- MAP & BOX PANE -->
              <div class="box box-success">
                <div class="box-header with-border">
                  <h3 class="box-title">Holiday Lists</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                   
                  </div>
                </div><!-- /.box-header -->
                 <div class="box-body no-padding">
                  <div class="row">
                    <div class="col-md-9 col-sm-8">
                      
		     <!-- /.Calendar -->
		     <div id='calendar'></div>
                    </div><!-- /.col -->
                    <div class="col-md-3 col-sm-4">
		    
                      <div class="pad box-pane-right bg-green" style="min-height: 465px;">
                        <div class="description-block margin-bottom">
                          <div class="sparkbar pad" data-color="#fff">May 10th</div>
                          <h5 class="description-header">SunDay</h5>
                          <span class="description-text">Mothers' Day</span>
                        </div><!-- /.description-block -->
                        <div class="description-block margin-bottom">
                          <div class="sparkbar pad" data-color="#fff">May 25th</div>
                          <h5 class="description-header">Monday</h5>
                          <span class="description-text">Memorial Day</span>
                        </div><!-- /.description-block -->
                       
                      </div>
                    </div><!-- /.col -->
					
                  </div><!-- /.row -->
				  
                </div><!-- /.box-body -->
				
              </div><!-- /.box -->
             
            </div><!-- /.col -->

            <div class="col-md-4">
              
			  
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Latest News</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="row">
                    <div class="col-md-8">
                      <div class="chart-responsive">
                       <ul class="nav nav-pills nav-stacked" style="border-bottom:1px solid gray; width:100%;">
						<li>
						People who attend no leave
							<ul>
							<li>Mabel</li>
							<li>Rose</li>
							</ul>
						</li>
						</ul>
						<ul class="nav nav-pills nav-stacked">
						<li>
						People who take the leave most
							<ul>
							<li>Pabel</li>
							
							</ul>
						</li>
						</ul>
                      </div><!-- ./chart-responsive -->
                    </div><!-- /.col -->
                   
                  </div><!-- /.row -->
                </div><!-- /.box-body -->
                
              </div><!-- /.box -->

                <!-- USERS LIST -->
                  <div class="box box-danger">
                    <div class="box-header with-border">
                      <h3 class="box-title">Latest Members</h3>
                      <div class="box-tools pull-right">
                        <span class="label label-danger">4 New Members</span>
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body no-padding">
                      <ul class="users-list clearfix">
                        <li>
                           <?php echo Tag::image(array('img/user1-128x128.jpg')) ?>
                          <a class="users-list-name" href="#">Alexander Pierce</a>
                          <span class="users-list-date">Today</span>
                        </li>
                        <li>
                          <?php echo Tag::image(array('img/user8-128x128.jpg')) ?>
                          <a class="users-list-name" href="#">Norman</a>
                          <span class="users-list-date">Yesterday</span>
                        </li>
                        <li>
                          <?php echo Tag::image(array('img/user7-128x128.jpg')) ?>
                          <a class="users-list-name" href="#">Jane</a>
                          <span class="users-list-date">12 Jan</span>
                        </li>
                        <li>
                          <?php echo Tag::image(array('img/user6-128x128.jpg')) ?>
                          <a class="users-list-name" href="#">John</a>
                          <span class="users-list-date">12 Jan</span>
                        </li>
                        
                      </ul><!-- /.users-list -->
                    </div><!-- /.box-body -->
                    <div class="box-footer text-center">
                      <a href="javascript::" class="uppercase">View All Users</a>
                    </div><!-- /.box-footer -->
                  </div><!--/.box -->
                
				
            </div><!-- /.col -->
			
          </div><!-- /.row -->
		  
        </section><!-- /.content -->
        