<!DOCTYPE html>
<?php use Phalcon\Tag as Tag; ?>
<html>
    <head><style>.ui-dialog-titlebar-close {
  visibility: hidden;
}</style>
        <meta charset="UTF-8">
        <title>Attendance System</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>


        <!-- Ionicons -->
        <?php $this->assets->outputCss() ?>
    </head>
    <body class="skin-blue sidebar-mini">
          <?php error_reporting(0); ?>                                
        <?php    if($type == 'userlist'){     ?>              
        <header class="main-header">
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" style="margin-left:0;">   
                    <a><img src="../../common/img/menu.png"  class="sidebar-toggle" href="#sidepage" role="button">
                             <span class="sr-only">Toggle navigation</span>
                             </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">                           
                            <!-- Notifications: style can be found in dropdown.less -->
                              <li class="dropdown notifications-menu" >
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 20px;">
                                    <img src="../../common/img/noti.png">
                                    <span class="label label-warning"><?php if(count($this->session->noti)==0){ }else{echo count($this->session->noti);}?></span>
                                </a>
                                  <ul class="dropdown-menu">
                                    <li class="header">You have <?php echo count($this->session->noti);?> notifications</li>
                                       <?php foreach ($this->session->noti as $noti) {?>
                                    <li>
                                        <!-- inner menu: contains the actual data -->
                                        <ul class="menu">
                                            <li>
                                               <a href="#" onclick="return false;" class="notidetail" id="<?php echo  $noti['member_id']; echo","; echo $noti['start_date'];?>">
                                                    <img src="../../common/img/notid.png"> 
                                                    <?php if($this->session->user['member_login_name']=="admin"){
                                                    echo $noti['member_login_name'];?> apply  leave for <?php echo date("d-m-Y", strtotime( $noti['start_date']));}
                                                    else {?>admin<?php 
                            switch($noti['leave_status']){
                            
                            case "1" : echo " Confirmed";break;
                            case "2" : echo " Rejected";break;
                               
                        }?> <?php echo date("d-m-Y", strtotime( $noti['start_date']));}?>
                                                                                         
                                                </a>
                                            </li>
                                           
                                        </ul>
                                </li><?php } ?>
                                    <li class="footer"><a href="../../notification/index/viewall">View all</a></li>
                                </ul>
                            </li>
                            <!-- Tasks: style can be found in dropdown.less -->

                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 20px;">
                                    <img src="../../common/img/profile.png" class="user-image" alt="User Image"/>
                                    <span class="hidden-xs"><?php echo $this->session->user['member_login_name']; ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <img src="../../common/img/profile.png" class="img-circle" alt="User Image" />
                                        <p>
                                            <?php echo $this->session->user['member_login_name']; ?>
                                            <small>Member since Nov. 2012</small>
                                        </p>
                                    </li>

                                    <!-- Menu Footer-->
                                       <li class="user-footer">
                                      <?php $name=$this->session->user['member_login_name'];
        if ( $name=='admin'){?>
                                        <div class="pull-left">
                                            <a href="../../setting/index/index" class="btn btn-default btn-flat">Setting</a>
                                        </div>
            
        <?php }
        else
        {?> 
            <div class="pull-left">
                                            <a href="../../setting/user/usersetting" class="btn btn-default btn-flat">Setting</a>
                                        </div>
        <?php }
        ?>
                                        
                                        <div class="pull-right">
                                            <a href="#" class="btn btn-default btn-flat" id="btn_logout">Sign out</a>

                                        </div>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>                
                </nav>
        </header>
            
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar" id="sidepage" style="display:none;">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar"  >
                    <!-- Sidebar user panel -->                  

                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li class="header">MAIN NAVIGATION</li>
                        <?php
                        foreach ($this->session->auth as $key_name => $key_value) {
                            //the outer main menu
                            if (count($key_value) > 1) {

                                echo ' <li class="treeview"><a href="#"><img src="../../common/img/list.png" ><span>' . $key_value[0] . '</span></a>';
                            } else {
                                $top = explode(" ", $key_value[0]);
                                if (strpos($key_name, 'user') !== false) {

                                    if (isset($top[1])) {
                                        echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/user/' . strtolower($top[0] . $top[1]) . '"><img src="../../common/img/list.png" ><span>' . $key_value[0] . '</span></a></li>';
                                    } else {
                                        echo '<li><a href="' . $baseUri . strtolower($top[0]) . '"><img src="../../common/img/list.png" ><span>' . $key_value[0] . '</span></a></li>';
                                    }
                                } else {
                                    echo '<li><a href="' . $baseUri . strtolower($key_value[0]) . '/index"><img src="../../common/img/list.png" ><span>' . $key_value[0] . '</span></a></li>';
                                }
                            }

                            //for the sub menu
                            foreach ($key_value as $name => $value) {
                                //print "Key = " . $name . " Value = " . $value . "<BR>";
                                echo '<ul class="treeview-menu">';
                                if ($name > 0) {
                                    if ($v_result = explode(" ", $value)) {
                                        //set to link action value
                                        $link_val = strtolower($v_result[0] . $v_result[1]);
                                        $mod = explode(" ", $key_value[0]);
                                    }
                                    if (strpos($key_name, 'user') !== false) {
                                        echo ' <li><a href="' . $baseUri . strtolower($mod[0] . $mod[1]) . '/user/' . $link_val . '"> <img src="../../common/img/li.png" >' . $value . '</a></li>';
                                    } else {
                                        echo ' <li><a href="' . $baseUri . strtolower($mod[0] . $mod[1]) . '/index/' . $link_val . '"> <img src="../../common/img/li.png" >' . $value . '</a></li>';
                                    }
                                }

                                echo '</ul>';
                            }
                            echo '</li>';
                        }
                        ?>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>


            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left: 0;">
                <section class="content">
                    <?php echo $this->getContent() ?>
                    <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script>
                    <?php $this->assets->outputJs(); 
                          echo Tag::javascriptInclude("apps/manageuser/js/useredit.js");
                    ?>
                </section>
            </div><!-- /.content-wrapper -->

            <footer class="main-footer" style="margin-left:0;">
                <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.
            </footer>
             
        <?php }  
        else {            
        ?>

                <section class="content">
                    <?php echo $this->getContent() ?>
                    <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script>
                    <?php $this->assets->outputJs(); ?>
                </section>

            <?php
        }
        ?>
        </div><!-- ./wrapper -->
<div id="notidetail" style=" display:none;border: 1px solid;background-color:white;" class="navbar">
    
</div>


    </body>
</html>
