<!DOCTYPE html>
<?php use Phalcon\Tag as Tag; ?>
<html>
    <head>
      
        <meta charset="UTF-8">
        <title>Attendance System</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?php $this->assets->outputCss() ?>
    </head>
    <body class="skin-blue sidebar-mini">
          <?php error_reporting(0); ?>   
        
        <header class="main-header">
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" id="fixedheader" style="margin-left:0;">   
                    <a><img src="<?php echo $baseUri?>common/img/menu.png"  class="sidebar-toggle" href="#sidepage" role="button">
                             <span class="sr-only">Toggle navigation</span>
                             </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav"> 
                                
                        
                            <!-- Tasks: style can be found in dropdown.less -->

                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 20px;">
                                   <!-- <img src="../../uploads/<?php echo  $this->session->user['member_profile'];?>" class="user-image" alt="User Image"/>-->
                                     <?php
                                                if($noti['member_profile']==null){
                                                   $img = "profile1.jpg";}
                                                else{
                                                     $img=$noti['member_profile'];
                                                      if(file_exists('./uploads/'.$img)){                                                            
                                                           $img=$img;                                                            
                                                      }else{  
                                                          $img = "profile1.jpg";                                                                 
                                                      }
                                                 }
                                      ?>                                                
                                    <span class="hidden-xs"><?php echo $this->session->user['login_name']; ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <!--<img src="../../common/img/profile.png" class="img-circle" alt="User Image" />-->
                                       
                                        <!--<img src="../../uploads/<?php echo  $this->session->user['member_profile'];?>" class="img-circle">-->
                                         <?php
                                                if($noti['member_profile']==null){
                                                   $img = "profile1.jpg";}
                                                else{
                                                     $img=$noti['member_profile'];
                                                      if(file_exists('./uploads/'.$img)){                                                            
                                                           $img=$img;                                                            
                                                      }else{  
                                                          $img = "profile1.jpg";                                                                 
                                                      }
                                                 }
                                      ?>                                                
                                        <img src="<?php echo $baseUri?>uploads/<?php echo  $img;?>"  class="img-circle" class="user-image" width="30px" alt="User Image"/>
                                        <p>
                                            <b><?php echo $this->session->user['login_name']; ?></b>
                                           <!-- <small><b>Member since Nov. 2012</b></small>-->
                                            <!--<small><b>Member since <?php echo "<i style='color:black'> \" ".$this->session->user['created_dt']." \"</i>";?></b></small>-->
                                            <small><b><?= $t->_("Member Since"); ?> </b><?php echo "<b style='color:white;font-size:13px;'>".date("M - Y", strtotime( $this->session->user['created_dt']))."</b>";?></small>
                                        </p>
                                    </li>

                                    <!-- Menu Footer-->
                                       <li class="user-footer">
                                              
                                 <?php 
   
              
               
                
             
                ?>
                                        
                                        <div class="pull-right">
                                            <a href="#" class="btn btn-default btn-flat" id="btn_logout"><b><?= $t->_("Sign out"); ?></b></a>

                                        </div>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>                
                </nav>
        </header>
            
            <!-- Left side column. contains the logo and sidebar -->
            

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">                     
                <?php     
                          //start for the left menu for each module
                          $j=0;
                          foreach ($this->session->auth as $key_name => $key_value) {                                 
                                       $top = explode(" ", $key_value["link0"]);
                                        if(strtolower($top[0] . $top[1]) ==$module_name) {
                                               if(count($key_value) >2 ) {
                                                             echo '<div class="row"><div class="col-sm-2 link">';
                                                             echo '<aside class="sidebar-menu">';
                                                           foreach ($key_value as $name => $value) {
                                                                                if($j > 1){
                                                                                                if($j %2 ==0){
                                                                                                    $link_name=$value;
                                                                                                }
                                                                                                if(is_string($name))
                                                                                                {
                                                                                                            if ($v_result = explode(" ", $value)) {
                                                                                                                //set to link action value
                                                                                                                $link_val = strtolower($v_result[0] . $v_result[1]);
                                                                                                                $mod = explode(" ", $key_value["link0"]);
                                                                                                            }
                                                                                                            if (strpos($key_name, 'user') !== false) {
                                                                                                             if($key_name == 'show_admin_user'){
                                                                                                              echo ' <li style="border-bottom:1px solid #aaa;"><a href="' . $baseUri . strtolower($mod[0] . $mod[1]) . '/index/' . $link_val . '">' . $link_name . '</a></li>';       
                                                                                                             }
                                                                                                             else{
                                                                                                             echo ' <li style="border-bottom:1px solid #aaa;"><a href="' . $baseUri . strtolower($mod[0] . $mod[1]) . '/user/' . $link_val . '">' . $link_name . '</a></li>';
                                                                                                             }
                                                                                                         } 
                                                                                                         else {
                                                                                                             echo ' <li style="border-bottom:1px solid #aaa;"><a href="' . $baseUri . strtolower($mod[0] . $mod[1]) . '/index/' . $link_val . '">' . $link_name . '</a></li>';
                                                                                                         }       
                                                                                               }
                                                                                        }
                                                                                   $j++;
                                                                                }
                                                                          echo '</aside></div><div class="col-sm-10">';
                                                                   }
                                                            }
                               }                               
                               //End of the left menu for each module
                                  echo '<section class="content">';
                                  echo $this->getContent();
                                  $this->assets->outputJs();
                                 echo '</section></div></div>';
                           ?>
            <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script> 
        </div><!-- /.content-wrapper -->

        <footer class="main-footer" style="margin-left:0;">
            <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.
        
        </footer>
       
<div id="notidetail" style=" display:none;" class="navbar">
    
</div>


    </body>
</html>

