<!DOCTYPE html>
<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    
 

use Phalcon\Tag as Tag; ?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Attendance System</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?php $this->assets->outputCss() ?>
    </head>
    <body class="skin-blue sidebar-mini">

        <header class="main-header">
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" id="fixedheader" style="margin-left:0;">   
                <a class="sidebar-toggle" role="button" href="#sidepage">
                    <span id="btn_show_menu" class="cmn-icons cmn-icons-toggle"></span>
                        </a>

                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">

                    <ul class="nav navbar-nav"> 
                      
                      
                        <!-- Notifications: style can be found in dropdown.less -->
                     
                        <!-- Tasks: style can be found in dropdown.less -->

                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" id="cmn_login_name" data-toggle="dropdown">
                                <span class="hidden-xs">Super Admin</span>
                            </a>

                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                              <p>
                                        <b>Super Admin</b>
                                        <small><b><?php echo $t->_("Member Since"); ?> </b><?php echo "<b style='color:white;font-size:13px;'>" . date("M - Y", strtotime($this->session->user['created_dt'])) . "</b>"; ?></small>
                                    </p>
                                </li>

                                <!-- Menu Footer-->
                                <li class="user-footer">

                                        

                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat" id="btn_logout"><b><?php echo $t->_("Sign out"); ?></b></a>

                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>                
            </nav>
        </header>


        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar" id="sidepage" style="display:none;height: auto;">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->                   

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <aside>
                    <ul class="sidebar-menu">
                        <li class="header"><b>MAIN NAVIGATION</b></li>
                        <li><a href="<?php echo $baseUri ?>managecompany"><img src=" /salts/common/img/list2.png"><span><b>Manage Company</b></span></a></li>
                        <li><a href="<?php echo $baseUri ?>managecompany/module"><img src=" /salts/common/img/list2.png"><span><b>Manage Module</b></span></a></li>
                </aside></section>
            <!-- /.sidebar -->
        </aside>  

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">                     
            <?php
            //start for the left menu for each module
            //End of the left menu for each module
            echo '<section class="content">';
            echo $this->getContent();
            $this->assets->outputJs();
            echo '</section></div></div>';
            ?>
            <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script> 
        </div><!-- /.content-wrapper -->

        <footer class="main-footer" style="margin-left:0;">
            <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.

        </footer>

        <div id="notidetail" style=" display:none;" class="navbar">

        </div>


    </body>
</html>

