<!DOCTYPE html>
<?php

use Phalcon\Tag as Tag; ?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Attendance System</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?php $this->assets->outputCss() ?>
    </head>
    <body class="skin-blue sidebar-mini">
        <?php error_reporting(0); ?>   

        <header class="main-header">
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" id="fixedheader" style="margin-left:0;">   
                <a><img src="<?php echo $baseUri ?>common/img/menu.png"  style="height: 54px"  class="sidebar-toggle" href="#sidepage" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav"> 


                        <!-- Tasks: style can be found in dropdown.less -->

                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 20px;">

                                <?php
                                if ($Noti['member_profile'] == null) {
                                    $img = "profile1.jpg";
                                } else {
                                    $img = $Noti['member_profile'];
                                    if (file_exists('./uploads/' . $img)) {
                                        $img = $img;
                                    } else {
                                        $img = "profile1.jpg";
                                    }
                                }
                                ?>                                                
                                <span class="hidden-xs"><?php echo $this->session->user['login_name']; ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">                                
                                    <?php
                                    if ($Noti['member_profile'] == null) {
                                        $img = "profile1.jpg";
                                    } else {
                                        $img = $Noti['member_profile'];
                                        if (file_exists('./uploads/' . $img)) {
                                            $img = $img;
                                        } else {
                                            $img = "profile1.jpg";
                                        }
                                    }
                                    ?>                                                
                                    <img src="<?php echo $baseUri ?>uploads/<?php echo $img; ?>"  class="img-circle" class="user-image" width="30px" alt="User Image"/>
                                    <p>
                                        <b><?php echo $this->session->user['login_name']; ?></b>                                     
                                        <small><b><?= $t->_("Member Since"); ?> </b><?php echo "<b style='color:white;font-size:13px;'>" . date("M - Y", strtotime($this->session->user['created_dt'])) . "</b>"; ?></small>
                                    </p>
                                </li>

                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat" id="btn_logout"><b><?= $t->_("Sign out"); ?></b></a>
                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>                
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar" id="sidepage" style="display:none;height: auto;">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->                   

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <aside>
                    <ul class="sidebar-menu">
                        <li class="header"><b>MAIN NAVIGATION</b></li>
                        <li><a href="<?php echo $baseUri ?>managecompany"><img src=" /salts/common/img/list2.png"><span><b>Manage Company</b></span></a></li>
                        <li><a href="<?php echo $baseUri ?>managecompany/module"><img src=" /salts/common/img/list2.png"><span><b>Manage Module</b></span></a></li>
                </aside></section>
            <!-- /.sidebar -->
        </aside>  

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">                     
            <?php
            //start for the left menu for each module
            //End of the left menu for each module
            echo '<section class="content">';
            echo $this->getContent();
            $this->assets->outputJs();
            echo '</section></div></div>';
            ?>
            <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script> 
        </div><!-- /.content-wrapper -->

        <footer class="main-footer" style="margin-left:0;">
            <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.

        </footer>

        <div id="notidetail" style=" display:none;" class="navbar">

        </div>


    </body>
</html>

