<?php

use Phalcon\Tag as Tag; ?>
<div id="home_header">
    <div id="logo" class="sprite-image crm-logo"></div>

<!--    <div id="btn_user" class="header-login-name"><?= $user['name'] ?></div>
<div id="btn_maintenace" class="sprite-image icon-24 icon-24-settings"></div>-->
</div>
<div id="main_contents">
    <?php // echo $this->tag->linkTo("attendance/index/todaylist", "Sign Up Here!"); ?>
    <?php
    foreach ($this->session->auth as $key_name => $key_value) {

        $this->response->redirect('dashboard');



//        foreach ($key_value as $name => $value) {
////            print "Key = " . $name . " Value = " . $value . "<BR>";exit;
//            if ($name == 0) {
//                echo $value . '<br>';
//            }
//            if ($name > 0) {
//                print "Key = " . $name . " Value = " . $value . "<BR>";
//            }
//        }

        foreach ($key_value as $name => $value) {
            //print "Key = " . $name . " Value = " . $value . "<BR>";
            if ($name == 0) {
                echo $value . '<br>';
            }
            if ($name > 0) {
                print "Key = " . $name . " Value = " . $value . "<BR>";
            }
        }
    }
    ?>
    <!--   <a href="{{ url("singup/1002") }}">Edit</a>-->
</div>
