<?php
/**
 * return user selected timezone for changing timezone
 * @return string
 * @author Su Zin Kyaw
 */
function tz_list() {
  $zones_array = array();
  $timestamp = time();
  foreach(timezone_identifiers_list() as $key => $zone) {
    date_default_timezone_set($zone);
    $zones_array[$key]['zone'] = $zone;
    $zones_array[$key]['diff_from_GMT'] = 'UTC/GMT ' . date('P', $timestamp);
  }
  return $zones_array;
}
?>


        <section class="content-header">
          <h1>
            Profile
          </h1>
          
        </section>

        <!-- Main content -->
        <section class="content">
         
         <div class="row">
	 <div class="col-md-12"><!--start add user form--->
	<div id="form_div">
	<div style="height:30px; background-color:#428bca; padding:5px 0 5px 15px;"><font color="#fffff">Add user form</font></div>
            <?php
	foreach ($userdetail  as $result) {
  ?>
        <form action="changeprofile" method="post" width="650px" height="300px" style="padding:5px 0 5px 15px;" enctype="multipart/form-data"> 
        <div ><img src="../../common/img/profile.png">
        </div>
            <input type="hidden" id="temp_password" name="temp_password" value="<?php echo  $result['member_password'];?>" disabled>
            <input type="hidden" id="file" name="temp_file" value="<?php echo  $result['member_profile'];?>" disabled>

	<table width="650px" height="300px"> 
            <tr>
                <td name="pp">Change Profile Picture </td>
                <td ><input type="file"   name="fileToUpload"   id="fileToUpload" > 
            </tr>
	<tr>
            
            <td >User Name :</td>
           
		<td>
		<input type="text" id="username" name="username" value="<?php echo  $result['member_login_name'];?>" disabled style="width:350px;">
		</td>
        </tr>
        <tr>
		
		<td>Password :</td>
                <td><input type="password" id="password" name="password" value="<?php echo  $result['member_password'];?>" disabled style="width:350px;"></td>
	</tr>
	<tr>
		<td>Department:</td>
		<td><input type="text" name="dept" id="dept" value="<?php echo  $result['member_dept_name'];?>" disabled style="width:350px;"></td>
        </tr>
        <tr>
          
		<td>Position	:</td>
		<td><input type="text" name="position" id="position" value="<?php echo  $result['job_title'];?>" disabled style="width:350px;"></td>
	</tr>
	<tr>
		<td>Email :</td>
		<td><input type="email" name="email" id="email" value="<?php echo  $result['member_mail'];?>" disabled style="width:350px;">
               </td>
	</tr>
        <tr>
		<td>Phone no</td>
		<td><input type="text" id="phno" name= "phno" value="<?php echo  $result['member_mobile_tel'];?>" disabled style="width:350px;"></td>
	</tr>
       
	<tr>
		<td>Address :</td>
		<td colspan="4"><textarea style="width:350px;" rows="5" id="add" name="add" cols="50" readonly><?php echo  $result['member_address'];?></textarea ></td>
	</tr><?php }
        ?>
        <tr>
            <td>Time Zone : </td>
            <td><select style= "width:350px;  margin-top: 9px; margin-bottom: 9px;" name="timezone" id="timezone" disabled>
    <option value="0">Please, select timezone</option>
    <?php foreach(tz_list() as $t) { ?>
      <option value="<?php print $t['diff_from_GMT'];echo " ";echo $t['zone'] ?>">
        <?php print $t['diff_from_GMT'] . ' - ' . $t['zone'] ?>
      </option>
    <?php } ?>
                </select></td>
        </tr>
	<tr>
		<td></td>
		
                <td><input type="submit" id="save" class="buttonn" value="Save" disabled><input type="button" id="edit" class="buttonn" value="Edit"></td>
		<td></td>
	</tr>
	</table>
	
</form>
			</div>
          </div><!--end add user form--->
          </div><!-- /.row -->
		  
        </section><!-- /.content -->
        

  
