<?php
$this->partial('../../core/views/partials/header');
?>
 
<!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">            


            <div class="row-fluid">
                <div class="sidebar-menu col-md-2 helpcenter link">
                    <img src="<?php echo $baseUri ?>/apps/help/img/app_help.png">   
                    <label><?php echo $t->_("Search Help"); ?></label>
                    <ul>
                        <li><a href="dashboard" id="" class="allhelpimg" ><?php echo $t->_("Dashboard"); ?></a></li>
                        <li>
                            <a href="" onclick="return false;" class="allhelpimg tog"><?php echo $t->_("Attendance List"); ?></a>
                            <ul class="togshow col-xs-offset-0" style="display:none;margin-top:-15px;">
                                <li><a href="todayattlist"><?php echo $t->_("Today List"); ?></a></li>
                                <li><a href="monthlyattlist"><?php echo $t->_("Monthly List"); ?></a></li>
                                <li><a href="monthlyattchart"><?php echo $t->_("Monthly Chart"); ?></a></li>
                            </ul>
                        </li>       
                        <li><a href="manageuser" class="allhelpimg"><?php echo $t->_("Manage User"); ?></a></li>
                        <li><a href="#" onclick="return false;" class="allhelpimg tog"><?php echo $t->_("Leave Days"); ?></a>
                            <ul class="togshow col-xs-offset-0" style="display:none;margin-top:-15px;">
                                <li><a href="applyleave"><?php echo $t->_("Apply Leave"); ?></a></li>
                                <li><a href="leavelists"><?php echo $t->_("Leave Lists"); ?></a></li>
                                <li><a href="leavesetting"><?php echo $t->_("Leave Setting"); ?></a></li>
                                <li><a href="leavedayleft"><?php echo $t->_("Leave DayLeft"); ?></a></li>
                            </ul>
                        </li>
                        <li><a href="#" class="allhelpimg tog"><?php echo $t->_("Salary"); ?></a>
                            <ul class="togshow col-xs-offset-0" style="display:none;margin-top:-15px;">
                                <li><a href="addsalary"><?php echo $t->_("Add Salary"); ?></a></li>
                                <li><a href="salarylists"><?php echo $t->_("Salary Lists"); ?></a></li>
                                <li><a href="monthlysallists"><?php echo $t->_("Monthly Salary Lists"); ?></a></li>
                                <li><a href="salarysetting"><?php echo $t->_("Salary Setting"); ?></a></li>
                                <li><a href="allowance"><?php echo $t->_("Allowance"); ?></a></li> 
                            </ul>
                        </li>        
                        <li><a href="#" onclick="return false;" class="allhelpimg tog"><?php echo $t->_("Document"); ?></a>
                            <ul class="togshow col-xs-offset-0" style="display:none;margin-top:-15px;">
                                <li><a href="letterhead"><?php echo $t->_("Letter Head"); ?></a></li>
                                <li><a href="ssbdocument"><?php echo $t->_("SSB"); ?></a></li>
                                <li><a href="taxdocument"><?php echo $t->_("Tax Document"); ?></a></li>
                                <li><a href="salaryreferdocument"><?php echo $t->_("SalaryReferDocument"); ?></a></li>
                                <li><a href="ssbapplyform"><?php echo $t->_("SSB Apply Form"); ?></a></li>
                                <li><a href="ssbresignform"><?php echo $t->_("SSB Resign Form"); ?></a></li>
                            </ul>
                        </li>   
                    </ul>
                </div>
                <?php
                echo $this->getContent();
                $this->assets->outputJs();
                ?>
            </div><!-- /.content-wrapper -->
        </div>
    <footer id="help_footer" style="margin-left:0;">
        <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.
        <div id="help_lang_box">
            <?php echo $t->_("Change_Language"); ?> : 
            <a href="../../core/index/setLanguage/en"><span id="cmn_lang_mm" class="cmn-icons cmn-icons-contry mm"></span></a>
            <a href="../../core/index/setLanguage/jp"><span id="cmn_lang_jp" class="cmn-icons cmn-icons-contry jp"></span></a>
            <a href="../../core/index/setLanguage/mm"><span id="cmn_lang_en" class="cmn-icons cmn-icons-contry en"></span></a>
        </div>
    </footer>
        <div id="notidetail" style="display:none;" class="navbar"></div>
    </body>
</html> 
