<!DOCTYPE html>
<?php

use Phalcon\Tag as Tag; ?>
<html>
    <head><style>.ui-dialog-titlebar-close {
                visibility: hidden;
            }</style>
        <meta charset="UTF-8">
        <title>Search Help</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?php $this->assets->outputCss() ?>
    </head>
    <body class="skin-blue sidebar-mini" >
        <?php error_reporting(0); ?>                                
        <header class="main-header">
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" id="fixedheader" style="margin-left:0;">   
                <a><img src="<?php echo $baseUri ?>common/img/menu.png"  style="height: 54px" class="sidebar-toggle" href="#sidepage" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">

                    <ul class="nav navbar-nav"> 
                        <li>
                            <a href="<?php echo $baseUri ?>help/index/searchHelp" class="" title="<?php echo $t->_("Help"); ?>" id="help_icon" style="padding-top: 20px;">
                                <img src="<?php echo $baseUri ?>common/img/help_browser.png">
                            </a>
                        </li>  
                        <!-- Notifications: style can be found in dropdown.less -->
                        <li class="dropdown notifications-menu" >
                            <a href="#" class="<?php
                            if (count($Noti) == 0) {
                                echo "nonoti";
                            } else {
                                echo "noti";
                            }
                            ?>" id="noti" style="padding-top: 20px;">
                                <img src="<?php echo $baseUri ?>common/img/noti.png">
                                <span class="label label-warning"><?php
                                    if (count($Noti) == 0) {
                                        
                                    } else {
                                        echo count($Noti);
                                    }
                                    ?></span>
                            </a>



                            <div id="notificationContainer">
                                <div id="notificationTitle"><?php echo $t->_("Notification"); ?></div>
                                <div id="notificationsBody" class="notifications">

                                </div>
                                <div id="notificationFooter"><a href="<?php echo $baseUri ?>notification/index/viewall"><span style="color:white"><?php echo $t->_("View All"); ?></span></a></div>
                            </div>
                        </li>
                        <!-- Tasks: style can be found in dropdown.less -->
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 20px;">
                                <?php
                                if ($this->session->user['member_profile'] == null) {
                                    $img = "profile1.jpg";
                                } else {
                                    $img = $this->session->user['member_profile'];
                                    if (file_exists('./uploads/' . $img)) {
                                        $img = $img;
                                    } else {
                                        $img = "profile1.jpg";
                                    }
                                }
                                ?>                                                 
                                <img src="<?php echo $baseUri ?>uploads/<?php echo $img; ?>"  style="box-shadow: 2px 3px 2px #428bca;width:30px;height:25px;" class="img-circle" class="user-image" width="30px" alt="User Image"/>
                                <span class="hidden-xs"><?php echo $this->session->user['member_login_name']; ?></span>
                            </a>

                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <?php
                                    if ($this->session->user['member_profile'] == null) {
                                        $img = "profile1.jpg";
                                    } else {
                                        $img = $this->session->user['member_profile'];
                                        if (file_exists('./uploads/' . $img)) {
                                            $img = $img;
                                        } else {
                                            $img = "profile1.jpg";
                                        }
                                    }
                                    ?>                                                 
                                    <img src="<?php echo $baseUri ?>uploads/<?php echo $img; ?>"  class="img-circle" class="user-image" width="30px" alt="User Image"/>
                                    <p>
                                        <b><?php echo $this->session->user['member_login_name']; ?></b>
                                        <small><b><?php echo $t->_("Member Since"); ?> </b><?php echo "<b style='color:white;font-size:13px;'>" . date("M - Y", strtotime($this->session->user['created_dt'])) . "</b>"; ?></small>
                                    </p>
                                </li>

                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <?php
                                    if ($permission == 1) {

                                        $this->view->disable();
                                        // $this->response->redirect('attendancelist/index/todaylist');
                                        ?>
                                        <div class="pull-left">
                                            <a href="<?php echo $baseUri ?>setting/index" class="btn btn-default btn-flat" id="setting"><b><?php echo $t->_("Setting"); ?></b></a>
                                        </div>
                                        <?php
                                    } else {
                                        ?> 
                                        <div class="pull-left">
                                            <a href="<?php echo $baseUri ?>setting/user/usersetting" class="btn btn-default btn-flat"  id="setting"><b><?php echo $t->_("Setting"); ?></b></a>
                                        </div>
                                    <?php }
                                    ?>

                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat" id="btn_logout"><b><?php echo $t->_("Sign out"); ?></b></a>

                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>                
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar" id="sidepage" style="display:none;height: auto;">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar" >
                <!-- Sidebar user panel -->                   

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <aside>
                    <?php //print_r($this->session->auth); 
                    ?>
                    <ul class="sidebar-menu">
                        <li class="header"><b>MAIN NAVIGATION</b></li>
                        <?php
                        $count = 1;
                        foreach ($this->session->auth as $key_name => $key_value) {

                            $top = explode(" ", $key_value["link0"]);
                            $top_link = explode(" ", $key_value["link1"]);
                            if (strpos($key_name, 'user') !== false) {
                                if ($key_name != 'show_user_notification' && $key_name != 'show_user_setting') {
                                    if (count($key_value) > 2) {
                                        if (isset($top_link[1])) {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/user/' . strtolower($top_link[0] . $top_link[1]) . '"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        } else {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/index"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        }
                                    } else {
                                        if (isset($top[1])) {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/user/' . strtolower($top[0] . $top[1]) . '"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        } else {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/index"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        }
                                    }
                                }
                            } else {
                                if ($key_name != 'show_admin_notification' && $key_name != 'show_admin_setting') {
                                    if (count($key_value) > 2) {
                                        if (isset($top_link[1])) {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/index/' . strtolower($top_link[0] . $top_link[1]) . '"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        } else {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/' . strtolower($top_link[0]) . '"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        }
                                    } else {
                                        if (isset($top[1])) {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/index"><img src="../../common/img/list' . $count . '.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        } else {
                                            echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index"><img src="../../common/img/list' . $count . '.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                        }
                                    }
                                }
                            }
                        }
                        ?>
                    </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">            


            <div class="row-fluid">
                <div class="sidebar-menu col-md-2 helpcenter">
                    <img src="<?php echo $baseUri ?>help/app_help (2).png">   
                    <label><?php echo $t->_("Search Help"); ?></label>
                    <ul>
                        <li><a href="dashboard" id="" class="allhelpimg" ><?php echo $t->_("Dashboard"); ?></a></li>
                        <li>
                            <a href="" onclick="return false;" class="allhelpimg tog"><?php echo $t->_("Attendance List"); ?></a>
                            <ul class="togshow col-xs-offset-2" style="display:none;margin-top:-15px;">
                                <li><a href="todayattlist"><?php echo $t->_("Today Attendance List"); ?></a></li>
                                <li><a href="monthlyattlist"><?php echo $t->_("Monthly Attendance List"); ?></a></li>
                                <li><a href="monthlyattchart"><?php echo $t->_("Monthly Attendance Chart"); ?></a></li>
                            </ul>
                        </li>       
                        <li><a href="manageuser" class="allhelpimg"><?php echo $t->_("Manage User"); ?></a></li>
                        <li><a href="#" onclick="return false;" class="allhelpimg tog"><?php echo $t->_("Leave Days"); ?></a>
                            <ul class="togshow col-xs-offset-2" style="display:none;margin-top:-15px;">
                                <li><a href="applyleave"><?php echo $t->_("Apply Leave"); ?></a></li>
                                <li><a href="leavelists"><?php echo $t->_("Leave Lists"); ?></a></li>
                                <li><a href="leavesetting"><?php echo $t->_("Leave Setting"); ?></a></li>
                            </ul>
                        </li>
                        <li><a href="calendar" class="allhelpimg"><?php echo $t->_("Calendar"); ?></a></li>
                        <li><a href="#" class="allhelpimg tog"><?php echo $t->_("Salary"); ?></a>
                            <ul class="togshow col-xs-offset-2" style="display:none;margin-top:-15px;">
                                <li><a href="addsalary"><?php echo $t->_("Add Salary"); ?></a></li>
                                <li><a href="salarylists"><?php echo $t->_("Salary Lists"); ?></a></li>
                                <li><a href="monthlysallists"><?php echo $t->_("Monthly Salary Lists"); ?></a></li>
                                <li><a href="salarysetting"><?php echo $t->_("Salary Setting"); ?></a></li>
                                <li><a href="allowance"><?php echo $t->_("Allowance"); ?></a></li> 
                            </ul>
                        </li>        
                        <li><a href="#" onclick="return false;" class="allhelpimg tog"><?php echo $t->_("Document"); ?></a>
                            <ul class="togshow col-xs-offset-2" style="display:none;margin-top:-15px;">
                                <li><a href="letterhead"><?php echo $t->_("Letter Head"); ?></a></li>
                                <li><a href="ssbdocument"><?php echo $t->_("SSB & Tax Document"); ?></a></li>
                            </ul>
                        </li>   
                    </ul>
                </div>
                <?php
                echo $this->getContent();
                $this->assets->outputJs();
                ?>
                <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script> 
            </div><!-- /.content-wrapper -->
        </div>
        <footer class="main-footer" style="margin-left:0;">
            <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.
            <div class="language">
                   <?php echo $t->_("Change_Language"); ?> : <?php echo Tag::linkTo("core/index/setLanguage/en", "<img src='../../common/img/english.png' width='20px'>") ?> &nbsp;&nbsp; <?php echo Tag::linkTo("core/index/setLanguage/jp", "<img src='../../common/img/japan.jpg' width='25px'>") ?> &nbsp;&nbsp; <?php echo Tag::linkTo("core/index/setLanguage/mm", "<img src='../../common/img/myanmar.jpg' width='25px'>") ?>
            </div>
        </footer>

        <div id="notidetail" style=" display:none;" class="navbar">

        </div>
    </body>
</html>
