<!--
 @author Su Zin Kyaw
 @since  2015/11 /06-->
<?php

use Phalcon\Tag as Tag; ?>
<script type="text/javascript">
    function checkValue() {
        var linkemail = document.forms["theForm"]["linkemail"].checked
        if (linkemail) {
            document.getElementById('xtraInfo').style.display = '';
        } else {
            document.getElementById('xtraInfo').style.display = 'none';
        }
    }
</script>

<?php
foreach ($this->session->auth as $key_name => $key_value) {
    if ($key_name == 'admin_dashboard') {
        $this->view->disable();
        $this->response->redirect('dashboard/index/admin');
    }
}
?>

<!-- Main content -->
<section class="content" style="height: 580px;">
    <div class="row">
        <div class="col-md-12"><!--start add user form--->
            <div class="top-row"><a href="../../attendancelist/user/attendancelist" ><?php echo Tag::image(array('../../common/img/user_male_delete3.png', 'width' => 27)) ?> <font style="color:blue;"><?= $t->_("attendance"); ?> : </font><?php echo $numatt; ?></a></div>
            <div class="top-row"><a href="../../leavedays/user/leavelist" ><?php echo Tag::image(array('common/img/leave.jpg', 'width' => 30)) ?> <font style="color:red;"><?= $t->_("leaveday"); ?> : <?php echo $numleaves; ?> </font></a></div>
            <div id="form_div">

                <div class="left-div-style-box" style="background-color: white; height:450px ; border: 1px solid #ccc; font-size: 20px;">


                    <div class="col-md-7 col-md-offset-3">
                        <h1 style="font-size: 184%"><?= $t->_("current_time"); ?> : <span id='ct' style="color:red;" ></h1>
                    </div><br><br>
                    <div class="col-md-8 col-md-offset-3">
                        <form id="theForm" name="theForm" method="post" action="">
                            <input type="checkbox" name="linkemail" value="y" onClick="return checkValue(this)" /><?= $t->_("late_reason"); ?>
                            <div id="xtraInfo" style="display:none;">
                                <textarea class="textarea" id="note" placeholder="Write your reason here" style="width: 56%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                            </div>
                        </form>

                    </div><br><br>
                    <div class="col-md-6 col-md-offset-4">
                        <a href="#"  class="btn btn-primary btn-sm btn-flat checkin" id="" style="width: 150px;"><?= $t->_("checkin"); ?> </a>
                    </div><br><br>
                    <div class="col-md-6 col-md-offset-4">
                        <a href="#"  class="btn btn-primary btn-sm btn-flat checkout" id="checkout" style="width: 150px;"><?= $t->_("checkout"); ?> </a>
                    </div><br><br></form>
                </div>

            </div>
        </div><!--end add user form--->
    </div><!-- /.row -->

</section><!-- /.content -->
