<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
        <?php $this->assets->outputCss() ?>
    </head>
    <body>
        <div id="slidemenu-left">
            <div class="slidemenu-left-content">
                <div>
                    // サーチホームや
                </div>
                <nav>
                    // ナビゲーションや
                </nav>
            </div>
        </div>
        <?php echo $this->getContent(); ?>
        <?php $this->assets->outputJs();?>
    </body>
</html>