<script type="text/javascript">
         function checkValue() {
  var linkemail=document.forms["theForm"]["linkemail"].checked
  if (linkemail) {
    document.getElementById('xtraInfo').style.display='';
  } else {
    document.getElementById('xtraInfo').style.display='none';
  } 
} 

</script>

<div class="" style="height:auto;margin-top: 40px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Dashboard
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">

        </div><!-- /.row -->

        <div class="row">
            <div class="col-md-12">
		  <div class="top_row"><a href="<?= $baseUri ?>attendancelist/index/todaylist"><img src="../../common/img/Check-32.png" class="imgstyle"><font style="color:red;"><?= $attname ?> </font> Staffs Attended</a></div>
		  <div class="top_row"><a href="<?= $baseUri ?>attendancelist/absent/absentlist"><img src="../../common/img/absence.png" class="imgstyle"><font style="color:red;"><?= $absent ?></font> Staffs Absent<a></div>
                            </div>
                            <div class="col-md-12">
                                <div style="height:30px"></div>
                                <!-- Small boxes (Stat box) -->
                                <div class="row">
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
              <div class="small-box bg-aqua" onclick="window.location.href='../../manageuser/index/userlist'" id="pointer_style1">
                  <img src="../../common/img/User-128.png">
                                            <span class="forsize"> Manage User</span>
                                        </div>
                                    </div><!-- ./col -->
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
              <div class="small-box bg-green" onclick="window.location.href='../../attendancelist/index/todaylist'" id="pointer_style2">
                <img src="../../common/img/View-List-128.png" ">
                                        <span class="forsize"> Attendance List</span>
                                        </div>
                                    </div><!-- ./col -->
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
              <div class="small-box bg-yellow" onclick="window.location.href='../../leavedays/index/leavelist'" id="pointer_style3">
                <img src="../../common/img/Calendar-Date-02-128.png">
                                           <span class="forsize">  Leave Days</span>
                                        </div>
                                    </div><!-- ./col -->
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
              <div class="small-box bg-red" onclick="window.location.href='../../salary/index/salarylist'" id="pointer_style3">
                <img src="../../common/img/Dollar-128.png">
                                           <span class="forsize">  Salary</span>
                                        </div>
                                    </div><!-- ./col -->
                                </div><!-- /.row -->

                            </div><!-- /.col -->
                            </div><!-- /.row -->
                            <div style="height:30px;"></div>
                            <!-- Main row -->
                            <div class="row">
                                <!-- Left col -->
                                <div class="col-md-8">
                                    <!-- MAP & BOX PANE -->
                                    <div class="box box-success">
                                        <div class="box-header with-border">
                                            <h3 class="box-title">Check in / out</h3>
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>

                                            </div>
                                        </div><!-- /.box-header -->
                                        <div class="box-body no-padding">
                                            <div class="row">
                                                <div class="col-md-12 col-sm-5">
                                                    <div id="form_div">

                                                        <div class="left_div_style_box" style="background-color: white; height:450px ; border: 1px solid #ccc; font-size: 20px;">


                                                            <div class="col-md-7 col-md-offset-3">
                                                                <h1 style="font-size:150%">Current Time : <span id="ct" style="color:red;" ></span> </h1>
                                                            </div><br><br>
                                                            <div class="col-md-8 col-md-offset-3">
                                                                <form id="theForm" name="theForm" method="post" action="">
                                                                    <input type="checkbox" name="linkemail" value="y" onClick="return checkValue(this)"/> If You late,Check Here and write your reason.
                                                                    <div id="xtraInfo" style="display:none;">
                                                                        <textarea class="textarea" id="note" placeholder="Write your reason here" style="width: 56%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                                                    </div>
                                                                </form>

                                                            </div><br><br>
                                                            <div class="col-md-6 col-md-offset-4">
                                                                <a href="checkin"  class="btn btn-primary btn-sm btn-flat" id="" style="width: 150px;">Check In </a>
                                                            </div><br><br>
                                                            <div class="col-md-6 col-md-offset-4">
                                                                <a href="checkout"  class="btn btn-primary btn-sm btn-flat" id="checkout" style="width: 150px;">Check Out </a>
                                                            </div><br><br>
                                                        </div>

                                                    </div>
                                                </div><!-- /.col -->

                                            </div><!-- /.row -->

                                        </div><!-- /.box-body -->

                                    </div><!-- /.box -->

                                </div><!-- /.col -->

                                <div class="col-md-4">


                                    <div class="box box-default">
                                        <div class="box-header with-border">
                                            <h3 class="box-title">Latest News</h3>
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>

                                            </div>
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-md-8">
                                                    <div class="chart-responsive">
                                                        <ul class="nav nav-pills nav-stacked" style="border-bottom:1px solid gray; width:100%;">
                                                            <li>
                                                                People who attend no leave
                                                                <ul><?php foreach ($nlname as $na){ ?>
                                                                    <li><?= $na['member_login_name'] ?></li>
                                                                    <?php } ?>
                                                                </ul>
                                                            </li>
                                                        </ul>
                                                        <ul class="nav nav-pills nav-stacked">
                                                            <li>
                                                                People who take the leave most
                                                                <ul><?php foreach ($lname as $na){ ?>
                                                                    <li><?= $na['member_login_name'] ?></li>
                                                                    <?php } ?>
                                                                </ul>
                                                            </li>
                                                        </ul>
                                                    </div><!-- ./chart-responsive -->
                                                </div><!-- /.col -->

                                            </div><!-- /.row -->
                                        </div><!-- /.box-body -->

                                    </div><!-- /.box -->

                                    <!-- USERS LIST -->
                                    <div class="box box-danger">
                                        <div class="box-header with-border">
                                            <h3 class="box-title">Latest Members</h3>
                                            <div class="box-tools pull-right">
                                                <span class="label label-danger"><?= $newnumber ?> New Members</span>
                                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                            </div>
                                        </div><!-- /.box-header -->
                                        <div class="box-body no-padding">
                                            <ul class="users-list clearfix">
                                                          <?php foreach($name as $v){ ?>
                                                             <li>
                                                                 <!--<img src="../../common/img/.jpg" alt="User Image"/>-->
                                                                 <!--<img src="../../uploads/<?php echo  $v->member_profile;?>" class="user-image" alt="User Image"/>-->
                                                                 <?php
                                                                        if($v->member_profile == null){
                                                                        $img = "profile1.jpg";}
                                                                        else{                                                                            
                                                                                 $img=$v->member_profile;                                                                        
                                                                        }
                                                                  ?>                                                 
                                                                 <img src="../../uploads/<?php echo  $img;?>" style="box-shadow: 2px 3px 2px #428bca;width:200px;height:65px;"  class="user-image" alt="User Image"/>
                                                                 <a class="users-list-name" href="#"><?= $v->member_login_name; ?></a>
                                                                 <span class="users-list-date"><?= $v->created_dt; ?></span>
                                                            </li>                          
                                                          <?php } ?>
                                            </ul><!-- /.users-list -->
                                        </div><!-- /.box-body -->
                                        <div class="box-footer text-center">
                      <a href="../../manageuser/index/userlist" class="uppercase">View All Members</a>
                                        </div><!-- /.box-footer -->
                                    </div><!--/.box -->


                                </div><!-- /.col -->

                            </div><!-- /.row -->

                            </section><!-- /.content -->
                            </div>
