<script type="text/javascript">
    function checkValue() {
        var linkemail = document.forms["theForm"]["linkemail"].checked
        if (linkemail) {
            document.getElementById('xtraInfo').style.display = '';
        } else {
            document.getElementById('xtraInfo').style.display = 'none';
        }
    }
</script>
<?php
 
foreach ($this->session->auth as $key_name => $key_value) {
    if ($key_name == 'user_dashboard') {
        $this->view->disable();
        $this->response->redirect('core/index');
    }
}
?>
<div class="" >
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?= $t->_("dashboard"); ?>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
            <li class="active"><?= $t->_("dashboard"); ?></li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
        </div><!-- /.row -->
        <div class="row">
            <div class="col-md-12">
                <div class="top-row"><a href="<?= $baseUri ?>attendancelist/index/todaylist"><img src="../../common/img/user_male_accept.png" class="imgstyle"><font style="color:green;"><?= $attname ?> </font><?= $t->_("attend"); ?></a></div>
                <div class="top-row"><a href="<?= $baseUri ?>attendancelist/absent/absentlist"><img src="../../common/img/user_male_delete3.png" class="imgstyle"><font style="color:red;"><?= $absent ?></font> <?= $t->_("absent"); ?></a></div>
            </div>
            <div class="col-md-12">
                <div style="height:30px"></div>
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-aqua" onclick="window.location.href = '../../manageuser/index/index'" id="pointer_style1">
                            <img src="../../common/img/User-128.png">
                            <span class="forsize"><?= $t->_("manageuser"); ?></span>
                        </div>
                    </div><!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-green" onclick="window.location.href = '../../attendancelist/index/todaylist'" id="pointer_style2">
                            <img src="../../common/img/View-List-128.png" ">
                            <span class="forsize"><?= $t->_("attendancelist"); ?></span>
                        </div>
                    </div><!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-yellow" onclick="window.location.href = '../../leavedays/index/leavelist'" id="pointer_style3">
                            <img src="../../common/img/Calendar-Date-02-128.png">
                            <span class="forsize"><?= $t->_("leaveday"); ?></span>
                        </div>
                    </div><!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-red" onclick="window.location.href = '../../salary/index/salarylist'" id="pointer_style3">
                            <img src="../../common/img/Dollar-128.png">
                            <span class="forsize"><?= $t->_("salary"); ?></span>
                        </div>
                    </div><!-- ./col -->
                </div><!-- /.row -->

            </div><!-- /.col -->
        </div><!-- /.row -->
        <div style="height:30px;"></div>
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <div class="col-md-8">
                <!-- MAP & BOX PANE -->
                <div class="box box-success">
                    <div class="box-header with-border">
                        
                        <h3 class="box-title"><?= $t->_("checkinout"); ?></h3>
                        <div class="box-tools pull-right">
                           
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                             <div id="loading" class="box-title"> </div>
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body no-padding">
                        <div class="row">
                            <div class="col-md-12 col-sm-5">
                                <div id="form_div">

                                    <div class="left_div_style_box" style="background-color: white; height:450px ; border: 1px solid #ccc; font-size: 20px;">

                                        <div class="col-md-7 col-md-offset-3">
                                            <h1 style="font-size:150%"><?= $t->_("current_time"); ?> : <span id="ct" style="color:red;" ></span> </h1>
                                        </div><br><br>
                                        <div class="col-md-8 col-md-offset-3">
                                            <form id="theForm" name="theForm" method="post" action="">
                                                <input type="checkbox" name="linkemail" value="y" onClick="return checkValue(this)"/><?= $t->_("late_reason"); ?>
                                                <div id="xtraInfo" style="display:none;">
                                                    <textarea class="textarea" id="note" placeholder="<?= $t->_("Write"); ?>" maxlength="60" style="width: 56%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                                </div>
                                            </form>

                                        </div><br><br>
                                        <div class="col-md-6 col-md-offset-4">
                                            <a href="#" class="btn btn-primary btn-sm btn-flat checkin" onclick="//Content.View.apply(this, ['checkin']);" style="width: 150px;border-radius: 5px;"><?= $t->_("checkin"); ?></a>
                                        </div><br><br>
                                        <div class="col-md-6 col-md-offset-4">
                                            <a href="#"  class="btn btn-primary btn-sm btn-flat checkout" id="checkout" style="width: 150px;border-radius: 5px;"><?= $t->_("checkout"); ?></a>
                                        </div><br><br>
                                    </div>

                                </div>
                            </div><!-- /.col -->

                        </div><!-- /.row -->

                    </div><!-- /.box-body -->

                </div><!-- /.box -->

            </div><!-- /.col -->

            <div class="col-md-4">


                <div class="box box-default">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?= $t->_("latest_news"); ?></h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>

                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="chart-responsive">
                                    <ul class="nav nav-pills nav-stacked" style="border-bottom:1px solid gray; width:100%;">
                                        <li>
                                            <?= $t->_("no_leave"); ?>
                                            <ul>
                                                <?php
                                                $noleave = [];
                                                foreach ($nlname as $na) {
                                                    ?>
                                                    <li id="noleaveli">
                                                                      
                                                        <?= $na->member_login_name ?>
                                                    </li>
                                                    <?php
                                                    array_push($noleave, $na->member_login_name);
                                                }
                                                ?>
                                            </ul>
                                            <?php
                                            if (sizeof($noleave) > 2) {
                                                ?>
                                            <a href="../../leavedays/index/noleavelist"  class="btn"  id="noleavelistblock"><?= $t->_("View All"); ?></a>
                                                <?php } else {
                                                    ?>
                                             <hr>
                                            <a href="../../leavedays/index/noleavelist"  class="btn"  id="noleavelistnone"><?= $t->_("View All"); ?></a>
                                                    <?php
                                                }
                                                ?>
                                           
                                        </li>
                                    </ul>
                                    <ul class="nav nav-pills nav-stacked">
                                        <li>
                                            <?= $t->_("leave_most"); ?>
                                            <ul><?php
                                                $count = [];
                                                foreach ($lname as $na) {
                                                    ?>
                                                    <li id="noleaveli">
                                                        <?= $na['member_login_name'] ?>
                                                    </li>
                                                    <?php
                                                    array_push($count, $na['member_login_name']);
                                                }
                                                ?>
                                            </ul>
                                            <?php
                                            if (sizeof($count) > 2) {
                                                ?>
                                            <a href="../../leavedays/index/leavemost"  class="btn"  id="leavemostlistblock"><?= $t->_("View All"); ?></a>
                                                <?php } else {
                                                    ?>
                                               <hr>
                                            <a href="../../leavedays/index/leavemost"  class="btn"  id="leavemostlistnone"><?= $t->_("View All"); ?></a>
                                                    <?php
                                                }
                                                ?>
                                            
                                        </li>
                                    </ul>
                                </div><!-- ./chart-responsive -->
                            </div><!-- /.col -->

                        </div><!-- /.row -->
                    </div><!-- /.box-body -->

                </div><!-- /.box -->

                <!-- USERS LIST -->
                <!--/.box -->


            </div><!-- /.col -->

        </div><!-- /.row -->

    </section><!-- /.content -->
</div>
