
 <!--
  @author Su Zin Kyaw
  @since  2015/11 /06-->
<?php use Phalcon\Tag as Tag;?>

<script type="text/javascript">
         function checkValue() {
  var linkemail=document.forms["theForm"]["linkemail"].checked
  if (linkemail) {
    document.getElementById('xtraInfo').style.display='';
  } else {
    document.getElementById('xtraInfo').style.display='none';
  } 
} 

</script>
<!-- Main content -->
<section class="content">
<div>
    <div class="top_row"><a href="../../attendancelist/user/attendancelist" ><?php echo Tag::image(array('common/img/att.jpg', 'width' => 27)) ?><font style="color:red;"><b> Attendance : </font><?php echo $numatt;?></b></a></div>
    <div class="top_row"><a href="../../leavedays/user/leavelist" ><?php echo Tag::image(array('common/img/leave.jpg', 'width' => 30)) ?><font style="color:red;"><b> Leave Days : </font><?php echo $numleaves;?></b></a></div>
</div>
    <div class="row">
        <div class="col-md-12"><!--start add user form--->
            <div id="form_div">
               
                <div class="left_div_style_box" style="background-color: white; height:450px ; border: 1px solid #ccc; font-size: 20px;">
                    

                   <div class="col-md-7 col-md-offset-3">
          <h1 style="font-size: 184%"><b>Current Time : <span id='ct' style="color:red;" ></b></h1>
        </div><br><br>
        <div class="col-md-8 col-md-offset-3">
            <form id="theForm" name="theForm" method="post" action="">
             <input type="checkbox" name="linkemail" value="y" onClick="return checkValue(this)" /> <b>If You late,Check Here</b> and write your reason.
              <div id="xtraInfo" style="display:none;">
                <textarea class="textarea" id="note" placeholder="Write your reason here" style="width: 56%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
             </div>
            </form>
            
        </div><br><br>
        <div class="col-md-6 col-md-offset-4">
          <a href="checkin"  class="btn btn-primary btn-sm btn-flat" id="" style="width: 150px;"><b>Check In</b> </a>
        </div><br><br>
        <div class="col-md-6 col-md-offset-4">
            <a href="checkout"  class="btn btn-primary btn-sm btn-flat" id="checkout" style="width: 150px;"><b>Check Out</b> </a>
        </div><br><br></form>
                </div>

            </div>
        </div><!--end add user form--->
    </div><!-- /.row -->

</section><!-- /.content -->
