
        <section class="content-header">
          <h1>
            Add user
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">add user</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
         
         <div class="row">
	 <div class="col-md-12"><!--start add user form--->
         <?php $this->flashSession->output() ?>
	<div id="form_div">
	<div style="height:30px; background-color:#428bca; padding:5px 0 5px 15px;"><font color="#fffff">Add user form</font></div>
        
        <form action="../coremember/saveuser" method="post" width="650px" height="300px" style="padding:5px 0 5px 15px;" enctype="multipart/form-data"> 
	<table width="650px" height="300px">
            <tr>
                <td rowspan="15"><img src="../../common/img/profile.png" > </td>
                <td rowspan="15"> <input type="file" name="fileToUpload" id="fileToUpload"></td>
            </tr>
	<tr>
            
            <td >User Name :</td>
           
		<td>
		<input type="text" name="member[username]" value="">
		</td>
        </tr>
        <tr>
		
		<td>Password :</td>
                <td><input type="password" name="member[password]" value=""></td>
	</tr>
        
	<tr>
		<td>Department:</td>
		<td><input type="text" name="member[dept]" value=""></td>
        </tr>
        <tr>
          
		<td>Position	:</td>
		<td><input type="text" name="member[position]" value=""></td>
	</tr>
	<tr>
		<td>Email :</td>
		<td><input type="email" name="member[email]" value="">
               </td>
	</tr>
        <tr>
		<td>Phone no</td>
		<td><input type="text" name= "member[phno]" value=""></td>
	</tr>
       
	<tr>
		<td>Address :</td>
		<td colspan="4"><textarea rows="5" name="member[address]" cols="50"></textarea></td>
	</tr>
        <tr>
		<td>User Role :</td>
		<td colspan="4"><select class="select" data-toggle="select" name="member[user_role]" id="member[user_role]" style="margin-top: 13px;">
            
                               <option value="ADMIN,adminstrator">          
                Admin</option>
                                <option value="USER,user">          
                User</option>
                                
                
        </select></td>
	</tr>
	<tr>
		<td></td>
		
                <td><input type="submit" class="buttonn" style="margin: 13px;"  value="Add  New User"></td>
		<td></td>
	</tr>
	</table>
	
</form>
			</div>
          </div><!--end add user form--->
          </div><!-- /.row -->
		  
        </section><!-- /.content -->
    