
        <section class="content-header">
          <h1>
            Add User
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Add User</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
         
         <div class="row">
	 <div class="col-md-12"><!--start add user form--->
         <?php $this->flashSession->output() ?>
	<div id="form_div">
	<div style="height:30px; background-color:#3c8dbc; padding:5px 0 5px 15px;"><font color="#fffff">Add User Form</font></div>
        
        <form id="saveuser" method="post" width="650px" height="300px" style="padding:5px 0 5px 15px;" enctype="multipart/form-data"> 
	<table width="700px" height="300px">
           
                          
            <tr>
                
                <td rowspan="10">
                    <img src="../../uploads/profile.png"  style="box-shadow: 2px 3px 2px #428bca;" class="img-circle" class="user-image" width="200px" alt="User Image"/>
                    <input style="margin-top:10px" type="file" name="fileToUpload" id="fileToUpload">
                </td>
            </tr>
	<tr>

            <td width="150px">User Name </td>

           
            <td style="height:40px;">
                <input style="margin-top:10px;" type="text" name="username" id="uname" placeholder="Write User Name">
                    <span id="user-error"></span>
		</td>                
        </tr>        
        <tr>
		
		<td>Password </td>
                <td style="height:40px;">
                    <input style="margin-top:10px;" type="password" name="password" id="pass" placeholder="Write Password">
                    <span id="pass-error"></span>
                </td>                
	</tr>
        
	<tr>
		<td>Department </td>
                <td style="height:40px;">
                    <input style="margin-top:10px;" type="text" name="dept" id="dept" placeholder="Write Department">
                    <span id="dept-error"></span>                
                </td>
                
        </tr>
        <tr>
          
		<td>Position </td>
                <td style="height:40px;">
                    <input style="margin-top:10px;" type="text" name="position" id="pos" placeholder="Write Position">
                    <span id="pos-error"></span>
                </td>
	</tr>
	<tr>
		<td>Email </td>
                <td style="height:40px;">
                    <input style="margin-top:10px;" type="email" name="email" id="mail" placeholder="Write Email">
                    <span id="mail-error"></span>
               </td>
	</tr>
        <tr>
		<td>Phone Number </td>
                <td style="height:40px;">
                    <input style="margin-top:10px;" type="text" name="phno" id="pno" placeholder="Write Phone Number">
                    <span id="pno-error"></span>
                </td>
	</tr>
       
	<tr>
		<td>Address </td>
                <td colspan="4"><textarea rows="5" name="address" cols="50" placeholder="Write Address"></textarea></td>
	</tr>
        <tr>
		<td><br>User Role </td>
		<td colspan="4"><select class="select" data-toggle="select" name="user_role" id="member[user_role]" style="margin-top: 13px;">
            
                               <option value="ADMIN,adminstrator">          
                Admin</option>
                                <option value="USER,user">          
                User</option>
                                
                
        </select></td>
	</tr>
	<tr>
		<td></td>
		
                <td><input type="submit" onclick="return false;" class="buttonn submit_useradd" style="margin-top:10px;"  value="Add User"><input style="margin-top:10px;" type="reset" class="buttonn" value="Cancel"></td>
		<td></td>
	</tr>
	</table>
	
</form>
			</div>
          </div><!--end add user form--->
          </div><!-- /.row -->
		  
        </section><!-- /.content -->
    
