<?php
    use Phalcon\Filter;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?= $t->_("userlist"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
        <li class="active"><?= $t->_("userlist"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">	
        <form class="buttons">
            <input  type="text" class="userauto form-control-static" name="username" data-autocomplete-limit="10" id="username" placeholder="<?= $t->_("searchusername"); ?>" autocomplete="off">

            <input type="submit" onclick="return false;" class="buttonn form-control-static" value="<?= $t->_("search"); ?>" id="userlistsearch" style="margin-top: -10px;">
             
               
            <a href="#" onclick="return false;"  class="right button displaypopup form-control-static" id="addinguser"><?= $t->_("adduser"); ?></a>              
     
        </form>

    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            
            <table class="listtbl mguser">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th><?= $t->_("name"); ?></th>
                        <th><?= $t->_("dept"); ?></th>
                        <th ><?= $t->_("position"); ?></th>
                        <th ><?= $t->_("mail"); ?></th>
                        <th ><?= $t->_("phone"); ?></th>
                        <th ><?= $t->_("address"); ?></th>                        
                    </tr>

                </thead>
                <tbody>                  
                       <?php 
                       $filter = new Filter();
                    $i=1;
                    foreach ($Result as $result) {                                                
                    ?>                       
                    <tr>
                        <td><?= $i ?></td>
                        <td><?= $filter->sanitize($result->member_login_name, "string"); ?></td>
                        <td><?= $filter->sanitize($result->member_dept_name, "string"); ?></td>
                        <td><?= $filter->sanitize($result->position, "string"); ?></td>
                        <td><?= $filter->sanitize($result->member_mail, "email"); ?></td>
                        <td><?= $filter->sanitize($result->member_mobile_tel, "int"); ?></td>
                        <td><?= $filter->sanitize($result->member_address, "string"); ?>
<!--                        <a href="#" onclick="return false;" style="float:right;margin-top: 5px;" class="button displaypopup" id="<?=$result->member_login_name; ?>">Edit</a>-->
                             <a href="#" onclick="return false;" style="float:right;margin-top: 12px;" class="inedit displaypopup" id="<?=$result->member_id; ?>"></a>
                        </td>
                    </tr>
                   <?php
                    $i++;
                    }
                    ?>
                </tbody>
                <tfoot style="display:none;"></tfoot>                    
            </table>
    </div>
</section>
<div id="content"></div>
<div id="edituser" class="navbar">    
</div>	
<div id="confirm" title="Confirm Delete">
    
</div>





