<?php
if (!ini_get('date.timezone')) {
    date_default_timezone_set('UTC');
}

use Phalcon\Filter;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?= $t->_("userlist"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
        <li class="active"><?= $t->_("userlist"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content" >
    <div class="row">	
        <form class="buttons">
            <input  type="text" class="userauto form-control-static col-sm-6" name="username" data-autocomplete-limit="10" id="username" placeholder="<?= $t->_("searchusername"); ?>" autocomplete="off">
            <input type="submit" onclick="return false;" class="buttonn form-control-static col-sm-3" value="<?= $t->_("search"); ?>" id="userlistsearch">
            <input type="submit" onclick="return false;" class="buttonn displaypopup col-sm-3 form-control-static" value="<?= $t->_("adduser"); ?>" id="addinguser" >     
        </form>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl mguser"  style="margin-top:-30px;">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th><?= $t->_("name"); ?></th>
                        <th><?= $t->_("dept"); ?></th>
                        <th ><?= $t->_("position"); ?></th>
                        <th ><?= $t->_("mail"); ?></th>
                        <th ><?= $t->_("phone"); ?></th>
                        <th ><?= $t->_("address"); ?></th>   
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $filter = new Filter();
                    $i = 1;
                    foreach ($Result->items as $result) {
                        $t = ($Result->current) - 1;
                        ?>                       
                        <tr>
                            <td><?= $i + ($Result->limit * $t) ?></td>
                            <td><?= $filter->sanitize($result->member_login_name, "string"); ?></td>
                            <td><?= $filter->sanitize($result->member_dept_name, "string"); ?></td>
                            <td><?= $filter->sanitize($result->position, "string"); ?></td>
                            <td><?= $filter->sanitize($result->member_mail, "email"); ?></td>
                            <td><?= $filter->sanitize($result->member_mobile_tel, "int"); ?></td>
                            <td><?= $filter->sanitize($result->member_address, "string"); ?>
                                <a href="#" onclick="return false;" style="float:right;margin-top: 12px;" class="inedit displaypopup" id="<?= $result->member_id; ?>"></a>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody>                            
            </table>
        </div>
    </div>
    <div id="content">
        <ul class="pagination" style="margin-left:15px;">
            <?php
            if ($Result->last != 1 && $Result->last != 0) {
                ?>
                <li><a href="index">First</a></li>
                <li><a href="index?page=<?= $Result->before; ?>">Previous</a></li>
                <li><a href="index?page=<?= $Result->next; ?>">Next</a></li>
                <li><a href="index?page=<?= $Result->last; ?>">Last</a></li>
                <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $Result->current, " of ", $Result->total_pages; ?></span></li>
                <?php
            }
            ?>
        </ul>
    </div>
    <div id="edituser" class="navbar">    
    </div>	
    <div id="confirm" title="Confirm Delete">   
    </div>
</section>






