<?php
    use Phalcon\Filter;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        User Lists
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">User Lists</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <!--<a href="#" class="button add-big">Add User</a>-->	
        <form>
        <select class="select" data-toggle="select" name="username" id="username">
            <option>Name</option>
               <?php
                foreach ($username as $name){
                ?>
                <option value="<?php echo $name->member_login_name; ?>" >          
                <?php echo $name->member_login_name; ?></option>
                <?php
                }
                ?>

        </select>
            <input type="submit" onclick="return false;" class="buttonn" value="Search" id="userlistsearch">
        </form>

    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="50px">ID</th>
                        <th width="150px">Name</th>
                        <th width="150px">Department</th>
                        <th width="150px">Position</th>
                        <th width="150px">Email</th>
                        <th width="150px">Phone no</th>
                        <th width="150px">Address</th>                        
                    </tr>

                </thead>
                <tbody>                  
                       <?php 
                       $filter = new Filter();
                    $i=1;
                    foreach ($Result as $result) {                                                
                    ?>                       
                    <tr>
                        <td><?= $i ?></td>
                        <td><?= $filter->sanitize($result->member_login_name, "string"); ?></td>
                        <td><?= $filter->sanitize($result->member_dept_name, "string"); ?></td>
                        <td><?= $filter->sanitize($result->position, "string"); ?></td>
                        <td><?= $filter->sanitize($result->member_mail, "email"); ?></td>
                        <td><?= $filter->sanitize($result->member_mobile_tel, "int"); ?></td>
                        <td><?= $filter->sanitize($result->member_address, "string"); ?>
                        <a href="#" onclick="return false;" style="float:right;margin-top: 5px;" class="button displaypopup" id="<?=$result->member_login_name; ?>">Edit</a>
                        </td>                        
                    </tr>
                   <?php
                    $i++;
                    }
                    ?>
                </tbody>
                <tfoot style="display:none;"></tfoot>                    
            </table>
    </div>
</section>   
<div id="content"></div>
<div id="edituser" class="navbar">    
</div>	
<div id="confirm" title="Confirm Delete">
    
</div>





