<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        User list
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">user list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <!--<a href="#" class="button add-big">Add User</a>-->	
        <form>
        <select class="select" data-toggle="select" name="username" id="username">
            <option>Name</option>
               <?php
                foreach ($username as $name){
                ?>
                <option value="<?php echo $name['member_login_name']; ?>" >          
                <?php echo $name['member_login_name']; ?></option>
                <?php
                }
                ?>

        </select>
            <input type="submit" class="buttonn" value="Search" id="userlistsearch">
        </form>

    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="80px">ID</th>
                        <th>Name</th>
                        <th>Department</th>
                        <th>Position</th>
                        <th width="250px">Email</th>
                        <th>Phone no</th>
                        <th>Address</th>
                        <th width="50px"></th>
                    </tr>

                </thead>
                <tbody>
                    <?php 
                    $i=0;
                    foreach ($Result->items as $result) {                                                
                    ?>                       
                    <tr>
                        <td><?= $i ?></td>
                        <td><?= $result->member_login_name ?></td>
                        <td><?= $result->member_dept_name ?></td>
                        <td><?= $result->position ?></td>
                        <td><?= $result->member_mail ?></td>
                        <td><?= $result->member_mobile_tel ?></td>
                        <td><?= $result->member_address ?></td>
                        <td><a href="#" onclick="return false;" class="button displaypopup" id="<?=$result->member_login_name ?>">Edit</a></td>
                    </tr>
                   <?php
                    $i++;
                    }
                    ?>
                </tbody>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->
    <ul class="pagination">    
        <li><a href="userlist">First</a></li>
        <li><a href="userlist?page=<?= $Result->before; ?>">Previous</a></li>
        <li><a href="userlist?page=<?= $Result->next; ?>">Next</a></li>
        <li><a href="userlist?page=<?= $Result->last; ?>">Last</a></li>    
<?php echo "You are in page ", $Result->current, " of ", $Result->total_pages; ?>
    </ul>
</section><!-- /.content -->
</div><!-- /.content-wrapper -->

<div id="edituser" style="display:none" class="navbar">
    
</div>	
<div id="confirm" title="Confirm Delete">
    
</div>





