<!DOCTYPE html>

<?php

use Phalcon\Tag as Tag;
$this->partial("partials/header");

?>
 

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">                     

            <?php
            echo $this->getContent();
           $this->assets->outputJs();
            ?>
        </div><!-- /.content-wrapper -->
    
<?php $this->partial("partials/footer"); ?>