<!DOCTYPE html>

<?php use Phalcon\Tag as Tag; ?>

 


<?php 

/* Var Output Place
 * 
 */
//var_dump($moduleIdCall);
//  
// 
// foreach ($module_id_set as $module_name_view){
//            $module_name_view  = $module_name_view['module_id'];
//          
//            var_dump($module_name_view);
//          
//        }
//        exit();
?>
 
<html>
    <head>
        <meta charset="UTF-8">
        <title>Dashboard</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?php $this->assets->outputCss() ?>
    </head>
    <body class="skin-blue sidebar-mini" onload="display_ct()">
          <?php error_reporting(0); ?>                                
        <header class="main-header">
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" id="fixedheader" style="margin-left:0;">   
                    <a><img src="<?php echo $baseUri;?>common/img/menu.png"  style="height: 54px"class="sidebar-toggle" href="#sidepage" role="button">
                             <span class="sr-only">Toggle navigation</span>
                             </a>
                    
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        
                        <ul class="nav navbar-nav"> 
                                <li>
                                    <a href="<?php echo $baseUri?>help/index/searchHelp" target="_blank" class="" title="<?php echo $t->_("Help"); ?>" id="help_icon" style="padding-top: 20px;">
                                               <img src="<?php echo $baseUri?>common/img/help_browser.png">
                                    </a>
                               </li>  
                          <!-- Notifications: style can be found in dropdown.less -->
                              <li class="dropdown notifications-menu" >
                                <a href="#" class="<?php if(count($noti)==0){echo "nonoti";}else{echo "noti";}?>" id="noti" style="padding-top: 20px;">
                                    <img src="<?php echo $baseUri;?>common/img/noti.png">
                                    <span class="label label-warning"><?php if(count($noti)==0){ }else{echo count($noti);}?></span>
                                </a>
                                 
                                      
                                    
                                  <div id="notificationContainer">
                                  <div id="notificationTitle"><?php echo $t->_("Notifications"); ?></div>
<div id="notificationsBody" class="notifications">

</div>
                                  <div id="notificationFooter"><a href="<?php echo $baseUri?>/notification/index/viewall"><span style="color:white"><?php echo $t->_("View All"); ?></span></a></div>
                                </div>
                            </li>
                            <!-- Tasks: style can be found in dropdown.less -->

                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 20px;">
                                   <!-- <img src="../../uploads/<?php echo  $this->session->user['member_profile'];?>" class="user-image" alt="User Image"/>-->
                                    <?php
                                                    if($this->session->user['member_profile']==null){
                                                    $img = "profile1.jpg";}
                                                    else{
                                                        $img=$this->session->user['member_profile'];
                                                                if(file_exists('./uploads/'.$img)){                                                            
                                                                     $img=$img;  
                                                                }else{  
                                                                    $img = "profile1.jpg";    
                                                                }
                                                    }
                                        ?>                                                 
                                        <img src="<?php echo $baseUri;?>uploads/<?php echo  $img;?>"  style="box-shadow: 2px 3px 2px #428bca;width:30px;height:25px;" class="img-circle" class="user-image" width="30px" alt="User Image"/>
                                    <span class="hidden-xs"><?php echo $this->session->user['member_login_name']; ?></span>
                                </a>
                                 
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <!--<img src="../../common/img/profile.png" class="img-circle" alt="User Image" />-->
                                       
                                        <!--<img src="../../uploads/<?php echo  $this->session->user['member_profile'];?>" class="img-circle">-->
                                        <?php
                                                    if($this->session->user['member_profile']==null){
                                                    $img = "profile1.jpg";}
                                                    else{
                                                        $img=$this->session->user['member_profile'];
                                                                if(file_exists('./uploads/'.$img)){                                                            
                                                                     $img=$img;  
                                                                }else{  
                                                                    $img = "profile1.jpg";    
                                                                }
                                                    }
                                        ?>                                                 
                                        <img src="<?php echo $baseUri;?>uploads/<?php echo  $img;?>"  class="img-circle" class="user-image" width="30px" alt="User Image"/>
                                        <p>
                                            <b><?php echo $this->session->user['member_login_name']; ?></b>
                                           <!-- <small><b>Member since Nov. 2012</b></small>-->
                                            <!--<small><b>Member since <?php echo "<i style='color:black'> \" ".$this->session->user['created_dt']." \"</i>";?></b></small>-->
                                            <small><b><?php echo $t->_("Member Since"); ?> </b><?php echo "<b style='color:white;font-size:13px;'>".date("M - Y", strtotime( $this->session->user['created_dt']))."</b>";?></small>
                                        </p>
                                    </li>

                                    <!-- Menu Footer-->
                                       <li class="user-footer">
                                          
                                 <?php 
                                      foreach ($this->session->auth as $key_name => $key_value) {                        
            if($key_name =='admin_dashboard'){
                //Go to user dashboard
                
                ?>
                 <div class="pull-left">
                     <a href="../../setting/index/admin" class="btn btn-default btn-flat" id="setting"><b><?php echo $t->_("Setting"); ?></b></a>
                                        </div>
                <?php
            }
             
                if ($key_name =='user_dashboard')  {
               
                    ?> 
                      <div class="pull-left">
                                                    <a href="../../setting/user" class="btn btn-default btn-flat"  id="setting"><b><?php echo $t->_("Setting"); ?></b></a>
                                                </div>
                <?php 
                         }
                                      
               
                  } 
             
                ?>       
            
        
                                        
                                        <div class="pull-right">
                                            <a href="#" class="btn btn-default btn-flat" id="btn_logout"><b><?php echo $t->_("Sign out"); ?></b></a>

                                        </div>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>                
                </nav>
        </header>
            
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar" id="sidepage" style="display:none;height: auto;">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar" >
                    <!-- Sidebar user panel -->                   

                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <aside>
                    <ul class="sidebar-menu">
                        <li class="header"><b>MAIN NAVIGATION</b></li>
                        <?php  
                       $count=1;
                        foreach ($this->session->auth as $key_name => $key_value) {
                            
                           
                                                                                    $top = explode(" ", $key_value["link0"]);
                                                                                    $top_link = explode(" ", $key_value["link1"]);
                                                                                    if (strpos($key_name, 'user') !== false) {
       
       if ($moduleIdCall == 1)
       {
           
                                                                                         if($key_name != 'show_user_notification' && $key_name != 'show_user_setting'){
                                                                                               if (count($key_value) > 2) {
                                                                                                 if (isset($top_link[1])) {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/user/' . strtolower($top_link[0] . $top_link[1]) . '"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                } else {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/index"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                          }
                                                                                          else{
                                                                                                if (isset($top[1])) {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/user/' . strtolower($top[0] . $top[1]) . '"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                } else {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/index"><img src="../../common/img/list.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                          }
                                                                                         }
        }    
                                                                                    } else {
                                                                                        if($key_name != 'show_admin_notification' && $key_name != 'show_admin_setting'){
                                                                                             if ($moduleIdCall == 1)
       {
                                                                                               if (count($key_value) > 2) {
                                                                                                 if (isset($top_link[1])) {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0] . $top[1]) . '/index/' . strtolower($top_link[0] . $top_link[1]) . '"><img src="../../common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                } else {
                                                                                                    echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index/'.strtolower($top_link[0]).'"><img src="../../common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                               }
                                                                                                else{
                                                                                                 if (isset($top[1])) {
                                                                                                 echo '<li><a href="' . $baseUri . strtolower($top[0].$top[1]) . '/index/index"><img src="../../common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                                else{
                                                                                                echo '<li><a href="' . $baseUri . strtolower($top[0]) . '/index"><img src="../../common/img/list'.$count.'.png" ><span><b>' . $key_value[0] . '</b></span></a></li>';
                                                                                                }
                                                                                        }
                                                                                                 
                                                                                        }
                                                                                        }
                        }
      
                        $count++;
                        }
                        ?>
                    </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper collapse-wrapper" style="height:auto;margin-left:0;">                     
                 
                             <?php
                                                                        echo $this->getContent();
                                                                        $this->assets->outputJs();
                                                        ?>
        </div><!-- /.content-wrapper -->
 <script language="javascript" type="text/javascript">var baseUri = '<?= $baseUri ?>';</script> 
        <footer class="main-footer" style="margin-left:0;">
            <strong>Copyright &copy; 2014-2015 <a href="">Gnext Myanmar</a>.</strong> All rights reserved.
            <div class="language">
                   <?php echo $t->_("Change_Language"); ?> : <?php echo Tag::linkTo("core/index/setLanguage/en", "<img src=' ".$baseUri."common/img/english.png' width='20px'>") ?> &nbsp;&nbsp; <?php echo Tag::linkTo("core/index/setLanguage/ja", "<img src=' ".$baseUri."common/img/japan.jpg' width='25px'>") ?> &nbsp;&nbsp; <?php echo Tag::linkTo("core/index/setLanguage/my", "<img src=' ".$baseUri."common/img/myanmar.jpg' width='25px'>") ?>
            </div>
        </footer>
       
<div id="notidetail" style=" display:none;" class="navbar">
    
</div>


    </body>
</html>
