<?php
if (!ini_get('date.timezone')) {
    date_default_timezone_set('UTC');
}
use Phalcon\Filter;
   $this->filter = new Filter();
   $filter = $this->filter; 
?>

<section class="content-header">
    <h1>
        <?php echo $t->_("month_att_chart") . " Search " ?>
    </h1>
    <br>
    <div> 
        <form action='attchartsearch' method="post" enctype="multipart/form-data">
            
          
            
            <input type='input' class="buttonn form-control-static col-sm-2 date-picker-year " placeholder="Select Date   " name="date-picker-input-year" required="Month and Year">
<!--                  &nbsp;&nbsp;<span class="buttonn form-control-static ">-->
              <?php
         
        ?>
<!--          </span>-->
        &nbsp;&nbsp;
        
         <select  class="buttonn form-control-static col-sm-2" name="date-picker-select" >          
              <option>Select-Dept</option> 
 <?php
            foreach ($core_att as $data_att_dept) {
                
 ?>               
                <option><?=  $data_att_dept->member_dept_name ?></option> 
        
    <?php
            }
     ?>
        </select>
        <input type='submit' id="userlistsearch" value="Search" class="buttonn form-control-static col-sm-1" name="date-picker-btn">
        </form>
    </div> 
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i><?php echo $t->_("home") ?></a></li>
        <li class="active"><?php echo $t->_("month_att_chart"); ?></li>
    </ol>
</section>
    <br>
<section class="content"> 
    <div class="row">
        <div class="col-sm-12 table-responsive"><!--start table content--->
            <table class="listtbl attlist attchart">
                 <thead>
                 
              
                  <th colspan='33' style=" text-align: center;"> Monthly Attendance  By Day  </td>
                 
                </thead>
                <tbody>
                    <tr>
                        <td width='2%'><?php echo "NO."; ?> </td>
                        <td width='13%'><?= $t->_("username"); ?></td>
                        
                        
                
                 
                 <?php
                
                      $search_date_year = $filter->sanitize($this->request->getPost('date-picker-input-year'),'string');
                      $day_count = explode(",", $search_date_year);
                      $month_count =  $day_count[0];
                      $year_count =  $day_count[1];
                       // $month_for_day_count = $search_date_month.'/'.$search_date_year;
                        $number = cal_days_in_month(CAL_GREGORIAN, $month_count, $year_count); // 31
                        
                      
                for ($i = 1; $i <= $number; $i++) {
                    echo "  <td> ". $i ."  </td>";
                }
                ?>      
                       
                        
                    </tr>
                    <?php
                    $no = 1;
      
                   
                    foreach ($data->items as $result) {
                        $day = explode(",", $result['day']);
                        $status = explode(",", $result['status']);
                        $tt = ($data->current - 1);
                        echo "<tr>";
                        echo "<td>" . ($no + ($data->limit * $tt)) . "</td>";
                        echo "<td>" . $result['member_login_name'] . "</td>";
                        for ($i = 1; $i <= $number; $i++) {
                            $j = array();
                            //get under today date
                            if ($i) {
                                foreach ($day as $k => $v) {
                                    if ($i == $v) {
                                        $j[$v + 1] = $v;
                                        $j[$v] = array();
                                        $j[$v][$v] = $status[$k];
                                    }
                                }
                                if (array_key_exists($i, $j)) {
                                    if ($i == $j[$i + 1]) {
                                        $j[$i][$i] == 0 ? $class = 'leave0' : ($j[$i][$i] == 1 ? $class = "leave1" : ($j[$i][$i] == 2 ? $class = "leave2" : $class = "leave3"));
                                        echo "<td class='$class' width='2%'></td>";
                                    }
                                } else {
                                    echo "<td class='unleave' width='2%'></td>";
                                }
                            }
                            //get above today date
                            else {
                                echo "<td class='unleave' width='2%'></td>";
                            }
                        }
                        echo "</tr>";
                        $no++;
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
    <div id="content">
    <ul class="pagination" style="margin-left:15px;">
        <?php
        if ($data->last === 1 || $data->last === 0) {
            
        } else {
            ?>
            <li><a href="attchartsearch">First</a></li>
            <li><a href="attchartsearch?page=<?= $data->before; ?>">Previous</a></li>
            <li><a href="attchartsearch?page=<?= $data->next; ?>">Next</a></li>
            <li><a href="attchartsearch?page=<?= $data->last; ?>">Last</a></li>
            <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $data->current, " of ", $data->total_pages; ?></span></li>
            <?php
        }
        ?>
    </ul>
</div>
    <div class="attchart">
    <div class="col-md-12"><div class="col-sm-1 leave0 btn"></div> <?php echo $t->_("att_person"); ?>  </div>
    <div class="col-md-12"><div class="col-sm-1 leave1 btn"></div> <?php echo $t->_("absent_leave_person"); ?>  </div>
    <div class="col-md-12"><div class="col-sm-1 leave2 btn"></div> <?php echo $t->_("absent_noleave_person"); ?> </div>
    <div class="col-md-12"><div class="col-sm-1 leave3 btn"></div> <?php echo $t->_("half_att_person"); ?> </div>
</div>

</section>

