<?php
if (!ini_get('date.timezone')) {
    date_default_timezone_set('UTC');
}
?>

<section class="content-header">
    <h1>
        <?php echo $t->_("month_att_chart") . " (" . date('Y') . "/" . date('m') . ")" ?>
    </h1>
    <br>
    <div> 
        <form action='attchartsearch' method="post" enctype="multipart/form-data">
        <input type='input' class="buttonn form-control-static col-sm-2 date-picker" placeholder="Select Month" value="Select Month" name="date-picker-input">
        &nbsp;&nbsp;
        <select  class="buttonn form-control-static col-sm-2" name="date-picker-select"><option>Select Dept</option><option>2</option></select>
        <input type='submit' id="userlistsearch" value="Search" class="buttonn form-control-static col-sm-1" name="date-picker-btn">
        </form>
    </div> 
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i><?php echo $t->_("home") ?></a></li>
        <li class="active"><?php echo $t->_("month_att_chart"); ?></li>
    </ol>
</section>
    <br>
    //<?php
//     foreach ($coreid as $search_date_view) {
//         
//        echo $search_date_view->member_id;
//          
//         ?>
      
    //<?php
//         
//     }
    ?>
<section class="content"> 
    <div class="row">
        <div class="col-sm-12 table-responsive"><!--start table content--->
            <table class="listtbl attlist attchart">
                <thead>
                <th><?php echo "NO."; ?></th>
                <th style="width:15%;"><?= $t->_("username"); ?></th>
                <?php
                for ($i = 1; $i <= date('t'); $i++) {
                    echo "<th>Day " . $i . "</th>";
                }
                ?>                    
                </thead>
                <tbody>
                    <?php
                    $no = 1;
                    foreach ($search_date->items as $result) {
                        $day = explode(",", $result['day']);
                        $status = explode(",", $result['status']);
                        $tt = ($search_date->current - 1);
                        echo "<tr>";
                        echo "<td>" . ($no + ($search_date->limit * $tt)) . "</td>";
                        echo "<td>" . $result['member_login_name'] . "</td>";
                        for ($i = 1; $i <= date('t'); $i++) {
                            $j = array();
                            //get under today date
                            if ($i <= date('d')) {
                                foreach ($day as $k => $v) {
                                    if ($i == $v) {
                                        $j[$v + 1] = $v;
                                        $j[$v] = array();
                                        $j[$v][$v] = $status[$k];
                                    }
                                }
                                if (array_key_exists($i, $j)) {
                                    if ($i == $j[$i + 1]) {
                                        $j[$i][$i] == 0 ? $class = 'leave0' : ($j[$i][$i] == 1 ? $class = "leave1" : ($j[$i][$i] == 2 ? $class = "leave2" : $class = "leave3"));
                                        echo "<td class='$class'></td>";
                                    }
                                } else {
                                    echo "<td class='unleave'></td>";
                                }
                            }
                            //get above today date
                            else {
                                echo "<td class='unleave'></td>";
                            }
                        }
                        echo "</tr>";
                        $no++;
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
    <div id="content">
    <ul class="pagination" style="margin-left:15px;">
         
    </ul>
</div>
    <div class="attchart">
    <div class="col-md-12"><div class="col-sm-1 leave0 btn"></div> <?php echo $t->_("att_person"); ?>  </div>
    <div class="col-md-12"><div class="col-sm-1 leave1 btn"></div> <?php echo $t->_("absent_leave_person"); ?>  </div>
    <div class="col-md-12"><div class="col-sm-1 leave2 btn"></div> <?php echo $t->_("absent_noleave_person"); ?> </div>
    <div class="col-md-12"><div class="col-sm-1 leave3 btn"></div> <?php echo $t->_("half_att_person"); ?> </div>
</div>

</section>

