<?php

use Phalcon\Tag as Tag;

$office_start_time = '08:00:00';
$office_end_time = '17:00:00';
$length = count($Month);
//print_r($Getname);
//echo $Name.'aa';
?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Monthly Attendance list
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">attendance list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
<!--        <form action="monthlysearch" method="post">-->
<form action="monthlylist" method="post">
            <select class="select" data-toggle="select" name="year" id="year">
                <option value="">Year</option>
                <?php
                $thisyr = date("Y");
                for ($i = 2012; $i <= $thisyr; $i++) {
                    ?>
                    <option value="<?php echo $i; ?>"
                   <?php echo(isset($Year)&&($Year==$i)?' selected="selected"':'');?>     
                    ><?php echo $i; ?></option>
                    <?php
                }
                ?>

            </select>

                <select class="select" data-toggle="select" name="month" id="month">
                <option value="">Month</option>
                <?php
                for ($i = 1; $i <= $length; $i++) {
                    ?>
                    <option value="<?php
                    if ($i < 10) {
                        echo '0' . $i;
                    }
                    else {
                        echo $i;
                    }
                    ?>"
                     <?php echo(isset($Mth)&&($Mth==$i)?' selected="selected"':'');?>
                    ><?php echo $Month[$i]; ?></option>
                            <?php
                        }
                        ?>

            </select>
                <select class="select" data-toggle="select" name="username" id="username">
                <option value="">Name</option>
                <?php
                //print_r($Getname);
                foreach ($Getname as $getname) {
                    ?>
                <option value="<?php echo $getname['member_login_name']; ?>"
                <?php echo(isset($Name)&&($Name==$getname['member_login_name'])?' selected="selected"':'');?>
                ><?php echo $getname['member_login_name']; ?></option>
                    <?php
                }
                ?>
            </select>
            <!-- <a href="../search/search" class="button" id='btn_search'>Search</a> -->
            <input type="submit" value="Search" class="button" id="sub">
            <input type="hidden" value='' id='hidden-type' name='ExportType'/>
<!--            <a href="../export" class="button export" id="btn_export">Export</a>-->
<input type="submit" value="Export" class="button" id="ExportType">
        </form>
    </div>

    <div class="row">
        <?php //$this->partial('attendance/showlist'); ?>
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px">Date</th>
                        
                        <th width="150px">User Name</th>
                        <th width="150px">Check In</th>
                        <th width="150px">Late</th>
                        <th width="150px">Check Out</th>
                        <th width="150px">Working Time</th>
                        <th width="150px">OverTime</th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                    //print_r($showlist);
                    //***************Show monthly attendance list******************************
                    foreach ($showlist as $result)
                    {
                                    ?>
                                    <tr>
                                        <td><?php echo $result['att_date']; ?></td>
                                        <td><?php echo $result['member_login_name']; ?></td>
                                        <td><?php
                                            //echo $showlist[$i][$j]['checkin_time']; 
                                            $ckin_time = explode(" ", $result['checkin_time']);
                                            echo $ckin_time[1];
                                            ?>
                                        </td>
                                        <td>
                                            <?php
                                            //calculate late time
                                            $dt = new DateTime($result['checkin_time']);
                                            $time = $dt->format('H:i:s');
                                            $office_start_time = '08:00:00';
                                            if ($time > $office_start_time) {
                                                $start = strtotime($office_start_time);
                                                $end = strtotime($time);
                                                $late = $end - $start;

                                                echo "<font color='red'>" . gmdate("H:i:s", $late) . "</font>";
                                            }
                                            ?>
                                        </td>
                                        <td>
                                            <?php
                                            $ckout_time = explode(" ", $result['checkout_time']);
                                            echo $ckout_time[1];
                                            ?>
                                        </td>
                                        <td>
                                            <?php
                                            //calculate working time
                                            $start_time = strtotime($result['checkin_time']);
                                            $end_time = strtotime($result['checkout_time']);
                                            if ($end_time == 0) {
                                                echo "-";
                                            } else {
                                                $workingHour = $end_time - $start_time;
                                                $hours = floor($workingHour / 3600);
                                                $minutes = floor(($workingHour / 60) % 60);
                                                $seconds = $workingHour % 60;
                                                echo "$hours:$minutes:$seconds";
                                            }
                                            ?>
                                        </td>
                                        <td>
                                            <?php
                                            //calculate overtime
                                            $workingHour = $end_time - $start_time;
                                            if ($workingHour > 28800) {
                                                $workingHour = $workingHour - 28800;
                                                echo gmdate("H:i:s", $workingHour);
                                            } else {
                                                echo "-";
                                            }
                                            ?>
                                        </td>

                                    </tr>
                                    <?php
                                }
                      
                  
                    ?>


                </tbody>
            </table>      
        </div><!--end table content--->
        <div id="test"></div>
    </div><!-- /.row -->

</section>
