<?php

    //calculate the user time offset
    if ($offset<0){
    $sign='-';
    $value=$offset*(-1);
  
  }
    else{
    $value=$offset*(-1);
} 


$length = count($Month);
//print_r($Getname);
//echo $Name.'aa';
?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Monthly Attendance list
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">attendance list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
<!--        <form action="monthlysearch" method="post">-->
<form onsubmit="return false;" method="post">
            <select class="select" data-toggle="select" name="year" id="year">
                <option value="">Year</option>
                <?php
                $thisyr = date("Y");
                for ($i = 2012; $i <= $thisyr; $i++) {
                    ?>
                    <option value="<?php echo $i; ?>"
                   <?php echo(isset($Year)&&($Year==$i)?' selected="selected"':'');?>     
                    ><?php echo $i; ?></option>
                    <?php
                }
                ?>

            </select>

                <select class="select" data-toggle="select" name="month" id="month">
                <option value="">Month</option>
                <?php
                for ($i = 1; $i <= $length; $i++) {
                    ?>
                    <option value="<?php
                    if ($i < 10) {
                        echo '0' . $i;
                    }
                    else {
                        echo $i;
                    }
                    ?>"
                     <?php echo(isset($Mth)&&($Mth==$i)?' selected="selected"':'');?>
                    ><?php echo $Month[$i]; ?></option>
                            <?php
                        }
                        ?>

            </select>
                <select class="select" data-toggle="select" name="username" id="username">
                <option value="">Name</option>
                <?php
                //print_r($Getname);
                foreach ($Getname as $getname) {
                    ?>
                <option value="<?php echo $getname['member_login_name']; ?>"
                <?php echo(isset($Name)&&($Name==$getname['member_login_name'])?' selected="selected"':'');?>
                ><?php echo $getname['member_login_name']; ?></option>
                    <?php
                }
                ?>
            </select>
            <!-- <a href="../search/search" class="button" id='btn_search'>Search</a> -->
            <input type="submit" value="Search" class="button" id="sub">
            <input type="hidden" value='' id='hidden-type' name='ExportType'/>
            <a href="" class="button export" onclick="Export.Export.apply(this,[$('table.listtbl'),'monthly_list.csv']);">Export</a>
        
        </form>
    </div>

    <div class="row">
        <?php //$this->partial('attendance/showlist'); ?>
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px">Date</th>
                        
                        <th width="150px">User Name</th>
                        <th width="150px">Check In</th>
                        <th width="150px">Late</th>
                        <th width="150px">Check Out</th>
                        <th width="150px">Working Time</th>
                        <th width="150px">OverTime</th>
                        <th width="150px">Place</th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                   
                    //print_r($showlist);
                    //***************Show monthly attendance list******************************
                    foreach ($showlist->items as $item) {
                        ?>
                        <tr>
                            <td><?php echo $item->att_date;?></td>
                          
                            <td><?php echo $item->member_login_name; ?></td>
                            <td><?php $checkintime=$item['checkin_time'];
                               if ($sign=='-'){
                               $time = new DateTime($checkintime);
                           $time->add(new DateInterval('PT' . $value . 'M'));
                           echo $time->format('H:i:s A ');
                           }
                           else{
                            $datetime_from = date(" H:i",strtotime($value." minutes",strtotime($checkintime)));
                               echo $datetime_from;
                           }
     ?>
                            </td>
                            <td>
                                    <?php
                                //calculate late time
                            $checkintime=$item['checkin_time'];
                         $dt = new DateTime($checkintime);
                         $time = $dt->format('H:i:s');
                         $office_start_time='01:30:00 ';
                         if($time>$office_start_time){
                             $start=strtotime($office_start_time);
                             $end=strtotime($time);
                             $late=$end-$start;
        
            echo "<font color='red'>". gmdate("H:i:s",$late)." Hours</font>";
            
        }
        ?>
                            </td>
                            <td>
                         <?php $checkouttime= $item['checkout_time'];
        if($checkouttime==0){
        echo "-";}
        else{
            if($sign='-'){
        $time = new DateTime($checkouttime);
        $time->add(new DateInterval('PT' . $value . 'M'));
        echo  $time->format('H:i:s A');}
        else {
            $datetime_from = date(" H:i",strtotime($value." minutes",strtotime($checkouttime)));
            echo $datetime_from;
        }
        }
?>
                            </td>
                            <td>
                               <?php
                                //calculate working time
                                $start_time = strtotime($item['checkin_time']);
                                $end_time = strtotime($item['checkout_time']);
                                if ($end_time == 0) {
                                    echo "-";
                                } else {
                                    $workingHour = $end_time - $start_time;
                                    $hours = floor($workingHour / 3600);
                                    $minutes = floor(($workingHour / 60) % 60);
                                    $seconds = $workingHour % 60;
                                    echo "$hours:$minutes:$seconds";echo" Hours";
                                   
                                }
                                ?>
                            </td>
                            <td>
                                <?php
                                //calculate overtime
                                $workingHour = $end_time - $start_time;
                                if ($workingHour > 28800) {
                                    $workingHour = $workingHour - 28800;
                                    echo gmdate("H:i:s", $workingHour);
                                } else {
                                    echo "-";
                                }
                                ?>
                            </td>
                            <td><?php
                            echo "Yangon";?>
                            </td>
                        </tr>
                        <?php
                    }
                     ?>


                </tbody>
            </table>      
        </div><!--end table content--->
        <div id="test"></div>
    </div><!-- /.row -->

</section>
<?php
if (isset($_POST['year'])or isset($_POST['month']) or isset($_POST['username'])) {
    $y = $_POST['year'];
    $m = $_POST['month'];
    $n = $_POST['username'];
} 
if (isset($_GET['year'])or isset($_GET['month']) or isset($_GET['username'])){
    $y = $_GET['year'];
    $m = $_GET['month'];
    $n = $_GET['username'];
}
//echo $y.' '.$m.' '.$n.'name';
?>
<a href="monthlylist">First</a>
<a href="monthlylist?page=<?= $showlist->before; ?>&year=<?php echo ((isset($y)) ? $y : ''); ?>&month=<?php echo ((isset($m)) ? $m : ''); ?>&username=<?php echo ((isset($n)) ? $n : ''); ?>">Previous</a>
<a href="monthlylist?page=<?= $showlist->next; ?>&year=<?php echo ((isset($y)) ? $y : ''); ?>&month=<?php echo ((isset($m)) ? $m : ''); ?>&username=<?php echo ((isset($n)) ? $n : ''); ?>">Next</a>
<a href="monthlylist?page=<?= $showlist->last; ?>&year=<?php echo ((isset($y)) ? $y : ''); ?>&month=<?php echo ((isset($m)) ? $m : ''); ?>&username=<?php echo ((isset($n)) ? $n : ''); ?>">Last</a>

<?php echo "You are in page ", $showlist->current, " of ", $showlist->total_pages; ?>
