<?php

use Phalcon\Filter;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?= $t->_("absentlist"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
        <li class="active"><?= $t->_("absentlist"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">


    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="80px"><?= $t->_("no"); ?></th>
                        <th width="150px"><?= $t->_("name"); ?></th>
                        <th width="150px"><?= $t->_("department"); ?></th>
                        <th width="150px"><?= $t->_("position"); ?></th>
                        <th width="150px"><?= $t->_("email"); ?></th>
                        <th width="150px"><?= $t->_("phoneno"); ?></th>
                        <th width="150px"><?= $t->_("address"); ?></th>
                        <th width="30px"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $filter = new Filter();
                    $i = 1;
                    $count = count($Result);
                    if ($count === 0) {
                        ?>
                        <tr>
                            <td colspan="8" ><center>No data to display</center></td>
                    </tr>
                    <?php
                } else {
                    foreach ($Result->items as $result) {
                         $t = ($Result->current)-1;
                        ?>                       
                        <tr>
                            <td><?= $i +($Result->limit*$t) ?></td>
                            <td><?= $filter->sanitize($result->member_login_name, "string"); ?></td>
                            <td><?= $filter->sanitize($result->member_dept_name, "string"); ?></td>
                            <td><?= $filter->sanitize($result->position, "string"); ?></td>
                            <td><?= $filter->sanitize($result->member_mail, "email"); ?></td>
                            <td><?= $filter->sanitize($result->member_mobile_tel, "int"); ?></td>
                            <td><?= $filter->sanitize($result->member_address, "string"); ?>
                            </td>
                            <td>
                                <a href="#" onclick="return false;"  style="float:right;margin-top:5px;" class="absentcheck" title="Absent" id="<?php echo $result->member_id ?>" ></a>
                            </td>   
                        </tr>
                        <?php
                        $i++;
                    }
                }
                ?>
                </tbody>                
            </table>
        </div>
        <div id="content">
    <ul class="pagination" style="margin-left:15px;">
        <?php
        if ($Result->last === 1 || $Result->last === 0) {
            
        } else {
            ?>
            <li><a href="absentlist">First</a></li>
            <li><a href="absentlist?page=<?= $Result->before; ?>">Previous</a></li>
            <li><a href="absentlist?page=<?= $Result->next; ?>">Next</a></li>
            <li><a href="absentlist?page=<?= $Result->last; ?>">Last</a></li>
            <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $Result->current, " of ", $Result->total_pages; ?></span></li>
                <?php
            }
            ?>
    </ul>
</div>
</section>   

