<?php

use Phalcon\Filter;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Absent Lists
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Absent Lists</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">


    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="50px">ID</th>
                        <th width="150px">Name</th>
                        <th width="150px">Department</th>
                        <th width="150px">Position</th>
                        <th width="150px">Email</th>
                        <th width="150px">Phone no</th>
                        <th width="150px">Address</th>                        
                    </tr>
                </thead>
                <tbody>                  
                    <?php
                    $filter = new Filter();
                    $i = 1;
                    foreach ($Result as $result) {
                        ?>                       
                        <tr>
                            <td><?= $i ?></td>
                            <td><?= $filter->sanitize($result['member_login_name'], "string"); ?></td>
                            <td><?= $filter->sanitize($result['member_dept_name'], "string"); ?></td>
                            <td><?= $filter->sanitize($result['position'], "string"); ?></td>
                            <td><?= $filter->sanitize($result['member_mail'], "email"); ?></td>
                            <td><?= $filter->sanitize($result['member_mobile_tel'], "int"); ?></td>
                            <td><?= $filter->sanitize($result['member_address'], "string"); ?>
                            </td>                        
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody>
                <tfoot style="display:none;"></tfoot>                    
            </table>
        </div>
</section>   
