<?php

use Phalcon\Filter;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?= $t->_("absentlist"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
        <li class="active"><?= $t->_("absentlist"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">


    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="80px"><?= $t->_("no"); ?></th>
                        <th width="150px"><?= $t->_("name"); ?></th>
                        <th width="150px"><?= $t->_("department"); ?></th>
                        <th width="150px"><?= $t->_("position"); ?></th>
                        <th width="150px"><?= $t->_("email"); ?></th>
                        <th width="150px"><?= $t->_("phoneno"); ?></th>
                        <th width="150px"><?= $t->_("address"); ?></th>
                        <th width="30px"></th>
                    </tr>
                </thead>
                <tbody style="display : none;">
                    <?php
                    $filter = new Filter();
                    $i = 1;
                    $count = count($Result);
                    if ($count === 0) {
                        ?>
                        <tr>
                            <td colspan="8" ><center>No data to display</center></td>
                    </tr>
                    <?php
                } else {
                    foreach ($Result as $result) {
                        ?>                       
                        <tr>
                            <td><?= $i; ?></td>
                            <td><?= $filter->sanitize($result['member_login_name'], "string"); ?></td>
                            <td><?= $filter->sanitize($result['member_dept_name'], "string"); ?></td>
                            <td><?= $filter->sanitize($result['position'], "string"); ?></td>
                            <td><?= $filter->sanitize($result['member_mail'], "email"); ?></td>
                            <td><?= $filter->sanitize($result['member_mobile_tel'], "int"); ?></td>
                            <td><?= $filter->sanitize($result['member_address'], "string"); ?>
                            </td>
                            <td>
                                <a href="#" onclick="return false;"  style="float:right;margin-top:5px;" class="absentcheck" title="Absent" id="<?php echo $result['member_id'] ?>" ></a>
                            </td>   
                        </tr>
                        <?php
                        $i++;
                    }
                }
                ?>
                </tbody>
                <tfoot style="display:none;"></tfoot>                    
            </table>
        </div>
</section>   
<div id="content"></div>
