<?php

use Phalcon\Tag as Tag;

include("calculate_time.php");
$office_start_time = '08:00:00';
$office_end_time = '17:00:00';
?>
<?php  
echo Tag::javascriptInclude('js/jquery.min_one.js');
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Attendance list
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">attendance list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <form id="frm_search" action="searchlist">
        <select class="select" data-toggle="select" name="namelist" id="namelist">
            <option>Name</option>
            <?php
            foreach ($Getname as $result) {
                ?>
                <option><?php echo $result['member_login_name']; ?></option>

                <?php
            }
            ?>


        </select>
        <input type="submit" class="button" value="Search" id="search">
<!--       <a href="#" class="button" id="search">Search</a>-->
        <a href="#" class="button export">Export</a>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px">Date</th>
                        <th width="150px">ID</th>
                        <th width="150px">User Name</th>
                        <th width="150px">Check In</th>
                        <th width="150px">Late</th>
                        <th width="150px">Check Out</th>
                        <th width="150px">Working Time</th>
                        <th width="150px">OverTime</th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                    foreach ($Result as $result) {
                        ?>
                        <tr>
                            <td><?php $date = date('Y-m-d');
                        echo $date; ?></td>
                            <td><?php echo $result['id']; ?></td>
                            <td><?php echo $result['member_login_name']; ?></td>
                            <td>
                                <?php
                                $ckin_time = explode(' ', $result['checkin_time']);
                                echo $ckin_time[1];
                                ?>
                            </td>
                            <td>
                                <?php
                                if($ckin_time>$office_start_time)
                                {
                                    $aa=calculate_time($office_start_time, $ckin_time[1]);
                                    if(isset($aa)){
                                        echo "<span style='color:red'>".$aa."</span>";
                                    }
                                }
                                ?>
                            </td>
                            <td>
                                <?php
                                $ckout_time = explode(' ', $result['checkout_time']);
                                echo $ckout_time[1];
                                ?></td>
                            <td>
                                <?php
                                $working_time=calculate_time($office_start_time, $ckout_time[1]);
                                echo $working_time;
                                ?>
                            </td>
                            <td>
                                <?php
                                
                                if ($ckout_time[1] > $office_end_time) {
                                    $overtime=calculate_time($office_end_time, $ckout_time[1]);
                                    echo $overtime;
                                } else {
                                    echo "_";
                                }
                                ?>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>

                </tbody>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->

<!--</section> /.content 


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#search").click(function(){
        alert("The paragraph was clicked."+document.getElementById("namelist").value);
        $.ajax({
    type:"get",
    url: "<?php echo $this->url->get("attendance/searchlist") ?>",
    data:{cname:document.getElementById("namelist").value},
            })
    
    .done(function(data) {
        alert("AA");
    })
    });
});
</script>-->
