<div id="slidemenu-left" class="mm-menu mm-horizontal mm-ismenu mm-offcanvas">
    <div class="slidemenu-left-content">
        <nav>
            <h2>アプリケーション</h2>
            <ul id="apps_menu_list">
                <?php foreach($menulist as $apps){ ?>
                <li id="apml_<?=$apps['code']?>"><?=$coreAppsTran->_($apps['code'])?></li>
                <?php } ?>
            </ul>
        </nav>
        <div>
            <div id="btn_logout">ログアウト</div>
        </div>
    </div>
</div>