<?php
use Phalcon\Tag as Tag ;
?>
<div id="external-events">
    <!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Calendar
        </h1>            
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">calendar</li>
        </ol>
       
    </section>
</div>
<!-- Main content -->
<section class="content">
    <div class="box box-primary">
        <div class="box-body no-padding">
            <div class="popup-table"></div> 
            <!-- THE CALENDAR -->
            <div id="calendar" class="bg-info" style="width:100%;height:100%;"></div>
        </div><!-- /.box-body -->
        <br><br>
    </div><!-- /. box -->

</section><!-- /.content -->
   
<div id="dialog" style="display:none" title="Edit Event" class="navbar">
    <form id="edit_event" onsubmit="return false;" class="container">
        <label for="title">Title:</label><input type="text" class="box" name="title" id="title_edit_event">
        <span class="err"></span><br><br> 
        <label for="member_name">Name:</label><select class="box input-medium" data-toggle="select" name="uname" id="show_name">
             <option value="" disabled>Name</option>
                <?php
                foreach ($uname as $result) {
                ?>
                    <option><?php echo $result['member_login_name']; ?></option>
                <?php
                }
                ?>
            </select>
        <span></span><br><br>
        <label for="sdate"> Start Date:</label><input type="text" class="box" name="sdate" id="sdate_edit_event">
        <span class="err-sdate"></span><br><br>
        <label for="edate"> End Date:</label><input type="text" class="box" name="edate" id="edate_edit_event"><br>
        <input type="submit" value="Edit" class="edit btn-success" id="submit_edit_event"><input type="submit" value="Delete" class="del btn-danger" id="del_event"><input type="reset" value="cancel" id="close_create_event">
    </form>
</div>
<!--//create dialog event-->
<div id="dialog_create" style="display:none" title="Create Event" class="navbar">
    <form id="create_event" onsubmit="return false;" class="container">
        <label for="title">Title:</label><input type="text" class="box" name="title" id="title_create_event">
        <span class="err"></span><br><br>        
        <label for="member_name">Name:</label><select class="box input-medium" data-toggle="select" name="uname" id="select_name">
             <option value="" disabled>Name</option>
                <?php
                foreach ($uname as $result) {
                ?>
                    <option><?php echo $result['member_login_name']; ?></option>
                <?php
                }
                ?>
            </select>
        <span></span><br><br>
        <label for="sdate"> Start Date:</label><input type="text" class="box" name="sdate" id="sdate_create_event">
        <span class="err-sdate"></span><br><br>
        <label for="edate"> End Date:</label><input type="text" class="box" name="edate" id="edate_create_event">
        <span class="err-edate"></span><br>
        <input type="submit" value="Create" class="btn-facebook" id="create_dialog"><input type="reset" value="cancel" id="reset_create_event">
    </form>
</div>






