<?php

    function checked() {
        if(isset($_POST['chkAllFiles'])) {
            return 'checked="checked" ';
        }
        else
        {
            return '';
        }
    }

?>
<?php
use Phalcon\Tag as Tag;
?>
<div id="external-events">
    <!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Calendar
        </h1>        
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Calendar</li>
        </ol>
    </section>      
<!-- Main content -->
<section class="content">
    <div class="row">
        
        <div class="col-md-2">
            <h2 class="col-sm-12 label label-primary"><span style="line-height: 25px;font-size: 15px;">User Event Enable</span></h2>
        <form action="#" method="post">      
            <span style="margin-left: 80px;"  ><input name="chkAllFiles" type="checkbox" <?php echo checked(); ?> >
                <input style="height: 18px;width:50px;border-radius: 5px;font-weight: 700;color:white;background-color: #3c8dbc;" name="btnGo" type="submit" value="Check" /></span>
        </p>
           <!--<a href="#" onclick="checked()">Select All</a>-->
       
        <ul class="nav nav-pills nav-stacked col-sm-12" id="left-scroll">
         <?php
            foreach ($uname as $result) {
                ?>
            <li class="addbtn"> <input style="margin-top: -2px;margin-left: 10px;" type="checkbox" value="<?= $result->member_login_name; ?>" <?php echo checked(); ?>><?php echo " ".$result->member_login_name; ?></li>
                <?php
            }
            ?>
        </ul>
         </form>
        <span class="btn btn-primary col-sm-12 btn-show-event">Show Event</span>
        <div class="alert col-sm-12">Check above user to see their event</div>
        </div>
    <div class="col-md-10">
        <div class="box-body no-padding">
            <!-- THE CALENDAR -->
            <div id="calendar" class="bg-info"></div>
        </div><!-- /.box-body -->
        <br><br>
    </div><!-- /. box -->
    </div>
</section><!-- /.content -->

<div id="dialog" style="display:none" title="Edit Event" class="navbar">
    <form id="edit_event" onsubmit="return false;" class="container">
        <label for="title">Title</label><input style="font-size: 13px;" type="text" class="box" name="title" id="title_edit_event">
        <span class="err"></span>
        <label for="member_name">Name</label>
        <select style="font-size: 13px;" class="box input-medium" data-toggle="select" name="uname" id="show_name">
            <option value="">Name</option>
            <?php
            foreach ($uname as $result) {
                ?>
                <option><?php echo $result->member_login_name; ?></option>
                <?php
            }
            ?>
        </select>
        <span></span>
        <label for="sdate"> Start Date</label><input style="font-size: 13px;" type="text" class="box" name="sdate" id="sdate_edit_event">
        <span class="err-sdate"></span>
        <label for="edate"> End Date</label><input style="font-size: 13px;" type="text" class="box" name="edate" id="edate_edit_event"><br><br>
        <input type="submit" value="Edit"  id="submit_edit_event"> <input type="submit" value="Delete"  id="del_event"> <input type="reset" value="Cancel" id="close_create_event">
    </form>
</div>
<!--//create dialog event-->
<div id="dialog_create" style="display:none" title="Create Event" class="navbar">
    <form id="create_event" onsubmit="return false;" class="container">
        <table>
            <tr>
                <td> <label for="title">Title</label><input style="font-size: 13px;" type="text" class="box" name="title" id="title_create_event" placeholder="Write Title"></span> </td>
             </tr>
             <tr>
                 <td>
                     <label for="member_name">Name</label><select style="font-size: 13px;" class="box input-medium" data-toggle="select" name="uname" id="select_name">
                         <option value="" disabled selected>Name</option>
                            <?php
                            foreach ($uname as $result) {
                                ?>
                                <option><?php echo $result->member_login_name; ?></option>
                                <?php
                            }
                            ?>
                        </select>
                 </td>
             </tr>
             <tr>
                 <td>
                     <label for="sdate"> Start Date </label><input style="width:250px;font-size: 13px;" type="text" class="box" name="sdate" id="sdate_create_event">
                 </td>
             </tr>
             <tr>
                 <td>
                     <label for="edate"> End Date</label><input style="width:250px;font-size: 13px;" type="text" class="box" name="edate" id="edate_create_event">
                        <span class="err-edate"></span><br><br>
                 </td>
             </tr>
             <tr>
                 <td>
                     <input type="submit" value="Create" class="btn-facebook" id="create_dialog"> <input type="reset" value="Cancel" id="reset_create_event">
                 </td>
             </tr>
        </table>                                                   
                                                            
    </form>
</div>






