<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Attendance System</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?php $this->assets->outputCss() ?>
    </head>
    <body class="sidebar-mini">
        <div class="wrapper">            
            
                <aside class="main-sidebar">                   
                    <!-- sidebar: style can be found in sidebar.less -->
                    
                    <section class="sidebar" style="margin-top:-50px!important; ">
                      <ul class="sidebar-menu">
                        <li class="btn-info">Administrator Menu</li>
                        <li class="treeview"><a href="<?= $baseUri ?>setting/index/settingmodule"><img src=""><span>Setting Module</span></a></li>
                        <li class="treeview"><a href=""><img src=""><span>Setting Order</span></a></li>
                      
                    
                    </ul>
                </section>

                </aside>
               <div class="content-wrapper" >
                    <section class="wrapper">
                        <?php echo $this->getContent() ?>
                        <?php $this->assets->outputJs(); ?>
                    </section>
                </div>
        </div> 
    </body>