<section class="content-header">
    <h1>
        Add Salary For Each Member
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Add Salary</li>
    </ol>
</section>
<?php
if(isset($Msg))
{
    echo "<script>alert($Msg);</script>";
}
?>
<!-- Main content -->
<section class="content">
       <div class="row">
        <div class="col-md-12"><!--start table content--->
            <div id="form_div">
                <div style="height:30px; background-color:#3c8dbc; padding:5px 0 5px 15px;"><font color="#fffff">Add Salary Form</font></div>
                <div class="left_div_style_box">
                    <form action="../salarymaster/savesalary" method="post">
                    <div class="div_bottom">
                        <span class="span_style">UserName </span>
                        <span>
                            <select style="width:34%;" name="uname" id="uname">
                                <option value="">Name</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username->member_id; ?>"
                                    <?php //echo(isset($Uname) && ($Uname == $result['member_login_name']) ? ' selected="selected"' : ''); ?>        
                                            ><?php echo $username->member_login_name; ?></option>

                                    <?php
                                }
                                ?>
                            </select>
                        </span>
                    </div>
                        
                    <div class="div_bottom">
                        <span class="span_style">Position </span>
                        <span>
                            <select style="width:34%;" name="position" id="position">
                                <option value="">Select Position</option>
                                <?php
                                for($i=1;$i<count($position);$i++){
                                ?>
                                <option value="<?php echo $position[$i];?>"><?php echo $position[$i];?></option>
                                <?php
                                }
                                ?>
                                
                                       
                            </select>
                        </span>
                    </div>
                    <div class="div_bottom">
                        <span class="span_style">Basic Salary </span>
                        <span><input type="text" id="bsalary" value="" placeholder="Basic salary" style="width:34%; height: 20%;" name="bsalary"></span>
                    </div>

                    <div class="div_bottom">
                        <span class="span_style">Travel fees </span>
                        <span><input type="text" id="travelfee" value="" placeholder="Travel fees" style="width:34%; height: 20%;" name="travelfee"></span>
                    </div>

                    <div class="div_bottom">
                        <span class="span_style">Overtime ( per hr ) </span>
                        <span><input type="text" id="overtime" value="" style="width:5%;" name="overtime" placeholder="0"></span>
                        <span>%</span>
                    </div>
                        
                    <div class="div_bottom">
                        <span class="span_style">Deduce for SSC </span>
                        <span>
                            <?php
                            //print_r($getall_allowance);
                            foreach ($getall_deduce as $getall_deduces) {
                                echo '<input type="checkbox" name="check_allow[]" value="'.$getall_deduces['deduce_id'].'"> '. $getall_deduces['deduce_name'];
                            }
                            ?>
                            
                        </span>
                        
                    </div>
                    <div style="padding-left: 20px;padding-bottom: 10px;line-height: 30px;">
                        <div style="float: left; width: 8%;">Allowance </div>
                        <div style="margin-left: 11%;">
                            <?php
                            //print_r($getall_allowance);
                            foreach ($getall_allowance as $getall_allowances) {
                                echo '<input type="checkbox" name="check_allow[]" value="'.$getall_allowances['allowance_id'].'"> '. $getall_allowances['allowance_name']."<br>";
                            }
                            ?>
                            
                        </div>
                    </div>
                        <div class="div_bottom" style="clear: both;">
                        <span class="span_style"></span>
                        <span>
<!--                            <a href="#" class="button">Apply</a>-->
                            <input type="submit" value="Apply" class="buttonn">
                            <!--<a href="#" class="button"><b>Cancel</b></a>-->
                            <input type="reset" class="buttonn" value="Cancel">
                        </span>
                    </div>
                </form>
                </div>

            </div>  
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
</section><!-- /.content -->
