<section class="content-header" style="height:auto;">
    <h1>
        <?= $t->_("addsalary_title"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
        <li class="active"><?= $t->_("addsalary_title"); ?></li>
    </ol>
</section>
<?php
if(isset($Msg))
{
    echo "<script>alert($Msg);</script>";
}
?>
<!-- Main content -->
<section class="content">
       <div class="row">
        <div class="col-md-12"><!--start table content--->
            <div id="form_div">
                <div style="height:30px; background-color:#3c8dbc; padding:5px 0 5px 15px;"><font color="#fffff">Add Salary Form</font></div>
                <div class="left-div-style-box">
                    <form action="#" method="post" id="add_salary">
                    <div class="div-bottom">
                        <span class="span-style"><?= $t->_("name"); ?></span>
                        <span>
<!--                            <select style="width:34%;" name="uname" id="uname">
                                <option value="">Name</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username->member_id; ?>"
                                    <?php //echo(isset($Uname) && ($Uname == $result['member_login_name']) ? ' selected="selected"' : ''); ?>        
                                            ><?php echo $username->member_login_name; ?></option>

                                    <?php
                                }
                                ?>
                            </select>
                             <span id="add_salary_uname_error"></span> -->
                            <input type="text" class="salusername" name="uname" id="uname" style="width:34%; height: 20%;" placeholder="<?php echo $t->_("searchusername"); ?>">
                            <span id="add_salary_uname_error"></span>
                            <input type="hidden" value="" id="formemberid" name="member_id">
                        </span>
                       
                    </div>
                        
<!--                    <div class="div-bottom">
                        <span class="span-style">Position </span>
                        <span>
                            <select style="width:34%;" name="position" id="position">
                                <option value="">Select Position</option>
                                <?php
                                for($i=1;$i<count($position);$i++){
                                ?>
                                <option value="<?php echo $position[$i];?>"><?php echo $position[$i];?></option>
                                <?php
                                }
                                ?>
                                
                                       
                            </select>
                        </span>
                    </div>-->
                    <div class="div-bottom">
                        <span class="span-style"><?= $t->_("basic_salary"); ?></span>
                        <span><input type="text" id="bsalary" value="" placeholder="<?php echo $t->_("basic_sal"); ?>" style="width:34%; height: 20%;" name="bsalary"></span>
                         <span id="add_salary_bsalary_error"></span>
                    </div>

                    <div class="div-bottom">
                        <div class="span-style"><?= $t->_("travel_fee_perday"); ?></div>
                        
                        <div style="width:350px; margin-left: 220px">
                            <div style="padding-bottom: 10px;">
                            Choose travel fees type:
                            <input type='radio' name='radTravel' value='1' id="radtravel1"/>Per day
                            <input type='radio' name='radTravel' value='2' id="radtravel2"/>Per month
                            
                            </div> 
                            <div>
                                <input type="text" id="travelfee" value="" placeholder="<?php echo $t->_("travelperday"); ?>" style="width:97%; height: 20%;" name="travelfees" disabled/>
                            </div>
                    </div>
                    <div class="div-bottom">
                        <span class="span-style"><?= $t->_("overtime"); ?></span>
                        <span><input type="text" id="overtime" value="" style="width:34%; height: 20%;" name="overtime" placeholder="<?php echo $t->_("over"); ?>"></span>
                    </div>
                        
                           
                    <div style="padding-left: 20px;padding-bottom: 10px;line-height: 30px;">
                        <div style="float: left; width: 20%;"><?= $t->_("deduce_ssc"); ?></div>
                        <div style="margin-left: 20%;width: 150px;">
                            <?php
                            //print_r($getall_allowance);
                            $i=1;
                            foreach ($getall_deduce as $getall_deduces) {
                                echo '<input type="checkbox" name="checkall[]" onClick="return checkValue(this)" id="checkall'.$i.'" value="'.$getall_deduces['deduce_id'].'"> '.  $getall_deduces['deduce_name']."<br>";
                                $i++;
                                if($i==3){
                                     echo "<div id='No_of_children' style='display:none;'>
                                <input type='text'  name='no_of_children' id='no_of_children' placeholder='number of children'>
                            </div>";
                                }
                               
                            }
                            ?>                            
                        </div>
                        <div id="clear"></div>
                        <div style="margin-left: 40%;float: right;margin-top: -100px;margin-right: 500px; width: 150px;">
                            <span id="add_salary_ssc_error"></span>
                        </div>
                    </div>
                       
                                           
                       

                    <div style="padding-left: 20px;padding-bottom: 10px;line-height: 30px;">
                        <div style="float: left; width: 20%;"><?= $t->_("allowance"); ?></div>
                       <div style="margin-left: 20%;">
                            <?php
                            //print_r($getall_allowance);
                            
                            foreach ($getall_allowance as $getall_allowances) {
                                echo '<input type="checkbox" name="check_allow[]" id="check_allow[]" value="'.$getall_allowances['allowance_id'].'"> '. $getall_allowances['allowance_name']."<br>";
                            }
                            ?>
                           
                        </div>
                    </div>
                        <div class="div-bottom" style="clear: both;">
                        <span class="span-style"></span>
                        <span>
<!--                            <a href="#" class="button">Apply</a>-->
                           <input type="submit" value="<?= $t->_("apply"); ?>" onclick="return false;" id="addsalary" class="buttonn">
                            <!--<a href="#" class="button"><b>Cancel</b></a>-->
                            <input type="reset" id="add_salary_cancel" class="buttonn" value="<?= $t->_("cancel"); ?>">
                        </span>
                    </div>
                </form>
                </div>

            </div>  
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
</section><!-- /.content -->
<script type="text/javascript">
    function checkValue() {
        var linkemail = document.forms["add_salary"]["checkall2"].checked
        if (linkemail) {
            document.getElementById('No_of_children').style.display = '';
        } else {
            document.getElementById('No_of_children').style.display = 'none';
        }
    }
//for checking radio button
document.getElementById('radtravel1').onchange = displayTextBox;
document.getElementById('radtravel2').onchange = displayTextBox;

var textBox = document.getElementById('travelfee');

function displayTextBox(evt){
    if(evt.target.value=="1" || evt.target.value=="2"){
        textBox.disabled = false;
    }else{
        textBox.disabled = true;
    }
}
</script>
