<section class="content-header">
    <h1>
        <b>Add Salary For Each Member</b>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <b>Home</b></a></li>
        <li class="active"><b>Add Salary</b></li>
    </ol>
</section>
<?php
if(isset($Msg))
{
    echo "<script>alert($Msg);</script>";
}
?>
<!-- Main content -->
<section class="content">
       <div class="row">
        <div class="col-md-12"><!--start table content--->
            <div id="form_div">
                <div style="height:30px; background-color:#428bca; padding:5px 0 5px 15px;"><font color="#fffff"><b>Add Salary Form</b></font></div>
                <div class="left_div_style_box">
                    <form action="../salarymaster/savesalary" method="post">
                    <div class="div_bottom">
                        <span class="span_style"><b>UserName :</b></span>
                        <span>
                            <select style="width:34%;" name="uname" id="uname">
                                <option value="">Name</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username->member_id; ?>"
                                    <?php //echo(isset($Uname) && ($Uname == $result['member_login_name']) ? ' selected="selected"' : ''); ?>        
                                            ><?php echo $username->member_login_name; ?></option>

                                    <?php
                                }
                                ?>
                            </select>
                        </span>
                    </div>
                        
                    <div class="div_bottom">
                        <span class="span_style"><b>Position :</b></span>
                        <span>
                            <select style="width:34%;" name="position" id="position">
                                <option value="">select position</option>
                                <?php
                                for($i=1;$i<count($position);$i++){
                                ?>
                                <option value="<?php echo $position[$i];?>"><?php echo $position[$i];?></option>
                                <?php
                                }
                                ?>
                                
                                       
                            </select>
                        </span>
                    </div>
                    <div class="div_bottom">
                        <span class="span_style"><b>Basic Salary :</b></span>
                        <span><input type="text" id="bsalary" value="" placeholder="Basic salary" style="width:34%; height: 20%;" name="bsalary"></span>
                    </div>

                    <div class="div_bottom">
                        <span class="span_style"><b>Travel fees :</b></span>
                        <span><input type="text" id="travelfee" value="" placeholder="Travel fee" style="width:34%; height: 20%;" name="travelfee"></span>
                    </div>

                    <div class="div_bottom">
                        <span class="span_style"><b>Overtime (per hr) :</b></span>
                        <span><input type="text" id="overtime" value="" style="width:5%;" name="overtime" placeholder="0"></span>
                        <span>%</span>
                    </div>
                        
                    <div class="div_bottom">
                        <span class="span_style"><b>Deduce for SSC :</b></span>
                        <span>
                            <b>with_F</b> <input type="checkbox" name="check_list[]" value="stay_father">
                            <b>with_M</b> <input type="checkbox" name="check_list[]" value="stay_mother">
                            <b>spouse</b> <input type="checkbox" name="check_list[]" value="spouse">
                            <b>children</b> <input type="checkbox" name="check_list[]" value="children">
                            <b>life_insurance</b> <input type="checkbox" name="check_list[]" value="life_insurance">
                        </span>
                        
                    </div>
                    <div style="padding-left: 20px;padding-bottom: 10px;line-height: 30px;">
                        <div style="float: left; width: 8%;"><b>Allowance :</b></div>
                        <div style="margin-left: 12%;">
                            <?php
                            //print_r($getall_allowance);
                            foreach ($getall_allowance as $getall_allowances) {
                                echo '<input type="checkbox" name="check_allow[]" value="'.$getall_allowances['allowance_id'].'"><b> '. $getall_allowances['allowance_name']."</b><br>";
                            }
                            ?>
                            
                        </div>
                    </div>
                        <div class="div_bottom" style="clear: both;">
                        <span class="span_style"></span>
                        <span>
<!--                            <a href="#" class="button">Apply</a>-->
                            <input type="submit" value="Apply" class="buttonn">
                            <a href="#" class="button"><b>Cancel</b></a>
                        </span>
                    </div>
                </form>
                </div>

            </div>  
        </div><!--end table content--->
    </div><!-- /.row -->

</section><!-- /.content -->
