<section class="content-header">
    <h1>
        <b>Allowance</b>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <b>Home</b></a></li>
        <li class="active"><b>Allowance</b></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-12"><!--start table content--->
             
            <form id='TextBoxesGroup' action='saveallowance'>
                <div id="TextBoxDiv1">
         
                    <label>Allowance Name 1 : </label> <input type='text' id='textbox1' name='textbox1' >
                    <label>Allowance Amount 1 : </label> <input type='text' id='txt1' name='txt1'>
                    <b><input type='button' value='+' id='addButton'></b>
                    <b><input type='button' value='-' id='removeButton'></b>
                    <b><input type='submit' value='Add' id=''></b>

                </div>
            </form>


            <table class="listtbl">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Allowance Name</th>
                        <th>Allowance Amount</th>
                        <th width="30px"></th>
                    </tr>

                </thead>
                <tbody>
                <?php
                $n=0;
                foreach ($list   as $result) {$n++;
                    ?><tr>
                        <td><?php echo $n; ?></td>
                        <td><?php echo $result['allowance_name'];?></td>
                        <td><?php echo $result['allowance_amount'];?></td>
                        <td><input type="button" class="btn btn-default allpopup" onclick="return false;" id="<?= $result['allowance_id'] ?>" value="Edit"></td>
                      </tr>
                 <?php
                }
                ?>
                </tbody>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->

</section><!-- /.content -->
<div id="edit_all_dia" class="navbar"></div>
<div id="confirm" class="navbar"></div>

<script type="text/javascript">

    $(document).ready(function () {

        var counter = 2;
        var counter1=2;
        $("#addButton").click(function () {

            if (counter > 10) {
                alert("Only 10 textboxes allow");
                return false;
            }
           
            var newTextBoxDiv = $(document.createElement('div'))
                    .attr("id", 'TextBoxDiv' + counter);

            newTextBoxDiv.after().html('<label>Allowance Name ' + counter + ' : </label> ' +
                    ' <input type="text" name="textbox' + counter +
                    '" id="textbox' + counter + '" value="" > <label>Allowance Amount  ' + counter + ' : </label>' +
                    ' <input type="text" name="txt' + counter +
                    '" id="txt' + counter + '" value="" >');

            newTextBoxDiv.appendTo("#TextBoxesGroup");


            counter++;
        });

        $("#removeButton").click(function () {
            if (counter == 2) {
                alert("No more textbox to remove");
                return false;
            }

            counter--;

            $("#TextBoxDiv" + counter).remove();

        });
        
        $("#getButtonValue").click(function () {
            alert(counter);
//window.location.href = baseUri + 'salary/index/saveallowance?count='+counter;
//            var msg = '';
//            for (i = 1; i < counter; i++) {
//                msg += "\n Textbox #" + i + " : " + $('#textbox' + i).val();
//                msg += "\n Textbox #" + i + " : " + $('#txt' + i).val();
//            }
//          
//            alert(msg);
        });

    });
</script>

