<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}

use Phalcon\Filter;
?>
<section class="content-header" style="height:auto;">
    <h1>
        <?= $t->_("monthly_salary_list"); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <?= $t->_("home"); ?></a></li>
        <li class="active"><?= $t->_("monthly_salary_list"); ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <span class="dropdown">
            <h4 class="dropdown-toggle btn btn-primary" data-toggle="dropdown" id="csv_file">Add Salary By CSV file </h4>
            <h4 class="btn btn-primary csv_download" title="Download Sample CSV(we recommend to open in excel)" id="2"><img src="../../common/img/download1.png"></h4>
            <div class="dropdown-menu"  id="radsal_type" style="margin-top: 20px;">
                <form action="#" enctype="multipart/form-data" role="form" id="csvimport" method="POST">
                    <input type="file" name="file" id="file_select" class="col-xs-6 col-xs-offset-0">
                    <button type="submit" onclick="return false;" class="col-xs-3 col-xs-offset-4 btn btn-primary csvtosql" id="2">Add</button>
                    <span id="file_err" class="col-xs-12" style="display:none;"></span>
                </form>
            </div>
        </span>
        <a href="#" class="button add-big" id="displaypopup"><?= $t->_("Calculate salary"); ?></a>
        <a href="#" class="button export" onclick="Export.Export.apply(this, [$('table.listtbl'), 'monthly_salary.csv']);">Export</a>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl salarylist">
                <thead>
                    <tr>
                        <th><center><?= $t->_("mth/yr"); ?></center></th>
                <th><center><?= $t->_("salary"); ?></center></th>
                <th><center><?= $t->_("allowance"); ?></center></th>
                <th><center><?= $t->_("travel_fee"); ?></center></th>
                <th><center><?= $t->_("income"); ?></center></th>
                <th><center>SSC Employer</center></th>
                <th><center>SSC Employee</center></th>
                <th><center><?= $t->_("tax_total"); ?></center></th>
                <th><center><?= $t->_("total"); ?></center></th>
                </tr>

                </thead>
                <tbody>
                    <?php
                    $filter = new Filter();
                    foreach ($geteachmonthsalarys->items as $geteachmonthsalary) {
                        ?>
                        <tr>
                            <td width="50px"><a  href="showsalarylist?month=<?php echo $geteachmonthsalary['Mt'] ?> && year=<?php echo $geteachmonthsalary['Yr'] ?>"><?php echo $geteachmonthsalary['Mt'] . '/' . $geteachmonthsalary['Yr']; ?></a></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['salary_total'], "int")); ?></div></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['allowance'], "int")); ?></div></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['travel_expense'], "int")); ?></div></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['income_tax_amount'], "int")); ?></div></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['ssc_emp_amount'], "int")); ?></div></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['ssc_comp_amount'], "int")); ?></div></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['Tax_total'], "int")); ?></div></td>
                            <td><div class="td-style"><?php echo number_format($filter->sanitize($geteachmonthsalary['Total'], "int")); ?></div></td>
                        </tr>
                        <?php
                    }
                    ?>


                </tbody>
            </table>      
        </div><!--end table content--->        
    </div><!-- /.row -->
    <div id="content">
        <ul class="pagination" style="margin-left:15px;">
            <?php
            if ($geteachmonthsalarys->last === 1 || $geteachmonthsalarys->last === 0) {
                
            } else {
                ?>
                <li><a href="monthlysalary">First</a></li>
                <li><a href="monthlysalary?page=<?= $geteachmonthsalarys->before; ?>">Previous</a></li>
                <li><a href="monthlysalary?page=<?= $geteachmonthsalarys->next; ?>">Next</a></li>
                <li><a href="monthlysalary?page=<?= $geteachmonthsalarys->last; ?>">Last</a></li>
                <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $geteachmonthsalarys->current, " of ", $geteachmonthsalarys->total_pages; ?></span></li>
                <?php
            }
            ?>
        </ul>
    </div>
    <!-- calculate salary-->
    <div id="edit_dect_dia" class="navbar"></div><div id="add_new_dt" class="navbar"></div>





