<!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
              <b>Salary Detail</b>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> <b>Home</b></a></li>
            <li class="active"><b>Salary Detail</b></li>
          </ol>
        </section>
        
        
        <!-- Main content -->
        <section class="content">  
          <div class="row">
		  <div class="col-md-12"><!--start add user form--->
		  
			<div style="line-height:30px; width:65%;">
			<div style="float:right; margin-bottom:10px;">
			<a href="#" class="button print"><b>Print</b></a>
			</div>
	<div style="clear:right;"></div>
        <?php 
        $sum='';
        $deduce='';
        foreach($getsalarydetails as $getsalarydetail){
        ?>
				<div style="border:1px solid #dcdedf;" id="printable">
				<center style="font-size:16px;"><b>Pay slip for : <i style="color:#4682B4"><?php echo "<b style='color:black'>".date("M - Y", strtotime( $getsalarydetail->salarydet->pay_date))."</b>";?></i></b></center>
				
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Name </b></div>
				<div><?php                                 
                                echo " <b>:</b> ".$getsalarydetail->core->member_login_name;
                                ?></div>
				</div>
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Department </b></div>
				<div><?php                                 
                                echo " <b>:</b> ".$getsalarydetail->core->member_dept_name;
                                ?></div>
				</div>
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Position </b></div>
				<div><?php                                 
                                //echo "Web Developer";
                                echo " <b>:</b> ".$getsalarydetail->core->position;
                                ?></div>
				</div>
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Basic salary </b></div>
				<div><?php 
                                $sum+=$getsalarydetail->salarydet->basic_salary;
                                echo " <b>:</b> ".$getsalarydetail->salarydet->basic_salary;
                                ?></div>
				</div>
				
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>OT : 10000*2hr</b></div>
				<div><?php 
                                $sum+=$getsalarydetail->salarydet->overtime;
                                echo " <b>:</b> ".$getsalarydetail->salarydet->overtime;
                                ?></div>
				</div>
                                <?php
                                if(!empty($getallowance)){
                                foreach($getallowance as $getallowances){
                                    $sum=$sum+$getallowances['allowance_amount'];
                                ?>
                                <div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b><?php echo $getallowances['allowance_name'];?></b></div>
				<div><?php echo " <b>:</b> ".$getallowances['allowance_amount'];?></div>
				</div>
                                <?php
                                }
                                }
                                ?>
                                
				<div style="border-bottom:1px dotted gray; background-color:#e0e8f2;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Total amount </b></div>
                                <div>
                                    <?php
                                    echo " <b>:</b> ".$sum;
                                    ?>
                                </div>
				</div>
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Absent Deduction </b></div>
				<div><?php                                 
                                echo " <b>:</b> ".$getsalarydetail->salarydet->absent_dedution;
                                ?></div>
				</div>
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>SSC </b></div>
				<div><?php 
                                $deduce+=$getsalarydetail->salarydet->ssc_emp;
                                echo " <b>:</b> ".$getsalarydetail->salarydet->ssc_emp;
                                ?></div>
				</div>
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Income Tax </b></div>
				<div><?php 
                                $deduce+=$getsalarydetail->salarydet->income_tax;
                                echo " <b>:</b> ".$getsalarydetail->salarydet->income_tax;
                                ?></div>
				</div>
				<div style="border-bottom:1px dotted gray;">
				<div style="float:left; width:260px; padding-left:10px;"><b>Total Deduction </b></div>
				<div><?php echo " <b>:</b> ".$deduce;?></div>
				</div>
				<div style="border-bottom:1px dotted gray; background-color:#e0e8f2; font-weight:bold;">
				<div style="float:left; width:260px; padding-left:10px;">Net Payments </div>
                                <div>
                                    <?php
                                    $netpay=$sum-$deduce;
                                    echo ": ".$netpay;
                                    ?>
                                </div>
				</div>
				</div>
        <?php
        }
        ?>
			</div>	
		  </div>
          </div><!--end add user form--->
          </div><!-- /.row -->
		  
        </section><!-- /.content -->
