<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    

use Phalcon\Filter;
?>
<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->
            <div style="width:100%;">
                <div style="padding: 10px 10px 10px 10px">
                    <div style="float:right;">
                        <a href="#" class="button print">Print</a>
                    </div>
                </div>
                <div style="clear:both;">

                    <?php
                    $filter = new Filter();
                    $j = 0;
                    foreach ($getsalarydetails as $A) {
                        $j++;
                        $sum = 0;
                        $deduce = 0;
                        for ($i = 0; $i < count($A); $i++) {
                            ?>
                            <div style="padding: 0 10px 10px 10px" class="sample"  id="printable">
                                <h3><center>G-Next Official Salary Report</center></h3>
                                <input type="hidden" class="print_id" value="<?php echo $A[$i]->core->member_id; ?>">
                                <input type="hidden" id="paydate" value="<?php echo $A[$i]->salarydet->pay_date; ?>">
                                <div>
                                    <div style="width: 10%; float: left;">Name</div>
                                    <div><?php echo $filter->sanitize($A[$i]->core->member_login_name, "string"); ?></div>
                                </div>
                                <div>
                                    <div style="width: 10%; float: left;">Month</div>
                                    <div><?php echo date("M - Y", strtotime($A[$i]->salarydet->pay_date)); ?></div>
                                </div>
                                <div>
                                    <table border="1px solid gray" style="width:100%" class="detail-tbl">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Item</th>
                                                <th>Amount</th>
                                                <th width="200px"></th>
                                            </tr>

                                        </thead>
                                        <tbody>
                                        <td rowspan="5" style="border-bottom-color: #ecf0f5"></td>
                                        <td>Basic Salary</td>
                                        <td  style="text-align: right;"><?php
                                            echo number_format($filter->sanitize($A[$i]->salarydet->basic_salary, "string"));
                                            $sum = $sum + $A[$i]->salarydet->basic_salary;
                                            ?></td>
                                        <td></td>
                                        </tr>
                                        <tr>
                                            <td>Overtime Rate</td>
                                            <td style="text-align: right;" ><?php echo $filter->sanitize($A[$i]->salarymast->over_time, "string"); ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Overtime Hour</td>
                                            <td style="text-align: right;"><?php if($A[$i]->attend->overtime==0){echo "";}else{echo $filter->sanitize($A[$i]->attend->overtime, "string");} ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Overtime Payment</td>
                                            <td style="text-align: right;">
                                                <?php
                                                if ($filter->sanitize($A[$i]->attend->overtime, "string") > 0) {
                                                    $overtime_pay_perhr = $A[$i]->attend->overtime * $A[$i]->salarymast->over_time;
                                                    $overtime_payment = $overtime_pay_perhr * $A[$i]->attend->overtime;
                                                    echo $overtime_pay_perhr;
                                                   $sum = $sum + $overtime_fees +$A[$i]->salarydet->special_allowance;

                                                }
                                                ?>
                                            </td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Allowance for specific duty</td>
                                            <td style="text-align: right;"><?php if($A[$i]->salarydet->special_allowance!=null){echo number_format($filter->sanitize($A[$i]->salarydet->special_allowance, "string"));}?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">Gross Salary</td>
                                            <td style="text-align: right;"><?php $a = 0;if($A[$i]->salarydet->special_allowance!=null){$a =20000;}?><?php echo number_format(($sum+$a)); ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Deduce for absent</td>
                                            <td style="text-align: right;"><?php
                                                echo number_format($filter->sanitize($A[$i]->salarydet->absent_dedution, "string"));
                                                $deduce+=$A[$i]->salarydet->absent_dedution;
                                                ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Personal Income Tax</td>
                                            <td style="text-align: right;"><?php
                                                echo number_format($filter->sanitize($A[$i]->salarydet->income_tax, "string"));
                                                $deduce+=$A[$i]->salarydet->income_tax;
                                                ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">SSB Employee 2%</td>
                                            <td style="text-align: right;"><?php
                                                echo number_format($filter->sanitize($A[$i]->salarydet->ssc_emp, "string"));
                                                $deduce+=$A[$i]->salarydet->ssc_emp;
                                                ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Sub Total</td>
                                            <td style="text-align: right;"><?php echo number_format($deduce); ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Sub Total(Rounded up)</td>
                                            <td style="text-align: right;">
                                                <?php
                                                $sub_total = $sum - $deduce;
                                                echo number_format(round($sub_total,-2));
                                                ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Commute Fee</td>
                                            <td style="text-align: right;"><?php echo number_format($filter->sanitize($A[$i]->salarydet->travel_fee, "string")); ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2" height="50px">Grand Total</td>
                                            <td style="text-align: right;">
                                                <?php
                                               $grand_total = $sub_total + $A[$i]->salarydet->travel_fee+$a;
                                                echo number_format((round($grand_total, -2)));
                                                                                                
                                                ?>
                                            </td>
                                            <td></td>                   
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <?php
                        }

                        if ($j != count($getsalarydetails)) {
                            echo '<div class="p_break"></div>';
                        }
                    }
                    ?>

                </div>
            </div>
        </div>
    </div>
</section>
