<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    
 

use Phalcon\Filter;
?>
<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->

        <div class="col-md-12"><!--start add user form--->
            <div id="ssb_top">
                <div class="top-center">
                    လူမႈဖူလံုုေရးအဖြဲ႔<br>
                    အာမခံထားသူမ်ားအတြက္ လစဥ္ထည္႔၀င္ေၾကးေပးသြင္းစာရင္း
                    <span>နည္းဥပေဒ ၆၆(က)၊ (ပံုုစံ၁၃)</span>
                </div>
                <div class="ssb-reg">
                    <div class="ssb-left">အလုုပ္ဌာနအမည္  :
                        <span><u>G Next Co.;Ltd </u></span>
                    </div>
                    <div>
                        အလုုပ္ဌာန မွတ္ပံုုတင္အမွတ္  .....................................
                        <br>
                        .......................................................လအတြက္
                    </div>
                </div>
            </div>
            <table border="1px;" class="tbl-tax">
                <thead>
                    <tr>
                        <td rowspan="2">
                            Sr No.<br>
                            စဥ္
                        </td>
                        <td rowspan="2">
                            Insurance Name<br>
                            အာမခံထားသူအမည္
                        </td>
                        <td rowspan="2">
                            SSN.No<br>
                            အာမခံစီစစ္ေရးအမွတ္
                        </td>
                        <td rowspan="2">
                            Payment<br>
                            လုုပ္ခလစာ
                        </td>
                        <td colspan="2">
                            Health and Social Care<br>
                            Insurance System<br>
                            က်န္းမာေရးႏွင္္႔လူမႈေရး<br>
                            ေစာင္႔ေရွာက္မႈစနစ္
                        </td>

                        <td>
                            Employment Injury Benefit Insurance System
                        </td>
                        <td colspan="3">
                            Total<br>
                            စုုစုုေပါင္း
                        </td>

                        <td rowspan="2">Remark
                            <br> မွတ္ခ်က္
                        </td>
                    </tr>
                    <tr>

                        <td>
                            Employer<br>
                            အလုုပ္ရွင္
                        </td>
                        <td>
                            Employee<br>
                            အလုုပ္သမား
                        </td>
                        <td>
                            Employer<br>
                            အလုုပ္ရွင္
                        </td>

                        <td>
                            Employer<br>
                            အလုုပ္ရွင္  ၃%
                        </td>
                        <td>
                            Employee<br>
                            အလုုပ္သမား ၂%
                        </td>
                        <td>
                            Total<br>
                            စုုစုုေပါင္း ၅%
                        </td>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>၁</td>
                        <td>စုုဇင္ေက်ာ္</td>
                        <td></td>
                        <td>၁၈၀၀၀၀</td>
                        <td>၅၀၀၀</td>
                        <td>၅၀၀၀</td>
                        <td>၂၅၀၀</td>
                        <td>၇၅၀၀</td>
                        <td>၅၀၀၀</td>
                        <td>၁၂၅၀၀</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>၂</td>
                        <td>ေဒးဗစ္</td>
                        <td></td>
                        <td>၁၈၀၀၀၀</td>
                        <td>၅၀၀၀</td>
                        <td>၅၀၀၀</td>
                        <td>၂၅၀၀</td>
                        <td>၇၅၀၀</td>
                        <td>၅၀၀၀</td>
                        <td>၁၂၅၀၀</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>၁၅၀၀၀</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
