<?php
    use Phalcon\Filter;
?>
<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->
            <div style="width:100%;">
                <div style="padding: 10px 10px 10px 10px">
                    <div style="float:left;"><button class="btnEditInfo">EDIT</button>
                    <button id="btn_savedetail" disabled class="txtenable">Save</button>
<button id="btn_resign" class="btn_resign" >Resign</button>                    </div>
                    <div style="float:right;">
                    <a href="#" id="display1" class="display">PREV</a> |
                    <a href="#" id="display" class="display">NEXT</a>
                    </div>
                </div>
                <div style="clear:both;">
                    

<div style="padding: 0 10px 10px 10px" class="sample">
    <h3><center>G-Next Official Salary Report</center></h3>
<div>
    <div style="width: 10%; float: left;"></div>
    <div>
        <input type="hidden" value="" id="member_id" name="member_id">
    </div>
</div>
<div>
    <div style="width: 10%; float: left;"></div>
    <div></div>
</div>
<div>
    <table border="1px solid gray" style="width:100%" class="detail-tbl">
                <thead>
                    <tr>
                        <th colspan="2"></th>
                        <th></th>
                        <th width="200px"></th>
                        
                    </tr>

                </thead>
                <tbody>
                <td rowspan="5" style="border-bottom-color: #ecf0f5"></td>
    <td></td>
    <td><input type="text" name="txtbsalary" value="" id="txtbsalary" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><input type="text" name="txtovertimerate" value="" id="txtovertimerate" style="width:50px;" disabled="disabled" class="txtenable">%</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><input type="text" name="txtovertimehour" value="hr" id="txtovertimehour" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><input type="text" name="txtovertimepay" value="" id="txtovertimepay" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><input type="text" name="txtallowance" value="" id="txtallowance" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
      <td colspan="2"></td>
  <td></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"></td>
  <td><input type="text" name="txtincome" value="" id="txtallowance" disabled="disabled" class="txtenable"></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"></td>
  <td><input type="text" name="txtincome" value="" id="txtallowance" disabled="disabled" class="txtenable"></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"></td>
  <td><input type="text" name="txtssb" value="" id="txtssb" disabled="disabled" class="txtenable"></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("subtotal");?></td>
  <td></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("rounded_up");?></td>
  <td>
  ></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("commute_fee");?></td>
  <td></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2" height="50px"><?= $t->_("grand_total");?></td>
  <td>
      
  </td>
  <td></td>                   
  </tr>
</tbody>
</table>
    </div>
                </div>


</div>
        </div>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
