<?php
    use Phalcon\Filter;
?>
<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->
            <div style="width:100%;">
                <div style="padding: 10px 10px 10px 10px">
                    <div style="float:left;"><button class="btnEditInfo">EDIT</button>
                    <button id="btn_savedetail" disabled class="txtenable">Save</button>
<button id="btn_resign" class="btn_resign" >Resign</button>                    </div>
                    <div style="float:right;">
                    <a href="#" id="display1" class="display preimg"><span class="prehide">PREV</span></a> |
                    <a href="#" id="display" class="display nextimg"><span class="prehide">NEXT</span></a>
                    </div>
                </div>
                <div style="clear:both;">
                    <?php
//                    for ($x = 1; $x <= 3; $x++) {
//    echo '<div class="sample">div'.$x.'</div>';
//} 
//                    ?>
<!--                <div class="sample">div1</div>
                <div clas
                </div>

        </div>
        </dis="sample">div2</div>
                <div class="sample">div3</div>-->
<?php 
        
         $filter = new Filter(); 
         
        $sum='';
        $deduce='';
        //print_r($getsalarydetails);
        foreach($getsalarydetails as $A){
            for($i=0;$i<count($A);$i++){
                //echo $A[$i]['member_id'];
                
          
?>
<div style="padding: 0 10px 10px 10px" class="sample">
    <h3><center>G-Next Official Salary Report</center></h3>
<div>
    <div style="width: 10%; float: left;"><?= $t->_("name");?></div>
    <div><?php echo $filter->sanitize($A[$i]->core->full_name , "string"); ?>
        <input type="hidden" value="<?php echo $A[$i]->core->member_id;?>" id="member_id" name="member_id">
        <input type="hidden" value="<?php echo $year;?>" id="year" name="year">
        <input type="hidden" value="<?php echo $month;?>" id="month" name="month">
    </div>
</div>
<div>
    <div style="width: 10%; float: left;"><?= $t->_("month");?></div>
    <div><?php echo date("M - Y", strtotime( $A[$i]->salarydet->pay_date));?></div>
</div>
<div>
    <table border="1px solid gray" style="width:100%" class="detail-tbl">
                <thead>
                    <tr>
                        <th colspan="2"><?= $t->_("item");?></th>
                        <th><?= $t->_("amount");?></th>
                        <th width="200px"></th>
                        
                    </tr>

                </thead>
                <tbody>
                <td rowspan="5" style="border-bottom-color: #ecf0f5"></td>
    <td><?= $t->_("bsalary");?></td>
    <td><input type="text" name="txtbsalary" value="<?php echo $filter->sanitize($A[$i]->salarydet->basic_salary , "string"); $sum+=$A[$i]->salarydet->basic_salary;?>" id="txtbsalary" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
    <td><?= $t->_("overtime_rate");?></td>
    <td><input type="text" name="txtovertimerate" value="<?php echo $filter->sanitize($A[$i]->salarymast->over_time , "string");?>" id="txtovertimerate" style="width:50px;" disabled="disabled" class="txtenable">%</td>
    <td></td>
  </tr>
  <tr>
    <td><?= $t->_("overtime_hour");?></td>
    <td><input type="text" name="txtovertimehour" value="<?php echo $filter->sanitize($A[$i]->attend->overtime , "string");?>hr" id="txtovertimehour" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
    <td><?= $t->_("overtime_payment");?></td>
    <td><input type="text" name="txtovertimepay" value="<?php 
    if($filter->sanitize($A[$i]->attend->overtime , "string")>0){
        $overtime_pay_perhr=$A[$i]->salarydet->basic_salary*$A[$i]->salarymast->over_time/100;
        $overtime_payment=$overtime_pay_perhr*$A[$i]->attend->overtime;
        echo $overtime_payment;
        $sum+=$overtime_payment;
    }
    ?>" id="txtovertimepay" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
    <td><?= $t->_("allowance_for_specific");?></td>
    <td><input type="text" name="txtallowance" value="" id="txtallowance" disabled="disabled" class="txtenable"></td>
    <td></td>
  </tr>
  <tr>
      <td colspan="2"><?= $t->_("gross_salary");?></td>
  <td><?php echo $sum; ?></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("deduce_for_absent");?></td>
  <td><input type="text" name="txtincome" value="<?php echo $filter->sanitize($A[$i]->salarydet->absent_dedution , "string"); $deduce+=$A[$i]->salarydet->absent_dedution;?>" id="txtallowance" disabled="disabled" class="txtenable"></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("personal_income");?></td>
  <td><input type="text" name="txtincome" value="<?php echo $filter->sanitize($A[$i]->salarydet->income_tax , "string"); $deduce+=$A[$i]->salarydet->income_tax;?>" id="income_tax" disabled="disabled" class="txtenable"></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("ssb_employee");?></td>
  <td><input type="text" name="txtssb" value="<?php echo $filter->sanitize($A[$i]->salarydet->ssc_emp , "string"); $deduce+=$A[$i]->salarydet->ssc_emp; ?>" id="txtssb" disabled="disabled"></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("subtotal");?></td>
  <td><?php echo $deduce; ?></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("rounded_up");?></td>
  <td>
  <?php 
  $sub_total=$sum-$deduce;
  echo $sub_total;
  ?></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2"><?= $t->_("commute_fee");?></td>
  <td><?php echo $filter->sanitize($A[$i]->salarydet->travel_fee , "string"); ?></td>
  <td></td>                   
  </tr>
  <tr>
  <td colspan="2" height="50px"><?= $t->_("grand_total");?></td>
  <td>
      <?php
      $grand_total=$sub_total+$A[$i]->salarydet->travel_fee;
      echo $grand_total;
      ?>
  </td>
  <td></td>                   
  </tr>
</tbody>
</table>
    </div>
                </div>
<?php
  }
  $sum=0;
  $deduce=0;
        }
?>

</div>
        </div>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
