<?php
    use Phalcon\Filter;
?>
<section class="content-header" style="height:auto;margin-top: 5px;">
    <h1>
        Salary Lists
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Salary Lists</li>
               
    </ol>
    <br>
    <div style="float:right; padding-bottom: 10px;">
    <a href="" class="button export" onclick="Export.Export.apply(this, [$('table.listtbl'), 'salary_list.csv']);">Export</a> 
    </div>
</section>

<!-- Main content -->
<section class="content">
    
    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Basic_Salary</th>
                        <th>Travel_Fee</th>
                        <th>Overtime</th>
                        <th>SSC_Emp</th>
                        <th>SSC_Comp</th>
                        <th width="30px"></th>
                    </tr>

                </thead>
                <tbody style="display:none;">
                    <?php
                    $filter = new Filter();
                    $i = 1;
                    foreach ($salarydetail as $salarydetails) {
                        ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $filter->sanitize($salarydetails->core->member_login_name, "string"); ?></td>
                            <td><?php echo number_format($filter->sanitize($salarydetails->salarymas->basic_salary, "int")); ?></td>
                            <td><?php echo number_format($filter->sanitize($salarydetails->salarymas->travel_fee, "int")); ?></td>
                            <td><?php echo $filter->sanitize($salarydetails->salarymas->over_time, "int").' %' ?></td>
                            <td><?php echo $filter->sanitize($salarydetails->salarymas->ssc_emp, "int").' %' ?></td>
                            <td><?php echo $filter->sanitize($salarydetails->salarymas->ssc_comp, "int").' %' ?></td>
                            <td><input type="button" class="btn btn-default displaypopup" onclick="return false;" id="<?= $salarydetails->salarymas->id; ?>" value="Edit"></td>                            
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>

                   
                </tbody>
                <tfoot style="display:none;"></tfoot>
            </table>      
        </div><!--end table content--->
        <div id="content"></div>
    </div><!-- /.row -->
    <div id="content"></div>
</section><!-- /.content -->
<div id="edit_salary_dia"></div>


