<section class="content-header">
    <h1>
        <b>Salary Lists</b>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <b>Home</b></a></li>
        <li class="active"><b>Salary Lists</b></li>
        <a href="" class="button export" onclick="Export.Export.apply(this, [$('table.listtbl'), 'salary_list.csv']);"><b>Export</b></a>        
    </ol>
</section>

<!-- Main content -->
<section class="content">
    
    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Basic_Salary</th>
                        <th>Travel_Fee</th>
                        <th>Overtime</th>
                        <th>SSC_Emp</th>
                        <th>SSC_Comp</th>
                        <th width="30px"></th>
                    </tr>

                </thead>
                <tbody style="display:none;">
                    <?php
                    $i = 1;
                    foreach ($salarydetail as $salarydetails) {
                        ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $salarydetails['member_login_name'] ?></td>
                            <td><?php echo $salarydetails['basic_salary'] ?></td>
                            <td><?php echo $salarydetails['travel_fee'] ?></td>
                            <td><?php echo $salarydetails['over_time'].'%' ?></td>
                            <td><?php echo $salarydetails['ssc_emp'].'%' ?></td>
                            <td><?php echo $salarydetails['ssc_comp'].'%' ?></td>
                            <td><input type="button" class="btn btn-default displaypopup" onclick="return false;" id="<?= $salarydetails['id'] ?>" value="Edit"></td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody>
                <tfoot style="display:none;"></tfoot>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
</section><!-- /.content -->
<div id="edit_salary_dia"></div>


