<?php

use Phalcon\Filter;
?>
<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->
            <div style="width:100%;">
                <div style="padding: 10px 10px 10px 10px">
                    <div style="float:left;"><button class="btnEditInfo">EDIT</button>
                        <button id="btn_savedetail" class="txtenable" disabled>Save</button>
                        <button id="btn_resign" class="btn_resign" >Resign</button>
                    </div>
                    <div style="float:right;">
                        <a href="#" id="display1" class="display">PREV</a> |
                        <a href="#" id="display" class="display">NEXT</a>
                    </div>
                </div>
                <div style="clear:both;">
                    <?php
                    $filter = new Filter();

                    $sum = '';
                    $deduce = '';
                    //print_r($getsalarydetails);
                    foreach ($getsalarydetails as $A) {
                        for ($i = 0; $i < count($A); $i++) {
                            //echo $A[$i]['member_id'];
                            ?>
                            <div style="padding: 0 10px 10px 10px" class="sample">
                                <h3><center>G-Next Official Salary Report</center></h3>
                                <div>
                                    <div style="width: 10%; float: left;">Name</div>
                                    <div><?php echo $filter->sanitize($A[$i]->core->member_login_name, "string"); ?>
                                        <input type="hidden" value="<?php echo $A[$i]->core->member_id; ?>" id="member_id" name="member_id">
                                    </div>
                                </div>
                                <div>
                                    <div style="width: 10%; float: left;">Month</div>
                                    <div><?php echo date("M - Y", strtotime($A[$i]->salarydet->pay_date)); ?></div>
                                </div>
                                <div>
                                    <table border="1px solid gray" style="width:100%" class="detail_tbl">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Item</th>
                                                <th>Amount</th>
                                                <th width="200px"></th>

                                            </tr>

                                        </thead>
                                        <tbody>
                                        <td rowspan="5" style="border-bottom-color: #ecf0f5"></td>
                                        <td>Basic Salary</td>
                                        <td><input type="text" name="txtbsalary" class="txtenable" value="<?php echo $filter->sanitize($A[$i]->salarydet->basic_salary, "string");
                            $sum+=$A[$i]->salarydet->basic_salary; ?>" id="txtbsalary" disabled="disabled"></td>
                                        <td></td>
                                        </tr>
                                        <tr>
                                            <td>Overtime Rate</td>
                                            <td><input type="text" name="txtovertimerate" class="txtenable" value="<?php echo $filter->sanitize($A[$i]->salarymast->over_time, "string");
                            $sum+=$A[$i]->salarymast->over_time; ?>" id="txtovertimerate" style="width:50px;" disabled="disabled">%</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Overtime Hour</td>
                                            <td><input type="text" name="txtovertimehour" value="<?php echo $filter->sanitize($A[$i]->attend->overtime, "string"); ?>hr" id="txtovertimehour" disabled="disabled"></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Overtime Payment</td>
                                            <td><input type="text" name="txtovertimepay" value="<?php
                                                if ($filter->sanitize($A[$i]->attend->overtime, "string") > 0) {
                                                    $overtime_pay_perhr = $A[$i]->salarydet->basic_salary * $A[$i]->salarymast->over_time / 100;
                                                    $overtime_payment = $overtime_pay_perhr * $A[$i]->attend->overtime;
                                                    echo $overtime_payment;
                                                    $sum+=$overtime_payment;
                                                }
                                                ?>" id="txtovertimepay" disabled="disabled"></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Allowance for specific duty</td>
                                            <td><input type="text" name="txtallowance" class="txtenable" value="" id="txtallowance" disabled="disabled"></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">Gross Salary</td>
                                            <td><?php echo number_format($sum); ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Deduce for Absent</td>
                                            <td><input type="text" name="txtincome" value="<?php echo $filter->sanitize($A[$i]->salarydet->absent_dedution, "string");
                                                $deduce+=$A[$i]->salarydet->income_tax; ?>" id="txtallowance" disabled="disabled"></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Personal Income Tax</td>
                                            <td><input type="text" name="txtincome" value="<?php echo $filter->sanitize($A[$i]->salarydet->income_tax, "string");
                                                $deduce+=$A[$i]->salarydet->income_tax; ?>" id="txtallowance" disabled="disabled"></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">SSB Employee 2%</td>
                                            <td><input type="text" name="txtssb" value="<?php echo $filter->sanitize($A[$i]->salarydet->ssc_emp, "string");
                                                $deduce+=$A[$i]->salarydet->ssc_emp; ?>" id="txtssb" disabled="disabled"></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Sub Total</td>
                                            <td><?php echo number_format($deduce); ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Sub Total(Rounded up)</td>
                                            <td>
        <?php
        $sub_total = $sum - $deduce;
        echo number_format($sub_total);
        ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2">Commute Fee</td>
                                            <td><?php echo number_format($filter->sanitize($A[$i]->salarydet->travel_fee, "string")); ?></td>
                                            <td></td>                   
                                        </tr>
                                        <tr>
                                            <td colspan="2" height="50px">Grand Total</td>
                                            <td>
        <?php
        $grand_total = $sub_total + $A[$i]->salarydet->travel_fee;
        echo number_format($grand_total);
        ?>
                                            </td>
                                            <td></td>                   
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
        <?php
    }
}
?>

                </div>
            </div>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
