
	<style type="text/css">
      body { }
      ul#tabs { list-style-type: none; margin: 10px 0 0 0; padding: 0 0 0.3em 0; }
      ul#tabs li { display: inline; }
      ul#tabs li a { color: #42454a; background-color: #f9f9fa; border: 1px solid #c9c3ba; border-bottom: none; padding: 0.3em; text-decoration: none; }
      ul#tabs li a:hover { background-color: #f1f0ee; }
      ul#tabs li a.selected { color: #000; background-color: #f9f9fa; font-weight: bold; padding: 0.7em 0.3em 0.38em 0.3em; }
      div.tabContent { border: 1px solid #c9c3ba; padding: 0.5em; background-color: #f9f9fa; }
      div.tabContent.hide { display: none; }
    </style>
<section class="content-header">
    <h1>
        Salary Setting
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Salary Setting</li>
    </ol>
</section><br>
    <ul id="tabs">
      <li><a class="selected" href="#about">Tax Setting</a></li>
      <li><a class="" href="#advantages">Deduction Setting</a></li>

    </ul>
<form action="" method="post">
    <div class="tabContent" id="about">
        <!-- start Tax setting--->
       
      <table class="listtbl">
  <thead>
    <tr>
			<th width="120px">ID</th>
			<th>Taxs From </th>
			<th>Taxs To</th>
			<th>Taxs Rate</th>
			<th>SSC emp</th>
			<th>SSC comp</th>
			
			
			<th width="50px"></th>
	</tr>
	
  </thead>
  <tbody><?php
               
                foreach ($result  as $list) {
                    ?>
				<tr>
			  		<td><?php echo $list['id'];?></td>
			  		<td><?php echo $list['taxs_from'];?></td>
			  		<td><?php echo $list['taxs_to'];?></td>
			  		<td id='tbl-no'><?php echo $list['taxs_rate'];?></td>
			  		<td id='tbl-no'><?php echo $list['ssc_emp'];?></td>
			  		<td id='tbl-no'><?php echo $list['ssc_comp'];?></td>
					
					
					<td id='tbl-no'><input type="button" class="btn btn-default taxpopup" onclick="return false;" id="<?= $list['id'] ?>" value="Edit"></td>
			  	</tr>
                 <?php
                }
                ?>
  </tbody>
      </table>
        
        <div id="edit_tax_dia" class="navbar"></div>
    </div>

    <div class="tabContent hide" id="advantages"><!-- start Deduction setting-->
        <div class="buttons">
            <input type="button" class="addbtn add" onclick="return false;" value="Add New Deduction">
			
			
	 </div>
      <table class="listtbl">
  <thead>
    <tr>
			<th width="120px">ID</th>
			<th>Deduction Name </th>
			<th>Deduction Amount</th>
			
			
			<th width="50px"></th>
	</tr>
	
  </thead>
  <tbody><?php
               $n=0;
                foreach ($deduction as $list) {$n++;
                    ?>
				<tr>
			  		<td><?php echo $n;?></td>
			  		<td><?php echo $list['deduce_name'];?></td>
			  		<td><?php echo $list['amount'];?></td>
			  		
					
					
					<td id='tbl-no'><input type="button" class="btn btn-default dedtpopup" onclick="return false;" id="<?= $list['deduce_id'] ?>" value="Edit"></td>
			  	</tr>
                 <?php
                }
                ?>
  </tbody>
      </table>
        
    </div><!-- end allowance setting--><div id="edit_dect_dia" class="navbar"></div><div id="add_new_dt" class="navbar"></div>
	<div style="height:10px;"></div>
   
</form>
   

  

</body>
