<?php
    use Phalcon\Filter;
?>
	<style type="text/css">
      ul#tabs { list-style-type: none; margin: 10px 0 0 0; padding: 0 0 0.3em 0; }
      ul#tabs li { display: inline; }
      ul#tabs li a { color: #42454a; background-color: #f9f9fa; border: 1px solid #c9c3ba; border-bottom: none; padding: 0.3em; text-decoration: none; }
      ul#tabs li a:hover { background-color: #f1f0ee; }
      ul#tabs li a.selected { color: #000; background-color: #f9f9fa; font-weight: bold; padding: 0.7em 0.3em 0.38em 0.3em; }
      div.tabContent { border: 1px solid #c9c3ba; padding: 0.5em; background-color: #f9f9fa; }
      div.tabContent.hide { display: none; }
    </style>
<section class="content-header" style="height:auto;">
    <h1>
        Salary Setting
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Salary Setting</li>
    </ol>
</section><br>
    
<body onload="init()">
   
    <ul id="tabs">
      <li><a class="selected" href="#about">Tax Setting</a></li>
      <li><a class="" href="#advantages">Deduction Setting </a></li>

    </ul>
<form action="" method="post">
    <div class="tabContent" id="about"><!-- start Basic salary setting--->
      <table class="listtbl">
  <thead>
    <tr>
			<th width="120px">ID</th>
			<th>Taxs From </th>
			<th>Taxs To</th>
			<th>Taxs Rate</th>
			<th>SSC emp</th>
			<th>SSC comp</th>
			
			
			<th width="50px"></th>
	</tr>
	
  </thead>
  <tbody><?php
               $filter = new Filter();
                foreach ($result  as $list) {
                    ?>
				<tr>
			  		<td><?php echo $list['id'];?></td>
			  		<td><?php echo number_format($filter->sanitize($list['taxs_from'],"int"));?></td>
			  		<td><?php echo number_format($filter->sanitize($list['taxs_to'],"int"));?></td>
			  		<td id='tbl-no'><?php echo number_format($filter->sanitize($list['taxs_rate'],"int"));?></td>
			  		<td id='tbl-no'><?php echo number_format($filter->sanitize($list['ssc_emp'],"int"));?></td>
			  		<td id='tbl-no'><?php echo number_format($filter->sanitize($list['ssc_comp'],"int"));?></td>
					
					
<!--					<td id='tbl-no'><input type="button" class="btn btn-default taxpopup" onclick="return false;" id="<?= $list['id'] ?>" value="Edit"></td>-->
                                         <td id='tbl-no'>
                                                 <a href="#" onclick="return false;" style="float:right;" class="inedit taxpopup" id="<?= $list['id'] ?>"></a>
                                         </td>
			  	</tr>
                 <?php
                }
                ?>
  </tbody>
      </table>
        
        
    </div><!-- start Basic salary setting-->
    <div class="tabContent hide" id="advantages"><!-- start allowance setting-->
      <!-- <div class="buttons">
            <input type="button" class="addbtn add" onclick="return false;" value="Add New Deduction">
			
	 </div>-->
      <table class="listtbl">
  <thead>
    <tr>
			<th width="120px">ID</th>
			<th>Deduction Name </th>
			<th>Deduction Amount</th>
			
			
			<!--<th width="50px"><input style="color:black;height: 50px;"  id="inimg" type="button" class="addbtn add" onclick="return false;" value=" Add New Deduction"></th>-->
                        <th > 
                            <a href="#" onclick="return false;" style="float:right;"  class="button add" >Add New Deduction</a>
                        </th>
	</tr>
	
  </thead>
  <tbody><?php
               $n=0;
                foreach ($deduction as $list) {$n++;
                    ?>
				<tr>
			  		<td><?php echo $n;?></td>
			  		<td><?php echo $filter->sanitize($list['deduce_name'],"string");?></td>
			  		<td><?php echo number_format($filter->sanitize($list['amount'],"int"));?></td>
			  		
					
					
<!--					<td id='tbl-no'><input style="float:right;" type="button" class="btn btn-default dedtpopup" onclick="return false;" id="<?= $list['deduce_id'] ?>" value="Edit"></td>-->
                                        <td id='tbl-no'>
                                                 <a href="#" onclick="return false;" style="float:right;" class="inedit dedtpopup" id="<?= $list['deduce_id'] ?>"></a>
                                        </td>
			  	</tr>
                 <?php
                }
                ?>
  </tbody>
      </table>
        
    </div><!-- end allowance setting--><div id="edit_dect_dia" class="navbar"></div><div id="add_new_dt" class="navbar"></div>
	<div style="height:10px;"></div><div id="edit_tax_dia" class="navbar"></div>
<div id="confirm" class="navbar"></div>

</form>
   

  

</body>
