<?php
    use Phalcon\Filter;
?>
<section class="content-header">
    <h1>
        Show Salary Detail
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Salary Detail</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->

            <div class="search_box">
            <form name="search_frm" id="search_frm">
                <div id="Menu" >
                    <input type="hidden" name="cond[mth]" value="<?php echo $month;?>" id="month">
                    <input type="hidden" name="cond[yr]" value="<?php echo $year;?>" id="year">
                    <div id="M_1">
                        User Name :
                        <span>
                            <select class="select" data-toggle="select" name="cond[username]">
                                <option value="">Name</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username->member_login_name; ?>"><?php echo $username->member_login_name; ?></option>
                                    <?php
                                }
                                ?>

                            </select>
                        </span>
                    </div>
                    <div id="M_2">
                        Department :
                        <span>
                            <select class="select" data-toggle="select" name="cond[dept]">
                                <option value="">Department</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username->member_dept_name; ?>"><?php echo $username->member_dept_name; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                    </div>
                    <div id="M_3">
                        Position :
                        <span>
                            <select class="select" data-toggle="select" name="cond[position]">
                                <option value="">Position</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username->position; ?>"><?php echo $username->position; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                    </div>
                    <div id="M_4">
                         Salary :
                        <select class="select" data-toggle="select" name="cond[salary]">
                            <option>200000~400000</option>
                            <option>400000~700000</option>
                            <option>700000~1000000</option>

                        </select>
                    </div>
                </div>
                <div class="search_btn_box"><!--search btn-->
                    <div>
                        <a href="#" class="button" id="search_salary" style="margin-left:71px; margin-right:28px;">Search</a>
                        <a href="#" class="button export">Export</a>
                    </div>
                </div><!--search btn-->
            </form>
            </div>
        </div>
    </div><!-- for search form-->
    <div style="height:20px;"></div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl" >
                <thead>
                    <tr>
                        
                        <th>Name</th>
                        <th>Department</th>
                        <th><center>Basic Salary</center></th>
                        <th><center>Overtime</center></th>
                        <th><center>Travel fees</center></th>
                        <th><center>Absent</center></th>
                        <th><center>Tax</center></th>
                        <th><center>SSC_comp</center></th>
                        <th><center>SSC_emp</center></th>
                        <th><center>Total</center></th>
                        <th width="30px"></th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                    $filter = new Filter();
                    
                    $month=$this->request->get('month');
                    $year=$this->request->get('year');
                    $i = 1;
                    $totalresult="";
                    foreach ($getsalarylists as $getsalarylist) {
                        ?>
                        <tr>
                           
                            <td><?php echo $filter->sanitize($getsalarylist['member_login_name'] , "string"); ?></td>
                            <td><?php echo $filter->sanitize($getsalarylist['member_dept_name'] , "string") ?></td>
                            <td><div class="td_style"><?php echo number_format($filter->sanitize($getsalarylist['basic_salary'], "int")); ?></div></td>
                            <td><div class="td_style"><?php echo number_format($filter->sanitize($getsalarylist['overtime'], "int")); ?></div></td>
                            <td><div class="td_style"><?php echo number_format($filter->sanitize($getsalarylist['travel_fee'], "int")); ?></div></td>
                            <td><div class="td_style"><?php echo number_format($filter->sanitize($getsalarylist['absent_dedution'], "int")); ?></div></td>
                            <td><div class="td_style"><?php echo number_format($filter->sanitize($getsalarylist['income_tax'], "int")); ?></div></td>
                            <td><div class="td_style"><?php echo number_format($filter->sanitize($getsalarylist['ssc_comp'], "int")); ?></div></td>
                            <td><div class="td_style"><?php echo number_format($filter->sanitize($getsalarylist['ssc_emp'], "int")); ?></div></td>
                            
                            <td><div class="td_style"><?php 
                            $totalresult+=$getsalarylist['total'];
                            echo number_format($getsalarylist['total']); 
                                    
                                ?></div></td>
                            <td><a href="payslip?member_id=<?php echo $getsalarylist['member_id']?> && month=<?php echo $month; ?> && year=<?php echo $year; ?>" class="button" id="displaypopup">Print</a></td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>

                    <tr style="background-color:#428bca; color:#ffffff;">
                        <td colspan="9" style="text-align:center;"><b>Total salary for all user</b></td>
                        <td><div class="td_style"><b><?php echo number_format($filter->sanitize($totalresult, "int"));?></b></div></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->

</section><!-- /.content -->
