<section class="content-header">
    <h1>
        Show Salary detail
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">salary detail</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->

            <div class="search_box">
            <form name="search_frm" id="search_frm">
                <div id="Menu" >
                    <div id="M_1">User Name: 
                        <span>
                            <select class="select" data-toggle="select" name="cond[username]">
                                <option>Name</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username['member_login_name']; ?>"><?php echo $username['member_login_name']; ?></option>
                                    <?php
                                }
                                ?>

                            </select>
                        </span>
                    </div>
                    <div id="M_4">
                        Dept: 
                        <span>
                            <select class="select" data-toggle="select" name="cond[dept]">
                                <option value="">Position</option>
                                <?php
                                foreach ($usernames as $username) {
                                    ?>
                                    <option value="<?php echo $username['member_dept_name']; ?>"><?php echo $username['member_dept_name']; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                    </div>
                    <div id="M_3">
                        Position: 
                        <span>
                            <select class="select" data-toggle="select" name="cond[position]">
                                <option>Project Leader</option>
                                <option>mobile developer</option>
                                <option>designer</option>
                                <option>developer</option>
                            </select>
                    </div>
                    <div id="M_2">
                        Monthly: 
                        <span>
                            <select class="select" data-toggle="select" name="cond[month]">
                                <option selected="selected">Month</option>
                                <?php
                                for ($i = 1; $i <= count($months); $i++) {
                                    ?>
                                    <option value="<?php
                                    if ($i < 10) {
                                        echo '0' . $i;
                                    } else {
                                        echo $i;
                                    }
                                    ?>"
                                            <?php //echo(isset($Mth)&&($Mth==$i)?' selected="selected"':'');?>
                                            ><?php echo $months[$i]; ?></option>
                                            <?php
                                        }
                                        ?>
                            </select>
                    </div>
                </div>
                <div class="search_btn_box"><!--search btn-->
                    <div style="float:left;">
                        salary:
                        <select class="select" data-toggle="select" name="cond[salary]">
                            <option>200000~400000</option>
                            <option>400000~700000</option>
                            <option>700000~1000000</option>

                        </select>
                    </div>
                    <div>
                        <a href="#" class="button" id="search_salary" style="margin-left:71px; margin-right:28px;">Search</a>
                        <a href="#" class="button export">Export</a>
                    </div>
                </div><!--search btn-->
            </form>
            </div>
        </div>
    </div><!-- for search form-->
    <div style="height:20px;"></div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->

            <table class="listtbl">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Department</th>
                        <th>Basic Salary</th>
                        <th>Overtime</th>
                        <th>Travel fees</th>
                        <th>Absent</th>
                        <th>Tax</th>
                        <th>SSC_comp</th>
                        <th>SSC_emp</th>
                        <th>Total</th>
                        <th width="30px"></th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                    $month=$this->request->get('month');
                    $year=$this->request->get('year');
                    $i = 1;
                    foreach ($getsalarylists as $getsalarylist) {
                        ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $getsalarylist['member_login_name'] ?></td>
                            <td><?php echo $getsalarylist['member_dept_name'] ?></td>
                            <td><?php echo $getsalarylist['basic_salary'] ?></td>
                            <td><?php echo $getsalarylist['overtime'] ?></td>
                            <td><?php echo $getsalarylist['travel_fee'] ?></td>
                            <td><?php echo $getsalarylist['absent_dedution'] ?></td>
                            <td><?php echo $getsalarylist['income_tax'] ?></td>
                            <td><?php echo $getsalarylist['ssc_comp'] ?></td>
                            <td><?php echo $getsalarylist['ssc_emp'] ?></td>
                            <td><?php echo $getsalarylist['total'] ?></td>
                            <td><a href="payslip?member_id=<?php echo $getsalarylist['member_id']?> && month=<?php echo $month; ?> && year=<?php echo $year; ?>" class="button" id="displaypopup">Print</a></td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>

                    <tr style="background-color:#428bca; color:#ffffff;">
                        <td colspan="10" style="text-align:center;"><b>Total salary for all user</b></td>
                        <td><b>######</b></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->

</section><!-- /.content -->