
<!-- Main content -->
<!-- Main content -->

<?php
if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    $monthName ='';
foreach ($salary_info as $value) {
   $date=$value->salary_detail->pay_date;
     $data = explode("-", $date);
//   $year = date("Y",$date);
   $dateObj   = DateTime::createFromFormat('!m', $data[1]);
   $monthName = $dateObj->format('F'); 
}
?>
<script src="<?php echo $baseUri ?>/public/common/js/jquery.min.js"></script>
        <style type="text/css" media="all">
            
       table {
    border-top-width: 0px;
    border-right-width: 0px;
    border-bottom-width: 0px;
    border-left-width: 0px; 
    }
    tr{
        display: block;
    }
   
      tbody tr.head {
      page-break-before: always;
      page-break-inside: avoid;
        
    }
 
    @media screen {
       
      tbody .head {
        display: none;
       
      }
    }
       </style>

<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->
            <span style="float: right;"><a href="#" title="Print" class="printing" id="printimg"></a></span>
            <div class="printable">
                <div id="ssb_top">
                    <div class="top-center">
                        လူမႈဖူလံုုေရးအဖြဲ႔<br>
                        အာမခံထားသူမ်ားအတြက္ လစဥ္ထည္႔၀င္ေၾကးေပးသြင္းစာရင္း
                        <span style="float: right;">နည္းဥပေဒ ၆၆(က)၊ (ပံုုစံ၁၃)</span>
                    </div>
                    <div class="ssb-reg">
                        <div class="ssb-left">အလုုပ္ဌာနအမည္  :
                            <span><u><?php foreach ($cominfo as $value) {echo $value->company_name;
    }
 ?></u></span>
                        </div>
                        <div class="ssb-right">
                            အလုုပ္ဌာန မွတ္ပံုုတင္အမွတ္  ......................................
                            <br>
                            <?php echo $monthName; ?> လအတြက္
                        </div>
                    </div>
                </div>
                <div class="clone_div">
                    
                <table border="" class="table_ssb" width="100%">
                     
  <thead>
    <tr class="head">
      <td width="35">Sr <br>No.<br> စဥ္ </td>
      
     <td width="125">  Insurance Name<br>    အာမခံထားသူအမည္ </td>
     
       <td width="137">   SSN.No<br>  အာမခံစီစစ္ေရး<br>        အမွတ္</td>
       
     <td width="75">   Payment<br>  လုုပ္ခလစာ </td>
     <td>
         
         <table>
             <tr>
                 <td width="150">
                       Health and Social Care<br>
                                Insurance System<br>
                                က်န္းမာေရးႏွင္္႔လူမႈေရး<br>
                                ေစာင္႔ေရွာက္မႈစနစ္
                 </td>
             </tr>
             <tr>
                 <td>
                     <table class="border-top">
             <tr>
                 <td style="border-right: 1px solid;">
                  Employer
                  <br>
အလုုပ္ရွင္
                 </td>
            
                 <td>
                       Employee
                       <br>
အလုုပ္သမား
                 </td>
             </tr>
         </table>
                 </td>
             </tr>
         </table>
         
     </td>
     <td width="124px">  
         
         <table >
             <tr>
                 <td>
                     Employment Injury <br>
                 Benefit Insurance <br>
                 System 
                 </td>
             </tr>
             <tr>
                 <td>
                     <table class="border-top">
                         <tr>
                             <td width="124px">        Employer
                     <br>
အလုုပ္ရွင္</td>
                         </tr>
                     </table>
              
                 </td>
             </tr>
         </table>
             
     </td>
       <td width="250px">
       
       <table width="247px">
             <tr>
                 <td>
                  Total
                  <br>
စုုစုုေပါင္း
 
                 </td>
             </tr>
             <tr>
                 <td>
                   <table class="border-top" >
             <tr>
                 <td style="border-right: 1px solid;">
                   Employer
                   <br>
အလုုပ္ရွင္ ၃%
                 </td>
            
                 <td style="border-right: 1px solid;">
                     Employee
                     <br>
အလုုပ္သမား ၂%
                 </td>
                 <td>
                   Total
                   <br>
စုုစုုေပါင္း ၅%

                 </td>
             </tr>
         </table>
                 </td>
             </tr>
         </table>
           
       </td>
     <td width="58">  
         Remark
         <br>
        မွတ္ခ်က္ </td>
    </tr>
  </thead>
   </table>
                </div>
                   <table border="1px;" class="table_ssb">
                       <tbody>
                        <?php
                        $no = 1;
                        $page=1;
                        $ssb_total = 0;
                        $sum1 = 0;
                        $sum2 = 0;
                        $sum3 = 0;
                        $sum4 = 0;
                        $sum5 = 0;
                        $Total = 0;
                        $pbreak=1; 
                        $b = 6;
                        if (!empty($salary_info)) {
                            foreach ($salary_info as $salary_infos) {
                               
                                ?><tr>
                                
                                    <td style="width:35px;"> <?php echo $no; ?> </td>
                                    <td style="width:125px;"><?php echo $salary_infos->core->mm_name; ?></td>
                                    <td  style="width:137px;"><?php echo $salary_infos->core->ssn_no; ?></td>
                                    <td style="text-align: right;width:75px;"><?php if($salary_infos->salary_detail->basic_salary>300000){echo number_format(300000);}else{echo number_format($salary_infos->salary_detail->basic_salary); }?></td>
                                    <td   style="text-align: right;width:76px;">
                                        <?php
                                        $sum1 = $sum1 + $salary_infos->salary_detail->ssc_emp;
                                        echo number_format($salary_infos->salary_detail->ssc_emp);
                                        ?>
                                    </td>
                                    <td width="79" style="text-align: right;">
                                        <?php
                                        $sum2 = $sum2 + $salary_infos->salary_detail->ssc_emp;
                                        echo number_format($salary_infos->salary_detail->ssc_emp);
                                        ?>
                                    </td>
                                    <td width="124" style="text-align: right;">
                                        <?php
                                        $onepercent = $salary_infos->salary_detail->ssc_emp / 2;
                                        $sum3 = $sum3 + $onepercent;
                                        echo number_format($onepercent);
                                        ?>
                                    </td>
                                    <td width="83" style="text-align: right;">
                                        <?php
                                        $ssb_total = $ssb_total + $salary_infos->salary_detail->ssc_comp;
                                        $sum4 = $sum4 + $salary_infos->salary_detail->ssc_comp;
                                        echo number_format($salary_infos->salary_detail->ssc_comp);
                                        ?>
                                    </td>
                                    <td width="83" style="text-align: right;">
                                        <?php
                                        $ssb_total = $ssb_total + $salary_infos->salary_detail->ssc_emp;
                                        $sum5 = $sum5 + $salary_infos->salary_detail->ssc_emp;
                                        echo number_format($salary_infos->salary_detail->ssc_emp);
                                        ?>
                                    </td>
                                    <td width="84" style="text-align: right;">
                                        <?php
                                        echo number_format($salary_infos->salary_detail->ssc_emp+ $salary_infos->salary_detail->ssc_comp);
                                        ?>
                                    </td>
                                    <td width="58" ></td>
                                </tr>
                                <?php
                                $no++;
//                                $pbreak++; 
//                               
//                                if($pbreak == $b){
                                ?>
<!--                                <tr class="page-break">
                                </tr>-->
                                <?php
//                                $b = $b+10;
//                                }
                            }
                            ?>
                                
                            <tr>
                                <td width="35px"></td>
                                <td width="125px"></td>
                                <td width="137"></td>
                                <td width="75" ></td>
                                <td width="76"  style="text-align: right;"><?php echo number_format($sum1) ?></td>
                                <td width="79" style="text-align: right;"><?php echo number_format($sum2) ?></td>
                                <td  width="124"  style="text-align: right;"><?php echo number_format($sum3) ?></td>
                                <td width="83"  style="text-align: right;"><?php echo number_format($sum4) ?></td>
                                <td width="83" style="text-align: right;"><?php echo number_format($sum5) ?></td>
                                <td width="84" style="text-align: right;">
                                    <?php
                                    $Total = $Total + $sum4 + $sum5;
                                    echo number_format($Total);
                                    ?></td>
                                <td width="59"></td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>   <div class="break"></div>
                 <script language="JavaScript" type="text/javascript">
	$(document).ready(function() { 
	  var head = $('.clone_div');
      
	  $("tbody tr:nth-child(20n+20)").after(head.clone());
	});
	</script>
                <div class="break"></div>
               
            </div>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
 
