<?php
    use Phalcon\Filter;
?>
<!-- Main content -->
<section class="content">
    <div class="row"><!-- for search form-->
        
        <div class="col-md-12"><!--start add user form--->
            <span style="float: right;"><a href="#" class="button print">Print</a></span>
            <div id="printable">
            <div id="ssb_top">
                <div class="top-center">
                    လူမႈဖူလံုုေရးအဖြဲ႔<br>
                    အာမခံထားသူမ်ားအတြက္ လစဥ္ထည္႔၀င္ေၾကးေပးသြင္းစာရင္း
                    <span>နည္းဥပေဒ ၆၆(က)၊ (ပံုုစံ၁၃)</span>
                </div>
                <div class="ssb-reg">
                    <div class="ssb-left">အလုုပ္ဌာနအမည္  :
                        <span><u>G Next Co.;Ltd </u></span>
                    </div>
                    <div>
                        အလုုပ္ဌာန မွတ္ပံုုတင္အမွတ္  .....................................
                        <br>
                        .......................................................လအတြက္
                    </div>
                </div>
            </div>
            
            <table border="1px;" class="tbl-tax">
                <thead>
                <tr>
                    <td rowspan="2">
                        Sr No.<br>
                            စဥ္
                    </td>
                    <td rowspan="2">
                        Insurance Name<br>
                        အာမခံထားသူအမည္
                    </td>
                    <td rowspan="2">
                        SSN.No<br>
                        အာမခံစီစစ္ေရးအမွတ္
                    </td>
                    <td rowspan="2">
                        Payment<br>
                        လုုပ္ခလစာ
                    </td>
                    <td colspan="2">
                        Health and Social Care<br>
                        Insurance System<br>
                        က်န္းမာေရးႏွင္္႔လူမႈေရး<br>
                        ေစာင္႔ေရွာက္မႈစနစ္
                    </td>
                    
                    <td>
                        Employment Injury Benefit Insurance System
                    </td>
                    <td colspan="3">
                        Total<br>
                        စုုစုုေပါင္း
                    </td>
                    
                    <td rowspan="2">Remark
                        <br> မွတ္ခ်က္
                    </td>
                </tr>
                <tr>
                    
                    <td>
                    Employer<br>
                    အလုုပ္ရွင္
                    </td>
                    <td>
                    Employee<br>
                    အလုုပ္သမား
                    </td>
                    <td>
                        Employer<br>
                        အလုုပ္ရွင္
                    </td>
                    
                    <td>
                        Employer<br>
                        အလုုပ္ရွင္  ၃%
                    </td>
                    <td>
                        Employee<br>
                        အလုုပ္သမား ၂%
                    </td>
                    <td>
                        Total<br>
                        စုုစုုေပါင္း ၅%
                    </td>
                    
                </tr>
                </thead>
                <tbody>
                    <?php
                    $no=1;
                    $ssb_total=0;
                    $sum1=0;
                    $sum2=0;
                    $sum3=0;
                    $sum4=0;
                    $sum5=0;
                    $Total=0;
                    foreach ($salary_info as $salary_infos) {
                    ?>
                    <tr>
                        <td><?php echo $no;?></td>
                        <td><?php echo $salary_infos['member_login_name'];?></td>
                        <td></td>
                        <td><?php echo $salary_infos['basic_salary'];?></td>
                        <td>
                            <?php 
                            $sum1=$sum1+$salary_infos['ssc_emp'];
                            echo $salary_infos['ssc_emp'];
                            ?>
                        </td>
                        <td>
                            <?php
                            $sum2=$sum2+$salary_infos['ssc_emp'];
                            echo $salary_infos['ssc_emp'];
                            ?>
                        </td>
                        <td>
                            <?php 
                            $onepercent=$salary_infos['ssc_emp']/2;
                            $sum3=$sum3+$onepercent;
                            echo $onepercent;
                            ?>
                        </td>
                        <td>
                            <?php
                            $ssb_total=$ssb_total+$salary_infos['ssc_comp'];
                            $sum4=$sum4+$salary_infos['ssc_comp'];
                            echo $salary_infos['ssc_comp'];
                            ?>
                        </td>
                        <td>
                            <?php 
                            $ssb_total=$ssb_total+$salary_infos['ssc_emp'];
                            $sum5=$sum5+$salary_infos['ssc_emp'];
                            echo $salary_infos['ssc_emp'];
                            ?>
                        </td>
                        <td>
                            <?php 
                            echo number_format($ssb_total);
                            ?>
                        </td>
                        <td></td>
                    </tr>
                    <?php
                    $no++;
                    }
                    ?>
                    
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><?php echo number_format($sum1)?></td>
                        <td><?php echo number_format($sum2)?></td>
                        <td><?php echo number_format($sum3)?></td>
                        <td><?php echo number_format($sum4)?></td>
                        <td><?php echo number_format($sum5)?></td>
                        <td>
                            <?php
                            $Total=$Total+$sum4+$sum5;
                            echo number_format($Total);
                            ?></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
