
<!-- Main content -->
<!-- Main content -->

<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    $monthName ='';
foreach ($salary_info as $value) {
   $date=$value->salary_detail->pay_date;
     $data = explode("-", $date);
//   $year = date("Y",$date);
   $dateObj   = DateTime::createFromFormat('!m', $data[1]);
   $monthName = $dateObj->format('F'); 
}

?>
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->
            <span style="float: right;"><a href="#" title="Print" class="print" id="printimg"></a></span>
            <div class="printable">
                <div id="ssb_top">
                    <div class="top-center">
                        လူမႈဖူလံုုေရးအဖြဲ႔<br>
                        အာမခံထားသူမ်ားအတြက္ လစဥ္ထည္႔၀င္ေၾကးေပးသြင္းစာရင္း
                        <span style="float: right;">နည္းဥပေဒ ၆၆(က)၊ (ပံုုစံ၁၃)</span>
                    </div>
                    <div class="ssb-reg">
                        <div class="ssb-left">အလုုပ္ဌာနအမည္  :
                            <span><u><?php foreach ($cominfo as $value) {echo $value->company_name;
    }
 ?></u></span>
                        </div>
                        <div class="ssb-right">
                            အလုုပ္ဌာန မွတ္ပံုုတင္အမွတ္  ......................................
                            <br>
                            <?php echo $monthName; ?> လအတြက္
                        </div>
                    </div>
                </div>

                <table border="1px;" class="tbl-tax">
                    <thead>
                        <tr>
                            <td rowspan="2">
                                Sr No.<br>
                                စဥ္
                            </td>
                            <td rowspan="2">
                                Insurance Name<br>
                                အာမခံထားသူအမည္
                            </td>
                            <td rowspan="2">
                                SSN.No<br>  
                                အာမခံစီစစ္ေရးအမွတ္
                            </td>
                            <td rowspan="2">
                                Payment<br>
                                လုုပ္ခလစာ
                            </td>
                            <td colspan="2">
                                Health and Social Care<br>
                                Insurance System<br>
                                က်န္းမာေရးႏွင္္႔လူမႈေရး<br>
                                ေစာင္႔ေရွာက္မႈစနစ္
                            </td>

                            <td>
                                Employment Injury Benefit Insurance System
                            </td>
                            <td colspan="3">
                                Total<br>
                                စုုစုုေပါင္း
                            </td>

                            <td rowspan="2">Remark
                                <br> မွတ္ခ်က္
                            </td>
                        </tr>
                        <tr>

                            <td>
                                Employer<br>
                                အလုုပ္ရွင္
                            </td>
                            <td>
                                Employee<br>
                                အလုုပ္သမား
                            </td>
                            <td>
                                Employer<br>
                                အလုုပ္ရွင္
                            </td>

                            <td>
                                Employer<br>
                                အလုုပ္ရွင္  ၃%
                            </td>
                            <td>
                                Employee<br>
                                အလုုပ္သမား ၂%
                            </td>
                            <td>
                                Total<br>
                                စုုစုုေပါင္း ၅%
                            </td>

                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $no = 1;
                        $ssb_total = 0;
                        $sum1 = 0;
                        $sum2 = 0;
                        $sum3 = 0;
                        $sum4 = 0;
                        $sum5 = 0;
                        $Total = 0;
                        if (!empty($salary_info)) {
                            foreach ($salary_info as $salary_infos) {
                                ?>
                                <tr>
                                    <td><?php echo $no; ?></td>
                                    <td><?php echo $salary_infos->core->member_login_name; ?></td>
                                    <td><?php echo $salary_infos->core->ssn_no; ?></td>
                                    <td style="text-align: right;"><?php if($salary_infos->salary_detail->basic_salary>300000){echo "300000";}else{echo $salary_infos->salary_detail->basic_salary; }?></td>
                                    <td style="text-align: right;">
                                        <?php
                                        $sum1 = $sum1 + $salary_infos->salary_detail->ssc_emp;
                                        echo $salary_infos->salary_detail->ssc_emp;
                                        ?>
                                    </td>
                                    <td style="text-align: right;">
                                        <?php
                                        $sum2 = $sum2 + $salary_infos->salary_detail->ssc_emp;
                                        echo $salary_infos->salary_detail->ssc_emp;
                                        ?>
                                    </td>
                                    <td style="text-align: right;">
                                        <?php
                                        $onepercent = $salary_infos->salary_detail->ssc_emp / 2;
                                        $sum3 = $sum3 + $onepercent;
                                        echo $onepercent;
                                        ?>
                                    </td>
                                    <td style="text-align: right;">
                                        <?php
                                        $ssb_total = $ssb_total + $salary_infos->salary_detail->ssc_comp;
                                        $sum4 = $sum4 + $salary_infos->salary_detail->ssc_comp;
                                        echo $salary_infos->salary_detail->ssc_comp;
                                        ?>
                                    </td>
                                    <td style="text-align: right;">
                                        <?php
                                        $ssb_total = $ssb_total + $salary_infos->salary_detail->ssc_emp;
                                        $sum5 = $sum5 + $salary_infos->salary_detail->ssc_emp;
                                        echo $salary_infos->salary_detail->ssc_emp;
                                        ?>
                                    </td>
                                    <td style="text-align: right;">
                                        <?php
                                        echo number_format($salary_infos->salary_detail->ssc_emp+ $salary_infos->salary_detail->ssc_comp);
                                        ?>
                                    </td>
                                    <td></td>
                                </tr>
                                <?php
                                $no++;
                            }
                            ?>

                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td style="text-align: right;"><?php echo number_format($sum1) ?></td>
                                <td style="text-align: right;"><?php echo number_format($sum2) ?></td>
                                <td style="text-align: right;"><?php echo number_format($sum3) ?></td>
                                <td style="text-align: right;"><?php echo number_format($sum4) ?></td>
                                <td style="text-align: right;"><?php echo number_format($sum5) ?></td>
                                <td style="text-align: right;">
                                    <?php
                                    $Total = $Total + $sum4 + $sum5;
                                    echo number_format($Total);
                                    ?></td>
                                <td></td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
                <div class="break"></div>
            </div>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
