<!-- Main content -->
<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    


foreach ($salary_info as $value) {
   $date=$value->salary_detail->pay_date;
   $month = explode("-", $date);

   $dateObj   = DateTime::createFromFormat('!m', $month[1]);
   $monthName = $dateObj->format('F'); 
}

?>
<section class="content">
    <div class="row"><!-- for search form-->
        <div class="col-md-12"><!--start add user form--->
            <span style="float: right;"><a href="#" title="Print" class="print" id="printimg"></a></span>
            <div class="printable">
                <div style="float:right">
                  ပတခ	(၀င)-၁၅။<br>
                   
                </div>
                <br>
                <div style="text-align: center;line-height: 27px;">
                    ၀င္ေငြခြန္ဥပေဒ  ပုဒ္မ ၁၆(ဃ) နွင္႔ ၁၆(စ) အရ လစာေခါင္းစဥ္နွင္႔<br>
                    အက်ံဴး၀င္သည္႔<br>
                    ၀င္ေငြမွ ၀င္ေငြခြန္လစဥ္နုတ္ယူေသာစာရင္း<br>
                    <?php echo $month[0]; ?> ခု၊ <?php echo$monthName; ?> လအတြက္။<br><br>

                </div>
                <table border="1px;" class="tbl-tax">
                    <thead>
                        <tr>
                            <td rowspan="3">
                                အမွတ္စဥ္
                            </td>
                            <td rowspan="3">
                              လခစားအမည္
                            </td>
                            <td rowspan="3">
                               ရာထူး/အလုပ္အကုိင္
                            </td>
                            <td rowspan="3">
                              လစာေငြ
                            </td>
                            <td rowspan="3">
                               ႏူတ္ယူသည့္ဝင္ေငြခြန္
                            </td>

                            <td rowspan="3">
                              မွတ္ခ်က္
                            </td>
<!--                            <td colspan="6">
                    <center>Tax Allowance</center>
                    </td>

                    <td rowspan="3">Taxable<br>
                        Income
                    </td>
                    <td rowspan="3">Income<br>
                        Tax for<br>
                        June 15
                    </td>
                    </tr>
                    <tr>


                        <td>
                            20%
                        </td>

                        <td>
                            <?php echo number_format("1000000"); ?>
                        </td>
                        <td>
                            <?php echo number_format("500000"); ?>
                        </td>
                        <td>
                            <?php echo number_format("1000000"); ?>
                        </td>
                        <td>
                            <?php echo number_format("1000000"); ?>
                        </td>
                        <td>

                        </td>
                    </tr>
                    <tr>
                        <td>
                            Basic<br>
                            Examption
                        </td>

                        <td>
                            Spouse
                        </td>
                        <td>
                            Child
                        </td>
                        <td>
                            Staying with<br>
                            Father
                        </td>
                        <td>
                            Staying with<br>
                            Mother
                        </td>
                        <td>
                            SSB
                        </td>-->
                    </tr>
                    
                    </thead>
                    <tbody>
<!--                          <tr>
                            <td rowspan="3">
                                (၁)
                            </td>
                            <td rowspan="3">
                            (၂)
                            </td>
                            <td rowspan="3">
                              (၃)
                            </td>
                            <td rowspan="3">
                            (၄)
                            </td>
                            <td rowspan="3">
                                (၅)
                            </td>

                            <td rowspan="3">
                              (၆)
                            </td></tr>-->
                        <?php
                        $i = 1;
                        $total = "";
                        if (!empty($salary_info)) {
                            foreach ($salary_info as $salary_infos) {
                                ?>

                                <tr>
                                    <td><?php echo $i; ?></td>
                                    <td><?php echo $salary_infos->core->member_login_name; ?></td>
                                    <td><?php echo $salary_infos->core->position; ?></td>
                                    <td><?php echo $salary_infos->salary_detail->basic_salary; ?></td>
                                    
                                   
                                    
                                    
                                    <td>
                                        <?php
                                        $total = $total + $salary_infos->salary_detail->income_tax;
                                        echo number_format($salary_infos->salary_detail->income_tax);
                                        ?>
                                    </td>
                                    <td></td>
                                  
                                </tr>
                                <?php
                                $i++;
                            }
                            ?>
                            <tr>
                                
                                
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                
                                <td><?php echo number_format($total); ?></td>
                                <td></td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
                     <div id ="taxdoc">
                    <p>  -------------------------------------  <br>
                     -------------------------------------       <br>
                     -------------------------------------      <br>
                     -------------------------------------  </p>  
                </div>
                <div id ="taxdoc">
                    <p>  လက္မွတ္  <br>
                    အမည္     <br>
                    ရာထူး    <br>
                    ဌာန/အဖြဲ႕အစည္း</p>  
                </div>
              
            </div>
        </div>
    </div>
    <div id="resign" class="navbar"></div>
</section>
