	<table>	
            <?php 
            foreach($edituser as $res){                    
            ?>
	<tr>
		<td>User ID :</td>
		<td><input type="text" value="<?= $res->member_id ?>"></td>
		<td></td>
		<td>User Name :</td>
		<td><input type="text" value="<?= $res->member_login_name ?>"></td>
	</tr>
	<tr>
		<td>Department :</td>
		<td><input type="text" value="<?= $res->member_dept_name ?>"></td>
		<td></td>
		<td>Position	:</td>
		<td><input type="text" value="<?= $res->job_title ?>"></td>
	</tr>
	<tr>
		<td>Email :</td>
		<td><input type="text" value="<?= $res->member_mail ?>"></td>
		<td></td>
		<td>Phone no</td>
		<td><input type="text" value="<?= $res->member_tel ?>"></td>
	</tr>
	<tr>
		<td>Address :</td>
		<td colspan="4"><textarea rows="5" cols="50">no(3),*****str,*****tsp, ygn</textarea></td>
	</tr>
	<tr>
		<td></td>
		<td colspan="3"><a href="#" class="button" id="displaypopup">Edit</a><a href="#" class="button" id="displaypopup">Delete</a><a href="#" class="button" id="displaypopup">Cancel</a></td>
		
	</tr>
        <?php
            }
            ?>
	</table>
	
