<form width="650px" height="300px">
	<table width="650px" height="300px">
	
	<tr>
		<td>User ID :</td>
		<td><input type="text" value="001"></td>
		<td></td>
		<td>User Name :</td>
		<td><input type="text" value="Su Zin Kyaw"></td>
	</tr>
	<tr>
		<td>Department :</td>
		<td><input type="text" value="Web development"></td>
		<td></td>
		<td>Position	:</td>
		<td><input type="text" value="developer"></td>
	</tr>
	<tr>
		<td>Email :</td>
		<td><input type="text" value="gnext.suzin@gmail.com"></td>
		<td></td>
		<td>Phone no</td>
		<td><input type="text" value="092473422"></td>
	</tr>
	<tr>
		<td>Address :</td>
		<td colspan="4"><textarea rows="5" cols="50">no(3),*****str,*****tsp, ygn</textarea></td>
	</tr>
	<tr>
		<td></td>
		<td colspan="3"><a href="#" class="button" id="displaypopup">Edit</a><a href="#" class="button" id="displaypopup">Delete</a><a href="#" class="button" id="displaypopup">Cancel</a></td>
		
	</tr>
	</table>
	
</form>