<!-- Content Header (Page header) -->
<section class="content-header" id="showuserlist">
    <h1>
        User list
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">user list</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <!--<a href="#" class="button add-big">Add User</a>-->	
        <form>
        <select class="select" data-toggle="select" name="username" id="username">
            <option>Name</option>
               <?php
                foreach ($username as $name){
                ?>
                <option value="<?php echo $name['member_login_name']; ?>" >          
                <?php echo $name['member_login_name']; ?></option>
                <?php
                }
                ?>

        </select>
            <input type="submit" onclick="return false;" class="buttonn" value="Search" id="userlistsearch">
        </form>

    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            
            <table class="listtbl">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Department</th>
                        <th>Position</th>
                        <th width="250px">Email</th>
                        <th>Phone no</th>
                        <th>Address</th>                        
                    </tr>

                </thead>
                <tbody>                    
                </tbody>
                <tfoot style="display:none;"></tfoot>                    
            </table>
    </div>
</section>   
<div id="content"></div>
<div id="edituser" style="display:none" class="navbar">
    
</div>	
<div id="confirm" title="Confirm Delete">
    
</div>





