<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Add Salary help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/addsalary.png" style="width:100%;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Search User Name"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Enter the username"); ?></pre></li>
                     </ul>
                </li>
                <li><?php echo $t->_("Enter users basic salary."); ?></li>
                <li><?php echo $t->_("Enter users Travel Fees."); ?></li>
                <li><?php echo $t->_("Enter users Overtime(per hr)."); ?></li>
                <li><span class="text-aqua"><?php echo $t->_("Deduce for SSC"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("You must checked Deduce for SSC."); ?></pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Allowance"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("You must checked Allowance."); ?></pre></li>
                     </ul>
                </li>
                <li><?php echo $t->_("sal_start_date"); ?></li>
                <li><span><?php echo $t->_("Salary_apply"); ?></span></li>
                <li><span class="text-aqua">  &nbsp;</span>
                     <ul>
                         <li><pre><?php echo $t->_("download_csv"); ?></pre></li>
                     </ul>
                </li>
                <li><span><?php echo $t->_("apply_with_csv"); ?></span></li>


            </ol>
        </div>
        <div class="col-md-12 pad">
            <div class="col-md-6 ">
                <a href="leavesetting"><< <?php echo $t->_("Leave Setting"); ?> </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="salarylists"><?php echo $t->_("Salary Lists"); ?> >></a>
            </div>
        </div>
    </div>
</div>
