<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <a href="#" ><span id="searchhelpcenter">Add Salary help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/addsalary.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li>Search User Name
                    <ul>
                         <li>Enter the username which you want to search.</li>
                     </ul>
                </li>
                <li>Enter users basic salary.</li>
                <li>Enter users Travel Fees.</li>
                <li>Enter users Overtime(per hr).</li>
                <li>Deduce for SSC
                     <ul>
                         <li>You must checked Deduce for SSC.</li>
                     </ul>
                </li>
                 <li>Allowance
                     <ul>
                         <li>You must checked Allowance.</li>
                     </ul>
                </li>
                <li>Apply button
                     <ul>
                         <li>Submit your apply form.</li>
                     </ul>
                </li>
                
             
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="calendar"><< Calendar </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="salarylists">Salary Lists  >></a>
    </div>
    </div>
</div>
</div>
