<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Allowance help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/allowance.png" style="width:100%;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">

                <li><span class="text-aqua"><?php echo $t->_("Add Button"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Admin can add Allowance"); ?></pre></li>
                     </ul>
                </li>
                <li style="list-style-image: url('<?php echo $baseUri ?>common/img/images1.png');"><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("Allowance_edit"); ?></pre></li>
                     </ul>
                </li>
            </ol>
        </div>
    <div class="col-md-12 pad " style="margin-top: 200px;">
    <div class="col-md-6 ">
        <a href="salarysetting"><< <?php echo $t->_("Salary Setting"); ?> </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="letterhead"><?php echo $t->_("Letter Head"); ?> >></a>
    </div>
    </div>
</div>
</div>
