<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
            <a href="#" ><span id="searchhelpcenter">Allowance help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/allowance.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
               
                 <li><span class="text-aqua">Add Button</span>
                     <ul>
                         <li><pre>Admin can add Allowance name and amount.</pre></li>
                     </ul>
                </li>
                <li style="list-style-image: url('../../common/img/images1.png');"><span class="text-aqua">Edit</span>
                     <ul>
                         <li><pre>Admin can edit of user informations.</pre></li>
                     </ul>
                </li>
            </ol>
        </div>
    <div class="col-md-12 top-padding ">
    <div class="col-md-6 ">
        <a href="salarysetting"><< Salary Setting  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="letterhead">Letter Head >></a>
    </div>
    </div>
</div>
</div>
