<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <img src="../../common/img/list3.png" > <a href="#" ><span id="searchhelpcenter">Apply Leave help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/applyleave.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                 <li><span class="text-aqua">Search User Box</span>
                    <ul>
                        <li><pre>Enter the username which you want to search.</pre></li>
                     </ul>
                </li>
                <li>Select Start Date </li>
                <li>Select End Date </li>
                <li><span class="text-aqua">Leave Categories</span>
                     <ul>
                         <li><pre>You must choose leave categories.</pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua">Leave Description</span>
                     <ul>
                         <li><pre>You must enter leave description.</pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua">Apply button</span>
                     <ul>
                         <li><pre>Submit your apply form.</pre></li>
                     </ul>
                </li>
                
             
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="manageuser"><< Manage User Lists </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="leavelists">Leave Lists  >></a>
    </div>
    </div>
</div>
</div>
