<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Apply Leave help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>common/img/applyleave.png" style="width:100%;height:380px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Apply_leave"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Apply_leave_name"); ?></pre></li>
                     </ul>
                </li>
                <li><?php echo $t->_("LStart Date"); ?> </li>
                <li><?php echo $t->_("LEnd Date"); ?></li>
                <li><span class="text-aqua"><?php echo $t->_("Leave Categories"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("You must choose"); ?></pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Leave Description"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("You must enter"); ?></pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Apply button"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("Submit"); ?></pre></li>
                     </ul>
                </li>
                
             
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="manageuser"><< <?php echo $t->_("Manage User"); ?> </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="leavelists"><?php echo $t->_("Leave Lists"); ?>  >></a>
    </div>
    </div>
</div>
</div>
