<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <img src="../../common/img/list3.png" > <a href="#" ><span id="searchhelpcenter">Calendar help center</span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">                
            <img src="../../common/img/calendar1.png" class="col-md-6"> 
            <img src="../../common/img/calendar2.png" class="col-md-6"> 
            <img src="../../common/img/calendar3.png" class="col-md-6">
            <img src="../../common/img/calendar4.png" class="col-md-6 pad" > 


        </div>
        <div class="col-md-6"  style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
            <ol type="1">
                <li>Create Event
                    <ul>
                        <li>To create event, you can click anywhere from the calendar date.</li>
                        <li>Then create dialog box appear,insert all fields to create event.</li>
                    </ul>
                </li>
                <li>Show Selected Event
                    <ul>
                        <li>To see someone event schedule, check member name under <span class="text-aqua">User Event Enable</span> box.
                            Then click <span class="text-aqua">Show Event </span>Button</li>
                    </ul>
                </li>
                <li>Member Event Schedule
                    <ul>
                        <li>
                            <pre>Edit   : Can edit schedule by dragging,
       resizing and click event .                                     Delete : To delete event,click the event that you want 
       to delete , edit  dialog box is appeared ,click
       delete button from under dialog form.
                            </pre>
                        </li>
                    </ul>
                </li>
            </ol>           
            
            <li class="dateimg" style="list-style: none;padding-left: 5%;">
                <span class="text-aqua">Add member</span> to see their event details ,click add button and type in dialog box name that you want to add username
            </li>
            <li class="dateminusimg" style="list-style: none;padding:0 5%;">            
                <span class="text-aqua">Remove member</span> from event permission , first check the member name box that you want to remove ,after that click minus button.
            </li>
            
        </div>
        <div class="col-md-12 top-padding">
            <div class="col-md-6 ">
                <a href="leavesetting"><< Leave Setting </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="addsalary">Add Salary  >></a>
            </div>
        </div>
    </div>
</div>
