<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Calendar help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">                
            <img src="../../common/img/calendar1.png" class="col-md-6"> 
            <img src="../../common/img/calendar2.png" class="col-md-6">
            <img src="../../common/img/calendar3.png" class="col-md-6">
            <img src="../../common/img/calendar4.png" class="col-md-6 pad" >
        </div>
        <div class="col-md-6"  style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
            <ol type="1">
                <li><?php echo $t->_("Create Event"); ?>
                    <ul>
                        <li><?php echo $t->_("To create event"); ?></li>
                        <li><?php echo $t->_("Then create dialog box"); ?></li>
                    </ul>
                </li>
                <li><?php echo $t->_("Show Selected Event"); ?>
                    <ul>
                        <li><?php echo $t->_("To see someone"); ?><span class="text-aqua"><?php echo $t->_("User Event Enable"); ?></span> <?php echo $t->_("box. Then click "); ?><span class="text-aqua"><?php echo $t->_("Show Event"); ?></span><?php echo $t->_("Button"); ?></li>
                    </ul>
                </li>
                <li><?php echo $t->_("Member Event Schedule"); ?>
                    <ul>
                        <li>
                            <pre><?php echo $t->_("Edit and Delete"); ?>
                            </pre>
                        </li>
                    </ul>
                </li>
            </ol>           

            <li class="dateimg" style="list-style: none;padding-left: 5%;">
                <span class="text-aqua"><?php echo $t->_("Add member"); ?></span> <?php echo $t->_("to see their event details"); ?>
            </li>
            <li class="dateminusimg" style="list-style: none;padding:0 5%;">            
                <span class="text-aqua"><?php echo $t->_("Remove member"); ?></span> <?php echo $t->_("from event permission"); ?>
            </li>           
        </div>
        <div class="col-md-12 clearfix pad">
                <div class="col-md-6 col-xs-6">
                    <a href="leavesetting"><< <?php echo $t->_("Leave Setting"); ?> </a>
                </div>
                <div class=" col-md-6 text-right" >
                    <a href="addsalary"><?php echo $t->_("Add Salary"); ?>  >></a>
                </div>            
        </div>
    </div>
</div>
