<div class="row-fluid">
    <div class="col-md-10 " id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"> <?php echo $t->_("Dashboard_hc"); ?></span></a>
            </li>
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri?>common/img/dashboard1.png" style="width:100%;height:380px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Manage User"); ?></span>
                    <ul>
                        <li><?php echo $t->_("Click Manage Users"); ?></li>
                    </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Attendance List"); ?></span>
                    <ul>
                        <li><?php echo $t->_("Click Attendance Link"); ?></li>
                    </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Leave Days"); ?></span>
                    <ul>
                        <li><?php echo $t->_("Click Leave Days Link"); ?></li>
                    </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Salary(Only For Admin)"); ?></span>
                    <ul>
                        <li><?php echo $t->_("Click Salary Link"); ?></li>
                    </ul>
                </li>
                <li><?php echo $t->_("If you late"); ?></li>
                <li><span class="text-aqua"><?php echo $t->_("Check In Button"); ?></span>
                    <ul>
                        <li><?php echo $t->_("It is describe"); ?></li>
                    </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Check Out Button"); ?></span>
                    <ul>
                        <li><?php echo $t->_("It is describe as"); ?></li>
                    </ul>
                </li>
                <li>&nbsp;
                    <ul>
                    <li><pre><?php echo $t->_("Status of"); ?></pre></li>
                    </ul>
                </li>
                <li>&nbsp;
                    <ul>
                            <li><pre><?php echo $t->_("Showing"); ?></pre></li>
                    </ul>
                </li>
            </ol>
        </div>
        <div class="col-md-12 span12">
            <div class="col-md-6 ">
                <a href="searchHelp"><< <?php echo $t->_("Help Center"); ?>  </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="todayattlist"><?php echo $t->_("Today Attendance List"); ?>  >></a>
            </div>
        </div>
    </div>

</div>
