<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <img src="../../common/img/list1.png" > <a href="#" ><span id="searchhelpcenter">Dashboard help center</span></a>
            </li>
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="../../common/img/dashboard1.png" style="width:100%;height:380px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua">Manage User</span>
                    <ul>
                        <li>Click Manage Users Link Icon,You can Manage,edit and modify User Lists.</li>
                    </ul>
                </li>
                <li><span class="text-aqua">Attendance List</span>
                    <ul>
                        <li>Click Attendance Link Icon, You can review your Today and Monthly Attendance Lists.</li>
                    </ul>
                </li>
                <li><span class="text-aqua">Leave Days</span>
                    <ul>
                        <li>Click Leave Days Link Icon, You can do your Apply Leave Day and can review your Leave Lists and Admin can  change Leave Setting.</li>
                    </ul>
                </li>
                <li><span class="text-aqua">Salary(Only For Admin)</span>
                    <ul>
                        <li>Click Salary Link Icon,Admin can calculate salary of all SALTS members.</li>
                    </ul>
                </li>
                <li>If you late,you must write your late reason by click checkbox.</li>
                <li><span class="text-aqua">Check In Button</span>
                    <ul>
                        <li>It is describe as a your attending office today,so you must check in at the time you arrive at office.</li>
                    </ul>
                </li>
                <li><span class="text-aqua">Check Out Button</span>
                    <ul>
                        <li>It is describe as a your finished woring time today,so you must check out before you leave the office.</li>
                    </ul>
                </li>
                <li><li><pre>Status of most not leave taken member and takes leave member</pre>
                        </li>
                </li>
                <li><li><pre>Showing the last registered member names</pre></li>
                </li>
            </ol>
        </div>
        <div class="col-md-12 span12 pad">
            <div class="col-md-6 ">
                <a href="searchHelp"><< Help Center  </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="todayattlist">Today Attendance Lists  >></a>
            </div>
        </div>
    </div>

</div>
