<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
            <img src="../../common/img/list1.png" > <a href="#" ><span id="searchhelpcenter">Dashboard help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/dashboard1.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li>Manage User
                    <ul>
                         <li>Click Manage Users Link Icon,You can Manage,edit and modify User Lists.</li>
                     </ul>
                </li>
                <li>Attendance List
                    <ul>
                         <li>Click Attendance Link Icon, You can review your Today and Monthly Attendance Lists.</li>
                     </ul>
                </li>
                <li>Leave Days
                     <ul>
                         <li>Click Leave Days Link Icon, You can do your Apply Leave Day and can review your Leave Lists and Admin can  change Leave Setting.</li>
                     </ul>
                </li>
                 <li>Salary(Only For Admin)
                        <ul>
                            <li>Click Salary Link Icon,Admin can calculate salary of all SALTS members.</li>
                         </ul>
                 </li>
                 <li>If you late,you must write your late reason by click checkbox.</li>
                 <li>Check In Button
                        <ul>
                            <li>It is describe as a your attending office today,so you must check in at the time you arrive at office.</li>
                         </ul>
                 </li>
                  <li>Check Out Button
                        <ul>
                            <li>It is describe as a your finished woring time today,so you must check out before you leave the office.</li>
                         </ul>
                 </li>
                 <li>Status of most not leave taken member and takes leave member</li>
                 <li>Showing the last registered member names</li>
            </ol>
        </div>
    <div class="col-md-12">
    <div class="col-md-6 ">
        <a href="searchHelp"><< Help Center  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="todayattlist">Today Attendance Lists  >></a>
    </div>
    </div>
</div>
    
</div>
