<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" > <span id="searchhelpcenter"><?php echo $t->_("Leave Setting help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>help/leavesetting.png" style="width:100%;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Edit Leave"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Admin can edit"); ?></pre></li>
                         </ul>
                 </li>
                 <li><span class="text-aqua"><?php echo $t->_("Leave Categories"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Admin can Add"); ?></pre></li>
                     </ul>
                </li>
                <li style="list-style-image: url('<?php echo $baseUri ?>common/img/delete2.png');"><span class="text-aqua"><?php echo $t->_("Delete"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("Admin can delete"); ?></pre></li>
                     </ul>
                </li>
                
            </ol>
        </div>
    <div class="col-md-12 pad">
    <div class="col-md-6 ">
        <a href="leavelists"><< <?php echo $t->_("Leave Lists"); ?> </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="calendar"><?php echo $t->_("Calendar"); ?> >></a>
    </div>
    </div>
</div>
</div>
