<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <img src="../../common/img/list2.png" ><a href="#" > <span id="searchhelpcenter">Leave Setting help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/leavesetting.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li>Edit Leave Setting(Admin)
                        <ul>
                            <li>Admin can edit Maximun leavedays allowed and Percentage of On Basic Salary.</li>
                         </ul>
                 </li>
                <li>Leave Categories
                    <ul>
                         <li>Admin can Add New Leave Categories. </li>
                     </ul>
                </li>
                 <li style="list-style-image: url('../../common/img/delete2.png');">Delete
                     <ul>
                         <li style="list-style: none;">Admin can delete of Leave Type.</li>
                     </ul>
                </li>
                
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="leavelists"><< Leave Lists </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="calendar">Calendar >></a>
    </div>
    </div>
</div>
</div>
