<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <a href="#" > <span id="searchhelpcenter"><?php echo $t->_("Leave Lists help center"); ?></span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="<?php echo $baseUri?>common/img/leavelists.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                 <li><span class="text-aqua"><?php echo $t->_("Leave Type"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("You can choose your Leave Type."); ?></pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Month"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("You can choose Month."); ?></pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Search Box"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Enter"); ?></pre></li>
                     </ul>
                </li>
                <li><?php echo $t->_("Then select the wanted username"); ?>                   
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Export"); ?>   </span>
                     <ul>
                         <li><pre><?php echo $t->_("This will output"); ?></pre></li>
                     </ul>
                </li>
                
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="applyleave"><< <?php echo $t->_("Apply Leave"); ?>  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="leavesetting"><?php echo $t->_("Leave Setting"); ?> >></a>
    </div>
    </div>
</div>
</div>
