<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <img src="../../common/img/list2.png" ><a href="#" > <span id="searchhelpcenter">Leave Setting help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/leavesetting.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                 <li><span class="text-aqua">Edit Leave Setting(Admin)</span>
                        <ul>
                            <li><pre>Admin can edit Maximun leavedays allowed and Percentage of On Basic Salary.</pre></li>
                         </ul>
                 </li>
                 <li><span class="text-aqua">Leave Categories</span>
                    <ul>
                        <li><pre>Admin can Add New Leave Categories.</pre></li>
                     </ul>
                </li>
                <li style="list-style-image: url('../../common/img/delete2.png');"><span class="text-aqua">Delete</span>
                     <ul>
                         <li><pre>Admin can delete of Leave Type.</pre></li>
                     </ul>
                </li>
                
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="leavelists"><< Leave Lists </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="calendar">Calendar >></a>
    </div>
    </div>
</div>
</div>
