<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" > <span id="searchhelpcenter"><?php echo $t->_("Leave Day Left"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/leavedayleft.png" class="img-responsive"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Leave Day Carry"); ?></span>
                    <ul>
                        <li><?php echo $t->_("You can known your Leave Day Carry"); ?></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Total Leave Days"); ?></span>
                    <ul>
                        <li><?php echo $t->_("You can known your Total Leave Day"); ?></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Leave DayLeft"); ?></span>
                    <ul>
                        <li><?php echo $t->_("You can known your Leave Day Left"); ?></li>
                     </ul>
                </li>                
                
            </ol>
        </div>
    <div class="col-md-12 pad" style="margin-top: 100px;">
    <div class="col-md-6 ">
        <a href="leavesetting"><< <?php echo $t->_("Leave Setting"); ?>  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="addsalary"><?php echo $t->_("Add Salary"); ?> >></a>
    </div>
    </div>
</div>
</div>
