<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter">Letter Head help center</span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="../../common/img/letterhead.png" style="width:100%;height:380px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li>Edit
                    <ul>
                        <li>To change the company name,address ,phone number and logo on the left side of the page.Then you can click <img src="../../common/img/save.png" > button</li>
                    </ul>
                </li> 
                <li>Export
                    <ul>
                        <li>This will output the data of display table as csv.</li>
                    </ul>
                </li>

            </ol>
        </div>
        <div class="col-md-12">
            <div class="col-md-6 ">
                <a href="allowance"><< Allowance  </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="ssbdocument">SSB Document  >></a>
            </div>
        </div>
    </div>

</div>
