<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Letter Head help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>help/letterhead.png" style="width:100%;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("To change"); ?><img src="<?php echo $baseUri ?>common/img/save.png" > <?php echo $t->_("save_button"); ?></pre></li>
                    </ul>
                </li> 
                <li><span class="text-aqua"><?php echo $t->_("Export"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("This will output"); ?></pre></li>
                    </ul>
                </li>

            </ol>
        </div>
        <div class="col-md-12 span12 top-padding">
            <div class="col-md-6 ">
                <a href="allowance"><< <?php echo $t->_("Allowance"); ?>  </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="ssbdocument"><?php echo $t->_("SSB & Tax Document"); ?>  >></a>
            </div>
        </div>
    </div>

</div>
