<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <img src="../../common/img/list3.png" > <a href="#" ><span id="searchhelpcenter">Manage User help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/manageuser.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li>Search User Box
                    <ul>
                         <li>Enter the username which you want to search.</li>
                     </ul>
                </li>
                <li>Then select the wanted username from dropdown list ,after that click search button                   
                </li>
                <li>Add User(For Admin)
                     <ul>
                         <li>Admin can create new SALTS member.</li>
                     </ul>
                </li>
                <li style="list-style-image: url('../../common/img/images1.png');">Edit
                     <ul>
                         <li style="list-style: none;">Admin can edit of user informations.</li>
                     </ul>
                </li>
             
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="monthlyattlist"><< Monthly Attendance Lists </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="applyleave">Apply Leave  >></a>
    </div>
    </div>
</div>
</div>
