<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Manage"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/manageuser.png" class="img-responsive"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Search Box"); ?></span>
                    <ul>
                        <li><?php echo $t->_("Enter_name"); ?></li>
                     </ul>
                </li>
                <li><?php echo $t->_("Then select the wanted username"); ?>                 
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Add User"); ?></span>
                     <ul>
                         <li><?php echo $t->_("Admin can create"); ?></li>
                     </ul>
                </li>
                <li style="list-style-image: url('<?php echo $baseUri ?>common/img/images1.png');"><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>
                     <ul>
                         <li><?php echo $t->_("Admin can edit of user informations."); ?></li>
                     </ul>
                </li>
             
            </ol>
        </div>
    <div class="col-md-12 pad" style="margin-top: 50px;">
    <div class="col-md-6 ">
        <a href="monthlyattchart"><< <?php echo $t->_("Monthly Attendance Chart"); ?> </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="applyleave"><?php echo $t->_("Apply Leave"); ?>  >></a>
    </div>
    </div>
</div>
</div>
