<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
           <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Manage"); ?></span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="<?php echo $baseUri?>common/img/manageuser.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                 <li><span class="text-aqua"><?php echo $t->_("Search"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Enter the username"); ?></pre></li>
                     </ul>
                </li>
                <li><?php echo $t->_("Then select the wanted username"); ?>                 
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Add User"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("Admin can create"); ?></pre></li>
                     </ul>
                </li>
                <li style="list-style-image: url('<?php echo $baseUri?>common/img/images1.png');"><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("Admin can edit of user informations."); ?></pre></li>
                     </ul>
                </li>
             
            </ol>
        </div>
    <div class="col-md-12 pad">
    <div class="col-md-6 ">
        <a href="monthlyattlist"><< <?php echo $t->_("Monthly Attendance List"); ?> </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="applyleave"><?php echo $t->_("Apply Leave"); ?>  >></a>
    </div>
    </div>
</div>
</div>
