<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Monthly"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/monthlyattlist.png" class="img-responsive"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><?php echo $t->_("Start Date"); ?></li>
                <li><?php echo $t->_("End Date"); ?></li>
                <li><span class="text-aqua"><?php echo $t->_("Search Box"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Enter"); ?></pre></li>
                     </ul>
                </li>
                <li><?php echo $t->_("Then select the wanted username"); ?>            
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Export"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("This will output"); ?></pre></li>
                     </ul>
                </li>
                
             
            </ol>
        </div>
    <div class="col-md-12 pad" style="margin-top: 50px;">
    <div class="col-md-6 ">
        <a href="todayattlist"><< <?php echo $t->_("Today Attendance List"); ?> </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="monthlyattchart"><?php echo $t->_("Monthly Attendance Chart"); ?> >></a>
    </div>
    </div>
</div>
</div>
