<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <img src="../../common/img/list2.png" ><a href="#" ><span id="searchhelpcenter">Monthly Attendance List help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/monthlyattlist.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                 <li>Select Search Start Date</li>
                 <li>Select Search End Date</li>
                 <li><span class="text-aqua">Search User Box</span>
                    <ul>
                        <li><pre>Enter the username which you want to search.</pre></li>
                     </ul>
                </li>
                <li>Then select the wanted username from dropdown list ,after that click search button                   
                </li>
                <li><span class="text-aqua">Export</span>
                     <ul>
                         <li><pre>This will output the data of display table as csv.</pre></li>
                     </ul>
                </li>
                
             
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="todayattlist"><< Today Attendance Lists </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="manageuser">Manage User  >></a>
    </div>
    </div>
</div>
</div>
