<div class="row-fluid">
    <div class="col-md-10" id="showhelp">

        <div class="col-md-12">        
            <div id="myCarousel" class="carousel slide col-md-12" data-ride="carousel">             


                <!-- Wrapper for slides -->
                <div class="carousel-inner span12" role="listbox">
                    <div class="item active l0">
                        <ol id="helpcenter">
                            <li>
                                <span id="searchhelpcenter">(1) Monthly Salary Lists help center</span>
                            </li>        
                        </ol>
                        <hr>
                        <img src="../../common/img/monthlysallists.png" alt="Chania" class="col-md-6 offset1" style="width:800px;height: 200px;">
                        <div class="col-md-12">
                            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                                <li><span class="text-aqua">Calculate Salary</span>
                                    <ul>
                                        <li><pre>Admin can calculate salary for this month.</pre></li>
                                    </ul>
                                </li>

                                <li><span class="text-aqua">Export</span>
                                    <ul>
                                        <li><pre>This will output the data of display table as csv.</pre></li>
                                    </ul>
                                </li>
                                <li><span class="text-aqua">Month/Year</span>
                                    <ul>
                                        <li><pre>Show details information,click Month/Year field date.</pre></li>
                                    </ul>
                                </li>


                            </ol>
                        </div>

                    </div>

                    <div class="item l1">
                        <ol id="helpcenter" >
                            <li>
                                <span id="searchhelpcenter">(2) Salary Detail Help Center</span></a>
                            </li>        
                        </ol>
                        <hr>
                        <img src="../../common/img/monthlysal_detail.png" alt="Chania" class="col-md-6 offset1" style="width:800px;height: 200px;">
                        <div class="col-md-12">
                            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                                <li><span class="text-aqua">Search User Salary</span>
                                    <ul>
                                        <li><pre>To search salary detail with <span class="text-bold text-blue">username,department,position and salary rate</span>.</pre></li>
                                    </ul>
                                </li>

                                <li><span class="text-aqua">Print</span>
                                    <ul>
                                        <li><pre>First check the User names to Print.Then click <img src="../../common/img/print7.png">.</pre></li>
                                    </ul>
                                </li>
                                <li><span class="text-aqua">Details Salary</span>
                                    <ul>
                                        <li><pre>To see detail salary of user , edit and assign.Check the username first then click <img src="../../common/img/detail2.png"> button.</pre></li>
                                    </ul>
                                </li>


                            </ol>
                        </div>
                    </div>

                    <div class="item l2">
                           <ol id="helpcenter" >
                            <li>
                                <span id="searchhelpcenter">(3) Salary Report Help Center</span></a>
                            </li>        
                        </ol>
                        <hr>
                        <img src="../../common/img/monthlysal_report.png" alt="Flower" class="col-md-6 offset1" style="width:800px;height: 200px;">
                        <div class="col-md-12">
                            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                                <li><span class="text-aqua">Edit</span>
                                    <ul>
                                        <li><pre>To enable edit, click edit button first then modify data.</pre></li>
                                    </ul>
                                </li>

                                <li><span class="text-aqua">Save</span>
                                    <ul>
                                        <li><pre>Save modified salary report data.</pre></li>
                                    </ul>
                                </li>
                                <li><span class="text-aqua">Resign</span>
                                    <ul>
                                        <li><pre>To resign modified date</pre></li>
                                    </ul>
                                </li>
                            </ol>
                        </div>
                    </div>                                
                </div>

                <!-- Left and right controls -->
                <div class="col-md-12 span12">

                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span  aria-hidden="true"> << </span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <ol class="carousel-indicators linknavi">
                        <li data-target="#myCarousel" data-slide-to="0" class="btn-color"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>                        
                    </ol>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span  aria-hidden="true"> >> </span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-12 span12 pad">
            <div class="col-sm-6">
                <a href="salarylists"><< Salary Lists </a>
            </div>
            <div class="col-sm-6 text-right">
                <a href="salarysetting">Salary Setting  >></a>
            </div>
        </div>
    </div>
</div>
