<div class="row-fluid">
    <div class="col-md-10" id="showhelp">

        <div class="col-md-12">        
            <div id="myCarousel" class="carousel slide col-md-12" data-ride="carousel">             


                <!-- Wrapper for slides -->
                <div class="carousel-inner span12" role="listbox">
                    <div class="item active l0">
                        <ol id="helpcenter">
                            <li>
                                <span id="searchhelpcenter"><?php echo $t->_("Monthly Salary Lists help center"); ?></span>
                            </li>        
                        </ol>
                        <hr>
                        <img src="../../common/img/monthlysallists.png" alt="Chania" class="col-md-6 offset1" style="width:800px;height: 200px;">
                        <div class="col-md-12">
                            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                                <li><span class="text-aqua"><?php echo $t->_("Calculate Salary"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("Admin can calculate"); ?></pre></li>
                                    </ul>
                                </li>

                                <li><span class="text-aqua"><?php echo $t->_("Export"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("This will output"); ?></pre></li>
                                    </ul>
                                </li>
                                <li><span class="text-aqua"><?php echo $t->_("Month/Year"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("Show details"); ?></pre></li>
                                    </ul>
                                </li>


                            </ol>
                        </div>

                    </div>

                    <div class="item l1">
                        <ol id="helpcenter" >
                            <li>
                                <span id="searchhelpcenter"><?php echo $t->_("Salary Detail Help Center"); ?></span></a>
                            </li>        
                        </ol>
                        <hr>
                        <img src="../../common/img/monthlysal_detail.png" alt="Chania" class="col-md-6 offset1" style="width:800px;height: 200px;">
                        <div class="col-md-12">
                            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                                <li><span class="text-aqua"><?php echo $t->_("Search User Salary"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("To search salary"); ?><span class="text-bold text-blue"><?php echo $t->_("username"); ?></span>.</pre></li>
                                    </ul>
                                </li>

                                <li><span class="text-aqua"><?php echo $t->_("Print"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("First check"); ?><img src="../../common/img/print7.png">.</pre></li>
                                    </ul>
                                </li>
                                <li><span class="text-aqua"><?php echo $t->_("Details Salary"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("To see detail"); ?><img src="../../common/img/detail2.png"> <?php echo $t->_("button"); ?></pre></li>
                                    </ul>
                                </li>


                            </ol>
                        </div>
                    </div>

                    <div class="item l2">
                           <ol id="helpcenter" >
                            <li>
                                <span id="searchhelpcenter"><?php echo $t->_("Salary Report Help Center"); ?></span></a>
                            </li>        
                        </ol>
                        <hr>
                        <img src="../../common/img/monthlysal_report.png" alt="Flower" class="col-md-6 offset1" style="width:800px;height: 200px;">
                        <div class="col-md-12">
                            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                                <li><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("To enable edit"); ?></pre></li>
                                    </ul>
                                </li>

                                <li><span class="text-aqua"><?php echo $t->_("Save"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("Save modified"); ?></pre></li>
                                    </ul>
                                </li>
                                <li><span class="text-aqua"><?php echo $t->_("Resign"); ?></span>
                                    <ul>
                                        <li><pre><?php echo $t->_("To resign"); ?></pre></li>
                                    </ul>
                                </li>
                            </ol>
                        </div>
                    </div>                                
                </div>

                <!-- Left and right controls -->
                <div class="col-md-12 span12">

                    <a class="left carousel-control margin" href="#myCarousel" role="button" data-slide="prev">
                        <span  aria-hidden="true"> << </span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <ol class="carousel-indicators linknavi">
                        <li data-target="#myCarousel" data-slide-to="0" class="btn-color"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>                        
                    </ol>
                    <a class="right carousel-control margin" href="#myCarousel" role="button" data-slide="next">
                        <span  aria-hidden="true"> >> </span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-12 span12 pad">
            <div class="col-sm-6">
                <a href="salarylists"><< <?php echo $t->_("Salary Lists"); ?> </a>
            </div>
            <div class="col-sm-6 text-right">
                <a href="salarysetting"><?php echo $t->_("Salary Setting"); ?>  >></a>
            </div>
        </div>
    </div>
</div>
