<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Monthly Attendance Chart"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/monthattchart.png" style="width:100%;height:380px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Monthly Attendance Chart"); ?></span>
                    <ul>
                        <li><?php echo $t->_("Admin can show"); ?></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Colors"); ?></span>
                    <ul class="list-unstyled">
                        <li>
                            <ul>
                                <li><?php echo $t->_("Green"); ?>
                                    <ul><?php echo $t->_("att_person"); ?></ul>
                                </li>
                                <li><?php echo $t->_("Yellow"); ?>
                                    <ul><?php echo $t->_("absent_leave_person"); ?></ul>
                                </li>
                                <li><?php echo $t->_("Red"); ?>
                                    <ul><?php echo $t->_("absent_noleave_person"); ?></ul>
                                </li>
                                <li><?php echo $t->_("Pink"); ?>
                                    <ul><?php echo $t->_("Half Day"); ?></ul>
                                </li>
                            </ul>
                        </li>
                     </ul>
                </li>
                
                
             
            </ol>
        </div>
    <div class="col-md-12 pad" style="margin-top: 50px;">
    <div class="col-md-6 ">
        <a href="monthlyattlist"><< <?php echo $t->_("Monthly Attendance List"); ?> </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="manageuser"><?php echo $t->_("Manage User"); ?> >></a>
    </div>
    </div>
</div>
</div>
