<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Salary List help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/salarylists.png"  class="img-responsive"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Search Box"); ?></span>
                    <ul>
                        <li><?php echo $t->_("Enter"); ?></li>
                     </ul>
                </li>
                <li><?php echo $t->_("You can select"); ?></li>
                <li><?php echo $t->_("Then select the wanted username"); ?></li>
                <li><span class="text-aqua"><?php echo $t->_("Export"); ?></span>
                    <ul>
                        <li><?php echo $t->_("This will output"); ?></li>
                     </ul>
                </li>
                <li style="list-style-image: url('<?php echo $baseUri ?>common/img/images1.png');"><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>
                     <ul>
                         <li><?php echo $t->_("Admin can edit of user informations."); ?></li>
                     </ul>
                </li>
            </ol>
        </div>
    <div class="col-md-12 pad" style="margin-top: 50px;">
    <div class="col-md-6 col-xs-6">
        <a href="addsalary"><< <?php echo $t->_("Add Salary"); ?>  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="monthlysallists"><?php echo $t->_("Monthly Salary Lists"); ?>  >></a>
    </div>
    </div>
</div>
</div>
