<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Salary Setting help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/salarysetting.png"  class="img-responsive"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">

                <li><span class="text-aqua"><?php echo $t->_("Tax Setting"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("To edit Tax"); ?></pre></li>
                   
                     <li style="list-style-image: url('<?php echo $baseUri ?>common/img/images1.png');"><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>    
                    <ul>
                            <li><pre><?php echo $t->_("Tax_edit"); ?></pre></li>
                    </ul>
                 </li>
                    </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Deduce Setting"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Admin can edit deduce"); ?></pre></li> 
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("New Deduction"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Admin can add new Deduction Type."); ?></pre></li> 
                     </ul>
                </li>
<!--                <li style="list-style-image: url('<?php echo $baseUri ?>common/img/images1.png');"><span class="text-aqua"><?php echo $t->_("Edit"); ?></span>    
                    <ul>
                            <li><pre><?php echo $t->_("Admin can edit of user informations."); ?></pre></li>
                    </ul>
                 </li>-->
            </ol>
        </div>
    <div class="col-md-12 pad" style="margin-top: 50px;">
    <div class="col-md-6 ">
        <a href="monthlysallists"><< <?php echo $t->_("Monthly Salary Lists"); ?>  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="allowance"><?php echo $t->_("Allowance"); ?>  >></a>
    </div>
    </div>
</div>
</div>
