<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
            <a href="#" ><span id="searchhelpcenter">Salary List help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/salarylists.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
               
                <li>Export
                     <ul>
                         <li>This will output the data of display table as csv.</li>
                     </ul>
                </li>
                 <li style="list-style-image: url('../../common/img/images1.png');">Edit
                     <ul>
                         <li style="list-style: none;">Admin can edit of user informations.</li>
                     </ul>
                </li>
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="addsalary"><< Add Salary  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="monthlysallist">Monthly Salary Lists  >></a>
    </div>
    </div>
</div>
</div>
