<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
            <a href="#" ><span id="searchhelpcenter">Salary Setting help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/salarysetting.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
               
                <li>Tax Setting
                     <ul>
                       <li>To edit Tax data by adminstrator
                       </li>
                     </ul>
                </li>
                <li>Deduce Setting
                    <ul>
                         <li>Admin can edit deduce amount of salary.</li> 
                     </ul>
                </li>
                <li>New Deduction
                    <ul>
                         <li>Admin can add new Deduction Type.</li> 
                     </ul>
                </li>
                 <li style="list-style-image: url('../../common/img/images1.png');">Edit                        
                           <li style="list-style: none;">Admin can edit of user informations.</li>   
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="monthlyattlist"><< Monthly Salary Lists  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="allowance">Allowance  >></a>
    </div>
    </div>
</div>
</div>
