<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
            <a href="#" ><span id="searchhelpcenter">Salary Setting help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/salarysetting.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
               
                 <li><span class="text-aqua">Tax Setting</span>
                     <ul>
                         <li><pre>To edit Tax data by adminstrator</pre>
                       </li>
                     </ul>
                </li>
                <li><span class="text-aqua">Deduce Setting</span>
                    <ul>
                        <li><pre>Admin can edit deduce amount of salary.</pre></li> 
                     </ul>
                </li>
                <li><span class="text-aqua">New Deduction</span>
                    <ul>
                        <li><pre>Admin can add new Deduction Type.</pre></li> 
                     </ul>
                </li>
                <li style="list-style-image: url('../../common/img/images1.png');"><span class="text-aqua">Edit</span>                
                <li><pre>Admin can edit of user informations.</pre></li>
            </ol>
        </div>
    <div class="col-md-12 span12 top-padding">
    <div class="col-md-6 ">
        <a href="monthlyattlist"><< Monthly Salary Lists  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="allowance">Allowance  >></a>
    </div>
    </div>
</div>
</div>
