<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Welcome"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-12 text-capitalize ">        

            <div class=" text-uppercase text-bold btn-app">
                <?php echo $t->_("Thanks"); ?><br><span class="text-light-blue "><?php echo $t->_("Salary,Tax"); ?></span> <?php echo $t->_("etc"); ?>
            </div>
            <div class="col-md-12 thumbnail top-padding">
                <p class="text-bold title"><?php echo $t->_("Explanation"); ?></p>
                <div class="col-md-12 btn-box-tool left-div-style-box">
                    <div class="col-sm-1">
                        <img src="<?php echo $baseUri ?>common/img/noti.png" >
                    </div>
                    <div class="col-sm-2"><?php echo $t->_("Notification"); ?></div>
                    <div class="col-sm-9"> <?php echo $t->_("Admin can"); ?></div>
                </div>
                <div class="col-md-12 btn-box-tool left-div-style-box">
                    <div class="col-sm-1">
                        <img src="<?php echo $baseUri ?>common/img/english.png" width='25px' > <img src="../../common/img/japan.jpg" width='25px'> <img src="../../common/img/myanmar.jpg" width='25px'>
                    </div>
                    <div class="col-sm-2"><?php echo $t->_("Change"); ?></div>
                    <div class="col-sm-9">
                        <?php echo $t->_("Change Language"); ?>
                    </div>
                </div>
                <div class="col-md-12 btn-box-tool left-div-style-box">
                    <div class="col-sm-1">
                        <img src="<?php echo $baseUri ?>common/img/setting.png" width='50px'>
                    </div>
                    <div class="col-sm-2"><?php echo $t->_("Setting"); ?></div>
                    <div class="col-sm-9"><?php echo $t->_("Right side"); ?></div>
                </div>
            </div>
            <div class="col-md-12 linkhover btn-link text-center" style="margin-top: 50px;">         
                <?php echo $t->_("To know"); ?>
            </div>

        </div>
    </div>
</div>
