<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
            <a href="#" ><span id="searchhelpcenter">Welcome to the search help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-12 text-capitalize ">        
<!--        <img src="../../common/img/dashboard1.png" style="width:100%;height:380px;"> -->
        <div class=" text-uppercase text-bold btn-app">
            Thanks for using SALTS Application.This application is the management system for offices such as <br><span class="text-light-blue ">Salary,Tax,Attendance Member List</span> ....etc.
        </div>
        <div class="col-md-12 thumbnail top-padding">
            <p class="text-bold title">Explanation</p>
            <div class="col-md-12 btn-box-tool left-div-style-box">
                <div class="col-sm-1">
                        <img src="../../common/img/noti.png" >
                </div>
                <div class="col-sm-2">Notification</div>
                <div class="col-sm-9"> Admin can Accept and Reject with users apply  leave.Users can known of Admin Accept and Reject.</div>
            </div>
            <div class="col-md-12 btn-box-tool left-div-style-box">
                <div class="col-sm-1">
                    <img src="../../common/img/english.png" width='25px' > <img src="../../common/img/japan.jpg" width='25px'> <img src="../../common/img/myanmar.jpg" width='25px'>
                </div>
                <div class="col-sm-2">Change Language</div>
                <div class="col-sm-9">
                       Change Language with Japan, English and Myanmar.
                </div>
        </div>
            <div class="col-md-12 btn-box-tool left-div-style-box">
                <div class="col-sm-1">
                        <img src="../../common/img/setting.png" width='50px'>
                </div>
                <div class="col-sm-2">Setting</div>
                <div class="col-sm-9">Right side of the page ,click user profile then click left setting button.</div>
            </div>
        </div>
        <div class="col-md-12 linkhover btn-link text-center" style="margin-top: 50px;">         
                To know how it work of modules,you can learn from left side link documentation.
        </div>
        
    </div>
</div>
</div>
