<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("SSB & Tax Document help center"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="../../common/img/ssbdocument.png" style="width:100%;height:180px;"> <br><br>
            <img src="../../common/img/taxdocument.png" style="width:100%;height:180px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><?php echo $t->_("SSB and Tax Document Printing"); ?>                   
                </li> 
                <li style="list-style-image: url('../../common/img/print7.png');"><span class="text-aqua"><?php echo $t->_("Print"); ?> </span>
                    <ul>
                        <li style="list-style: none;"><?php echo $t->_("Print SSB & Tax"); ?></li>
                    </ul>
                </li>

            </ol>
        </div>
        <div class="col-md-12 span12 top-padding">
            <div class="col-md-6 ">
                <a href="letterhead"><< <?php echo $t->_("Letter Head"); ?>  </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="searchHelp"><?php echo $t->_("Help Center"); ?>  >></a>
            </div>
        </div>
    </div>

</div>
