<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter">SSB & Tax Document help center</span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="../../common/img/ssbdocument.png" style="width:100%;height:380px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li>SSB and Tax Document Printing                    
                </li> 
                <li>Print
                    <ul>
                        <li>Print SSB & Tax Document details table.</li>
                    </ul>
                </li>

            </ol>
        </div>
        <div class="col-md-12 span12 top-padding">
            <div class="col-md-6 ">
                <a href="letterhead"><< Letter Head  </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="searchHelp">Home  >></a>
            </div>
        </div>
    </div>

</div>
