<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("SSB Resign Form"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>/apps/help/img/ssbresignform.PNG"  class="img-responsive"> <br><br>
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("SSB Resign Form"); ?></span></li> 
                <li><span class="text-aqua"><?php echo $t->_("Export"); ?> </span>
                    <ul>
                        <li style="list-style: none;"><?php echo $t->_("exportssbresignform"); ?></li>
                    </ul>
                </li>
            </ol>
        </div>
        <div class="col-md-12 pad" style="margin-top: 50px;">
            <div class="col-md-6 ">
                <a href="ssbapplyform"><< <?php echo $t->_("SSB Apply Form"); ?>  </a>
            </div>
            <div class="col-md-6 text-right">
                <a href="searchHelp"><?php echo $t->_("searchHelp"); ?>  >></a>
            </div>
        </div>
    </div>

</div>
