<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
        <ul id="helpcenter">
            <li>
                <a href="#" ><span id="searchhelpcenter"><?php echo $t->_("Today"); ?></span></a>
            </li>        
        </ul>
        <hr>
        <div class="col-md-6">        
            <img src="<?php echo $baseUri ?>common/img/todayattlist.png" style="width:100%;height:380px;"> 
        </div>
        <div class="col-md-6">
            <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li><span class="text-aqua"><?php echo $t->_("Search Box"); ?></span>
                    <ul>
                        <li><pre><?php echo $t->_("Enter"); ?></pre></li>
                     </ul>
                </li>
                <li><?php echo $t->_("Then select the wanted username"); ?>                
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Export"); ?></span>
                     <ul>
                         <li><pre><?php echo $t->_("This will output"); ?></pre></li>
                     </ul>
                </li>
                <li><span class="text-aqua"><?php echo $t->_("Editatttime"); ?></span>
                        <ul>
                            <li><pre><?php echo $t->_("Admin"); ?></pre></li>
                         </ul>
                 </li>
             
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="dashboard"><< <?php echo $t->_("Dashboard"); ?>  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="monthlyattlist"><?php echo $t->_("Monthly Attendance List"); ?>  >></a>
    </div>
    </div>
</div>
</div>
