<div class="row-fluid">
    <div class="col-md-10" id="showhelp">
       <ul id="helpcenter">
        <li>
             <img src="../../common/img/list2.png" ><a href="#" ><span id="searchhelpcenter">Today Attendance List help center</span></a>
        </li>        
    </ul>
    <hr>
    <div class="col-md-6">        
        <img src="../../common/img/todayattlist.png" style="width:100%;height:380px;"> 
    </div>
         <div class="col-md-6">
             <ol type="1" style="font-family: Century,Hevitical,sans-serif;font-weight: bold;">
                <li>Search Box
                    <ul>
                         <li>Enter the username which you want to search.</li>
                     </ul>
                </li>
                <li>Then select the wanted username from dropdown list ,after that click search button                   
                </li>
                <li>Export
                     <ul>
                         <li>This will output the data of display table as csv.</li>
                     </ul>
                </li>
                 <li>Edit Attendance time(Admin)
                        <ul>
                            <li>Admin can edit your attendance time if necessary.</li>
                         </ul>
                 </li>
             
            </ol>
        </div>
    <div class="col-md-12 top-padding">
    <div class="col-md-6 ">
        <a href="dashboard"><< Dashboard  </a>
    </div>
    <div class="col-md-6 text-right">
        <a href="monthlyattlist">Monthly Attendance Lists  >></a>
    </div>
    </div>
</div>
</div>
