<!--
  @author Su Zin Kyaw
  @since  2015/22 /06-->
<?php 
    
      $leavetypelength = count($Leavetype);?> 

<section class="content-header">
          <h1>
          Apply Leave
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
             <li><a href="#"><i class="fa fa-dashboard"></i> Leave Days</a></li>
            <li class="active"> Apply Leave</li>
          </ol>
</section>
        <!-- Main content -->
<div class="demo-content" style="padding-top:2%;">
    <form action="" method="post" >
<table class="listtbl">
<thead>
    <tr>
        <th colspan="2">Apply Leave Form</th>
    </tr>
  </thead>
  <tbody>
      <tr>
          <td>Start Date </td>
          <td><input  type="text" class="datepicker form-control"  name="sdate" style="height:39px;" placeholder="Start Date"></td>
      </tr>
       <tr>
          <td>End Date </td>
          <td><input type="text" class="datepicker form-control" name="edate" style="height:39px;" placeholder="End Date"></td>
      </tr>
      <tr>
          <td>Leave Categories </td>
          <td><select class="select" data-toggle="select" name="leavetype">
                    <?php
                    foreach ($Leavetype as $data) {
                    ?>
                         <option value="<?php echo $data['leavetype_name']; ?>"><?php echo $data['leavetype_name']; ?></option>
                    <?php
                    }
                    ?> </select>
                    </td>
      </tr>
      <tr>
          <td>Description </td>
          <td> <textarea rows="2" cols="100" name="description" placeholder="Write Description"></textarea>
          </td>
      </tr>
      <tr>
          <td>
          <td >
          <input type="submit" value="Apply" class="buttonn" name="submit"><input  type="reset" class="buttonn" value="Cancel">
          </td>
      </tr>
</tbody>
</table>
</form>

</div>
   