<!--
  @author Su Zin Kyaw
  @since  2015/22 /06-->
<?php 
    
      $leavetypelength = count($Leavetype);?> 

<section class="content-header">
          <h1>
          <b>Apply Leave</b>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> <b>Home</b></a></li>
             <li><a href="#"><i class="fa fa-dashboard"></i> <b>Leave Days</b></a></li>
            <li class="active"> <b>Apply Leave</b></li>
          </ol>
</section>
        <!-- Main content -->
<div class="demo-content" style="padding-top:2%;">
    <form action="" method="post" >
<table class="listtbl">
<thead>
    <tr>
        <th colspan="2"><b>Apply Leave Form</b></th>
    </tr>
  </thead>
  <tbody>
      <tr>
          <td><b>Start Date :</b></td>
          <td><input type="text" class="datepicker form-control"  name="sdate" style="height:39px;" placeholder="Start Date"></td>
      </tr>
       <tr>
          <td><b>End Date :</b></td>
          <td><input type="text" class="datepicker form-control" name="edate" style="height:39px;" placeholder="End Date"></td>
      </tr>
      <tr>
          <td><b>Leave Categories :</b></td>
          <td><select class="select" data-toggle="select" name="leavetype">
                    <?php
                    foreach ($Leavetype as $data) {
                    ?>
                         <option value="<?php echo $data['leavetype_name']; ?>"><?php echo $data['leavetype_name']; ?></option>
                    <?php
                    }
                    ?> </select>
                    </td>
      </tr>
      <tr>
          <td><b>Description :</b></td>
          <td> <textarea rows="2" cols="100" name="description" ></textarea>
          </td>
      </tr>
      <tr>
          <td>
          <td >
          <input type="submit" value="Apply" class="buttonn" name="submit">
          </td>
      </tr>
</tbody>
</table>
</form>

</div>
   