<?php
//$timezone_identifiers = DateTimeZone::listIdentifiers();
//$length = count($timezone_identifiers);echo $length;
//for ($i=0; $i < $length; $i++) {
//    echo "$timezone_identifiers[$i]<br>";
//}exit;

$length = count($Month);

?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <b><?= $t->_("leave_list"); ?></b>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <b>Home</b></a></li>
        <li class="active"><b>Leave List</b></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <form id="frm_search">
            <select class="select" data-toggle="select" name="ltype" id="ltype">
                
                <option value=""><?= $t->_("leave_type"); ?></option>
                <?php
                foreach ($Leavetype as $data){
                ?>
                <option value="<?php echo $data['leavetype_name']; ?>"
               
                ><?php  echo $data['leavetype_name'] ?></option>
                <?php
                }
                ?>

            </select>
            <select class="select" data-toggle="select" name="month" id="month">
                <option value=""><?= $t->_("month"); ?></option>
                <?php
                for ($i = 1; $i <= $length; $i++) {
                    ?>
                    <option value="<?php
                    if ($i < 10) {
                        echo '0' . $i;
                    }
                    else {
                        echo $i;
                    }
                    ?>"
                    <?php echo(isset($Mth)&&($Mth==$i)?' selected="selected"':'');?>
                    ><?php echo $Month[$i]; ?></option>
                            <?php
                        }
                        ?>

            </select>
           
            <b><input type="submit" onclick="return false;" class="buttonn" value="Search" id="usersearch"></b>
            <!--       <a href="#" class="button" id="search">Search</a>-->
            <a href="#" class="button export" onclick="Export.Export.apply(this,[$('table.listtbl'),'Leave_List.csv']);"><b>Export</b></a>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px"><?= $t->_("date"); ?></th>
                        <th width="150px"><?= $t->_("name"); ?></th>
                        <th width="150px"><?= $t->_("start_date"); ?></th>
                        <th width="150px"><?= $t->_("end_date"); ?></th>
                        <th width="150px"><?= $t->_("leave_day"); ?></th>
                        <th width="150px"><?= $t->_("leave_type"); ?></th>
                        <th width="150px"><?= $t->_("leave_desc"); ?></th>
                        <th width="150px"><?= $t->_("leave_status"); ?></th>
                        <th width="150px"><?= $t->_("leave_left"); ?></th>
                    </tr>

                </thead>
                <tbody style="display: none;">
                    <?php
                    //print_r($Result);
                    foreach ($Result as $item) {
                        ?>
                        <tr>
                            <td><?php  $dt=  explode(" ",date($item['date']));
                                echo $dt[0];
                                ?></td>

                            <td><?php echo $item['member_login_name']; ?></td>
                            <td><?php $start_date= explode(" ", $item['start_date']); 
                                      echo $start_date[0];
                                ?></td>
                            <td><?php $end_date= explode(" ", $item['end_date']); 
                                      echo $end_date[0];
                                
                                ?></td>
                            <td><?php
                                echo $item['leave_days'];
                                
                                ?></td>
                            <td><?php
                                echo $item['leave_category'];
                                ?></td>
                            <td><?php
                                echo $item['leave_description'];
                                ?></td>
                           
                            <td><?php
                                
                        switch($item['leave_status']){
                            case "0" : echo "Pending" ; break;
                            case "1" : echo "Confirmed";break;
                            case "2" : echo "Rejected";break;
                               
                        };
                                ?></td>
                            <td><font color="red"><?php
                                
                            if($item['total_leavedays']>$max){
                            
                            echo ($item['total_leavedays'])-$max;
                            echo " Days are in absent";
                    }
                    else{
                                
                    echo $max-($item['total_leavedays']);}                        
                                ?></font></td>
                        </tr>
                            <?php
                    }
                    ?>

                </tbody>
                <tfoot style="display: none;"></tfoot>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
