<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
$length = count($Month);
?>

<!-- Content Header (Page header) -->
<section class="content-header" id="showleavelist">
    <h1>
        <b><?= $t->_("leave_list"); ?></b>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> <b><?= $t->_("home"); ?></b></a></li>
        <li class="active"><b><?= $t->_("leave_list"); ?></b></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
     
        <form id="frm_search" onsubmit="return false;">
            <a  href="/salts/leavedays/user/applyleave">  
                <input type="button" value=" Apply Leave" id="usersearch" class="buttonn form-control-static">
            </a> 
            <select class="select form-control-static" data-toggle="select" name="ltype" id="ltype">

                <option value=""><?= $t->_("leave_type"); ?></option>
                <?php
                foreach ($Leavetype as $data) {
                    ?>
                    <option value="<?php echo $data['leavetype_name']; ?>"><?php echo $data['leavetype_name'] ?></option>
                    <?php
                }
                ?>

            </select>
            <select class="select form-control-static" data-toggle="select" name="month" id="month">
                <option value=""><?= $t->_("month"); ?></option>
                <?php
                for ($i = 1; $i <= $length; $i++) {
                    ?>
                    <option value="<?php
                    if ($i < 10) {
                        echo '0' . $i;
                    } else {
                        echo $i;
                    }
                    ?>"
                            <?php echo(isset($Mth) && ($Mth == $i) ? ' selected="selected"' : ''); ?>
                            ><?php echo $Month[$i]; ?></option>
                            <?php
                        }
                        ?>

            </select>

            <b><input type="submit" onclick="return false;" class="buttonn form-control-static" value="Search" id="usersearch"></b>
            <a href="#" class="button export" id="exbg" onclick="Export.Export.apply(this, [$('table.listtbl'), 'Leave_List.csv']);"><img id="exicon"><b>Export</b></a>
            <a href="leavelist/1" class="button export" id="exbg" ><img id="exicon"><b>Export All</b></a>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px"><?= $t->_("date"); ?></th>
                        <th width="150px"><?= $t->_("name"); ?></th>
                        <th width="150px"><?= $t->_("start_date"); ?></th>
                        <th width="150px"><?= $t->_("end_date"); ?></th>
                        <th width="150px"><?= $t->_("leave_day"); ?></th>
                        <th width="150px"><?= $t->_("leave_type"); ?></th>
                        <th width="150px"><?= $t->_("leave_desc"); ?></th>
                        <th width="150px"><?= $t->_("leave_status"); ?></th>
                        <th width="150px"><?= $t->_("leave_left"); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($Result->items as $item) {
                        ?>
                        <tr>
                            <td><?php
                                $dt = explode(" ", date($item->leaves->date));
                                echo $dt[0];
                                ?></td>

                            <td><?php echo $item->core_member->member_login_name; ?></td>
                            <td><?php
                                $start_date = explode(" ", $item->leaves->start_date);
                                echo $start_date[0];
                                ?></td>
                            <td><?php
                                $end_date = explode(" ", $item->leaves->end_date);
                                echo $end_date[0];
                                ?></td>
                            <td><?php
                                echo $item->leaves->leave_days;
                                ?></td>
                            <td><?php
                                echo $item->leaves->leave_category;
                                ?></td>
                            <td><?php
                                echo $item->leaves->leave_description;
                                ?></td>

                            <td><?php
                                switch ($item->leaves->leave_status) {
                                    case "0" : echo "Pending";
                                        break;
                                    case "1" : echo "Confirmed";
                                        break;
                                    case "2" : echo "Rejected";
                                        break;
                                };
                                ?></td>
                            <td><font color="red"><?php
                                if ($absentdays > $max) {

                                    echo ( $absentdays) - $max;
                                    echo " Days are in absent";
                                } else {

                                    echo $max -  $absentdays;
                                }
                                ?></font></td>
                        </tr>
                        <?php
                    }
                    ?>

                </tbody>                
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->
     <div id="content">
        <ul class="pagination" style="margin-left:15px;">
            <?php
            if ($Result->last !== 1) {                          
                ?>
                <li><a href="leavelist">First</a></li>
                <li><a href="leavelist?page=<?= $Result->before; ?>">Previous</a></li>
                <li><a href="leavelist?page=<?= $Result->next; ?>">Next</a></li>
                <li><a href="leavelist?page=<?= $Result->last; ?>">Last</a></li>
                <li><span class="btn" style="margin-left:20px;"><?php echo "You are in page ", $Result->current, " of ", $Result->total_pages; ?></span></li>
                    <?php
                }
                ?>
        </ul>
    </div>
