<?php
//$timezone_identifiers = DateTimeZone::listIdentifiers();
//$length = count($timezone_identifiers);echo $length;
//for ($i=0; $i < $length; $i++) {
//    echo "$timezone_identifiers[$i]<br>";
//}exit;
    use Phalcon\Filter;
    
$length = count($Month);

?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Leave List
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Leave List</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="buttons">
        <form id="frm_search">
            <select class="select" data-toggle="select" name="ltype" id="ltype">
                
                <option value="">Leave Type</option>
                <?php
                foreach ($leave_result as $data){
                ?>
                <option value="<?php echo $data['leavetype_name']; ?>"
               
                ><?php  echo $data['leavetype_name'] ?></option>
                <?php
                }
                ?>

            </select>
            <select class="select" data-toggle="select" name="month" id="month">
                <option value="">Month</option>
                <?php
                for ($i = 1; $i <= $length; $i++) {
                    ?>
                    <option value="<?php
                    if ($i < 10) {
                        echo '0' . $i;
                    }
                    else {
                        echo $i;
                    }
                    ?>"
                    <?php echo(isset($Mth)&&($Mth==$i)?' selected="selected"':'');?>
                    ><?php echo $Month[$i]; ?></option>
                            <?php
                        }
                        ?>

            </select>
           
            <b><input type="submit" onclick="return false;" class="buttonn" value="Search" id="usersearch"></b>
            <!--       <a href="#" class="button" id="search">Search</a>-->
            <a href="#" class="button export" onclick="Export.Export.apply(this,[$('table.listtbl'),'Leave_List.csv']);"><b>Export</b></a>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12"><!--start table content--->
            <table class="listtbl">
                <thead>
                    <tr>
                        <th width="150px">Date</th>
                        <th width="150px">Name</th>
                        <th width="150px">Start Date</th>
                        <th width="150px">End Date</th>
                        <th width="150px">Leave days</th>
                        <th width="150px">Leave type</th>
                        <th width="150px">Leave description</th>
                        <th width="150px">Leave status</th>
                        <th width="150px">Leave day left</th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                    //print_r($Result);
                     $filter = new Filter();
                     
                    foreach ($Result as $item) {
                        ?>
                        <tr>
                            <td><?php  $dt=  explode(" ",date($item['date']));
                                echo $dt[0];
                                ?></td>
                                
                            <td><?php echo $filter->sanitize($item['member_login_name'], "string"); ?></td>
                            <td><?php $start_date= explode(" ", $item['start_date']); 
                                      echo $start_date[0];
                                ?></td>
                            <td><?php $end_date= explode(" ", $item['end_date']); 
                                      echo $end_date[0];
                                
                                ?></td>
                            <td><?php
                                echo $filter->sanitize($item['leave_days'], "int");
                                
                                ?></td>
                            <td><?php
                                echo $filter->sanitize($item['leave_category'], "string");
                                ?></td>
                            <td><?php
                                echo $filter->sanitize($item['leave_description'], "string");
                                ?></td>
                           
                            <td><?php
                                
                        switch($filter->sanitize($item['leave_status'], "string")){
                            case "0" : echo "Pending" ; break;
                            case "1" : echo "Confirmed";break;
                            case "2" : echo "Rejected";break;
                               
                        };
                                ?></td>
                            <td><font color="red"><?php
                                
                            if($filter->sanitize($item['total_leavedays'], "int")>$max){
                            
                            echo ($filter->sanitize($item['total_leavedays'], "int"))-$max;
                            echo " Days are in absent";
                    }
                    else{
                                
                    echo $max-($filter->sanitize($item['total_leavedays'], "int"));}                        
                                ?></font></td>
                        </tr>
                            <?php
                    }
                    ?>

                </tbody>
                <tfoot style="display: none;"></tfoot>
            </table>      
        </div><!--end table content--->
    </div><!-- /.row -->
    <div id="content"></div>
