<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>WORK MANAGIMENT SYSTEM</title>
   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="forgot-logo">
<!--        <b>FORGOT YOUR PASSWORD</b>-->
        <br>
         <p id="forgottext">FORGOT YOUR PASSWORD?</p>
      </div><!-- /.forgot-logo -->
      <div class="forgot-box-body">
          
        <form method="post" action="<?=$this->url->getBaseUri();?>auth/index/findmember" id="form_login">
            <label>Don't worry! Just fill in your email and we'll help you reset your password.</label><br><br>
             <div class="form-group has-feedback">
                 <label>EMAIL ADDRESS</label>
                 <input type="email" name="member_mail" id="emailaddress" class="form-control" placeholder="Enter Your Email Address"/>           
             </div>
          
          <div class="row">            
            <div class="backgo">
                <span id="goright"><button type="submit" id="btngo" class="btn  btn-block btn-flat">Send Email</button></span>
            </div><!-- /.col -->
          </div>
        </form>

       

      </div><!-- /.forgot-box-body -->
        <div class="backtologin">
            <a href="../../auth" id="backtologintext">BACK TO LOGIN</a>
      </div><!-- /.backtologin -->
      
    </div><!-- /.login-box -->

<!--     jQuery 2.1.4 
    <script src="../../plugins/jQuery/jQuery-2.1.4.min.js"></script>
     Bootstrap 3.3.2 JS 
    <script src="../../bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
     iCheck 
    <script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>-->
  </body>
</html>
