<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>WORK MANAGIMENT SYSTEM</title>
   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
<!--        <b>FORGOT YOUR PASSWORD</b>-->
         <span id="saltstext">FORGOT YOUR PASSWORD</span>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        
        
        <form method="post" action="SaltsForGet" id="form_login">
          <div class="form-group has-feedback">              
            <input type="text" name="SaltsForGetInput" class="form-control" placeholder="Email"/>           
          </div>
          
          <div class="row">
            
            <div class="col-xs-4">
                <button type="submit" id="btnLogin" class="btn btn-primary btn-block btn-flat">Go!</button>
            </div><!-- /.col -->
          </div>
        </form>

       

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

<!--     jQuery 2.1.4 
    <script src="../../plugins/jQuery/jQuery-2.1.4.min.js"></script>
     Bootstrap 3.3.2 JS 
    <script src="../../bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
     iCheck 
    <script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>-->
  </body>
</html>
