<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>WORK MANAGIMENT SYSTEM</title>

    </head>
    <body class="login-page">
        <div class="login-box">
            <div class="forgot-logo">
                <br>
                <p id="forgottext">FORGOT YOUR PASSWORD?</p>
            </div><!-- /.forgot-logo -->
            <div class="forgot-box-body">

                <form method="post" action="#" id="form_login">
                    <label>Don't worry! Just fill in your email and we'll help you reset your password.</label><br><br>
                    <div id="emailerror" style="display: none;">   
                        <label>Please fill in at least one field</label><br>
                        <span id="onefield">Fill in at least one field to search for your account</span>
                    </div>
                    <div id="noemailerror" style="display: none;">   
                        <label>No Search Results</label><br>
                        <span id="noemailfield">Your search did not return any results. Please try again with other information.</span>
                    </div>
                    <br>
                    <div class="form-group has-feedback">
                        <label>EMAIL ADDRESS</label>
                        <br>
                        <img src="<?php echo $baseUri; ?>common/img/message1.png"> <input type="email" name="member_mail" style="width: 91%;margin-top: 10px;" id="emailaddress" class="form-control" placeholder="Enter Your Email Address"/>           
                    </div>

                    <div class="row">            
                        <div class="backgo">
                            <span id="goright"><button type="submit" onclick="return false;" id="btngo" class="btn  btn-block btn-flat">Check</button></span>
                        </div><!-- /.col -->
                    </div>
                </form>
                
            </div><!-- /.forgot-box-body -->
            <div class="backtologin"><br>
                <a href="../../auth" id="backtologintext">BACK TO LOGIN</a>
            </div><!-- /.backtologin -->

        </div><!-- /.login-box -->

    </body>
</html>
