<form method="post" action="<?=$url->getBaseUri();?>">
    <table border="0" cellpadding="0" cellspacing="0" class="loginTable">                
        <tr><th>Login Name</th></tr>                
        <tr><td><?=$this->tag->textField(['login_name', 'maxlength'=> 64]) ?></td></tr>
        <tr><th>Password</th></tr>
        <tr><td><?=$this->tag->passwordField(['login_password', 'maxlength'=> 64]) ?></td></tr>
        <tr>
            <td>
                <input id="btnLogin" type="submit" value="LOGIN" />
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="forgot_pass">
<?php print_r($user);?>                </td>
        </tr>

    </table>
</form>
<?php print_r($test);?>  
