<div id="login_block">
    <form method="post" action="./auth/login" id="form_login">
        <img src="./img/auth/logo.png">
        <table border="0" cellpadding="0" cellspacing="0" class="loginTable">                
            <tr><th>Login Name</th></tr>                
            <tr><td><?=$this->tag->textField(['account', 'maxlength'=> 64]) ?></td></tr>
            <tr><th>Password</th></tr>
            <tr><td><?=$this->tag->passwordField(['password', 'maxlength'=> 64]) ?></td></tr>
            <tr>
                <td>
                    <input id="btnLogin" type="submit" value="LOGIN" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="forgot_pass"></td>
            </tr>
        </table>
    </form>
</div>

<div id="bottom_block">
    Copyright (C) 2003-2014 G-NEXT, Inc. All rights reserved.
</div>

