<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>WORK MANAGIMENT SYSTEM</title>
   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
        <b>GNEXT WORK MANAGIMENT SYSTEM</b>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <?=$errorMsg?>
        <form method="post" action="<?=$this->url->getBaseUri();?>auth/login" id="form_login">
          <div class="form-group has-feedback">
              
            <input type="text" name="member_login_name" class="form-control" placeholder="UserName"/>
           
          </div>
          <div class="form-group has-feedback">
              
            <input type="password" name="password" class="form-control" placeholder="Password"/>
          </div>
          <div class="row">
            
            <div class="col-xs-4">
              <button type="submit" id="btnLogin" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
          </div>
        </form>

       

        <a href="">I forgot my password</a><br>
       

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

  </body>
</html>