<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <title>WORK MANAGIMENT SYSTEM</title>
   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="forgot-logo">
<!--        <b>FORGOT YOUR PASSWORD</b>-->
        <br>
         <p id="forgottext">CHOOSE A NEW PASSWORD</p>
      </div><!-- /.forgot-logo -->
      <div class="forgot-box-body">
          
        <form method="post" action="<?=$this->url->getBaseUri();?>auth/index/newpassword" id="form_login">
<!--            <label>Don't worry! Just fill in your email and we'll help you reset your password.</label><br><br>-->
             <div class="form-group has-feedback">
                 
                     A strong password is a combination of letters and punctuation marks. It must be at least 6 characters long.<br>
<!--                 <input type="email" name="member_mail" id="emailaddress" class="form-control" placeholder="Enter Your Email Address"/>           -->
                        <?php
                      foreach ($Result as $result) {
                ?>      
                        
               <?php 
                      }
               ?>
                     <input type="hidden" name="member_mail" id="emailaddress" class="form-control"  value="<?php echo $result ['member_mail']; ?>" />   
                     <table>
                         <tr>                             
                             <td id="newpass">New Password  </td>
                             <td><input type="text" style="margin-top: 10px;" name="newpassword" id="forgotnewpassword" class="form-control" placeholder=""/></td>
                         </tr>
                          <tr>                             
                              <td id="compass"> Comfirm Password   </td>
                             <td><input type="text" style="margin-top: 10px;" name="comfirmpassword" id="forgotcomfirmpassword" class="form-control" placeholder=""/></td>
                         </tr>
                     </table>
                   
               
                      
                 
<!--                                        <span id="forgotname">
                                           
                                            
                                        </span>-->
                                       
                
                 
             </div>
          
          <div class="row">  
              
            <div class="backgo">
                
                
               
                <span id="goright">
                    <input type="submit" class="buttonn" id="btngo" value="Continue">
                    <input type="reset" id="btn_cancel" class="buttonn" value="Cancel">
<!--                    <button type="submit"  class="btn  btn-block btn-flat">Continue</button><button type="reset" id="btngo" class="btn  btn-block btn-flat">Cancel</button>-->
                </span>
            </div><!-- /.col -->
          </div>
        </form>

       

      </div><!-- /.forgot-box-body -->
<!--        <div class="backtologin"><br>
            <a href="../../auth" id="backtologintext">BACK TO LOGIN</a>
      </div> /.backtologin -->
      
    </div><!-- /.login-box -->

<!--     jQuery 2.1.4 
    <script src="../../plugins/jQuery/jQuery-2.1.4.min.js"></script>
     Bootstrap 3.3.2 JS 
    <script src="../../bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
     iCheck 
    <script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>-->
  </body>
</html>
