<?php

if(! ini_get('date.timezone')){
    date_default_timezone_set('UTC');    
}
    

?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Login</title>

    </head>
    <body class="login-page">
        <div class="login-box">
            <div class="forgot-logo">
                <br>
                <p id="forgottext">CHOOSE A NEW PASSWORD</p>
            </div><!-- /.forgot-logo -->
            <div class="forgot-box-body">

                <form method="post" action="<?= $this->url->getBaseUri(); ?>auth/index/newpassword" id="form_login">
                    <div class="form-group has-feedback">

                        A strong password is a combination of letters and punctuation marks.<br><br>

                        <input type="hidden" name="member_mail" id="emailaddress" class="form-control"  value="<?php echo $member_mail; ?>" />   
                        <div id="newpassempty" style="display: none;">   
                            <label>Please fill in at least one field</label><br> 
                            <span id="onefield">Enter Your New Password!</span>
                        </div>
                        <div id="newpasserror" style="display: none;">   
                            <label>No Match your new password and comfirm password</label>   
                            <span id="onefield">Please Try again!</span>
                        </div>
                        <table>
                            <tr>                             
                                <td id="newpass">New Password  </td>
                                <td>
                                    <div id="hidepassword" > 
                                        <input type="password" style="margin-top: 10px;" name="newpassword" id="forgotnewpassword" class="form-control" placeholder=""/>
                                    </div>
                                    <div id="showpassword" style="display: none;">   
                                        <input type="text" style="margin-top: 10px;" name="showpassword" id="shownewpassword" class="form-control" placeholder=""/>
                                    </div>
                                </td>
                            </tr>
                            <div id="passshort" style="display: none;">   
                                <label>It must be at least 6 characters long.</label>
                            </div>
                            <div id="passlong" style="display: none;">   
                                <label>It must be at most 16 characters long.</label>
                            </div>
                            <tr>                             
                                <td id="compass"> Comfirm Password   </td>
                                <td>
                                    <div id="hideconpassword" >  
                                        <input type="password" style="margin-top: 10px;" name="comfirmpassword" id="forgotcomfirmpassword" class="form-control" placeholder=""/>
                                    </div>

                                    <div id="showconpassword" style="display: none;">   
                                        <input type="text" style="margin-top: 10px;" name="scpassword" id="showconfirmpassword" class="form-control" placeholder=""/>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><input type="checkbox" name="show"  id="show" value="Show Password" style="margin-top: 1px;" > Show Password</td>
                            </tr>
                        </table>

                    </div>

                    <div class="row">  

                        <div class="backgo">



                            <span id="goright">
                                <input type="submit" onclick="return false;"class="buttonn" id="btnnewpass" value="Continue">
                                <a href="../../auth" id="btn_cancel" class="buttonn">Cancel</a>
                            </span>
                        </div><!-- /.col -->
                    </div>
                </form>



            </div><!-- /.forgot-box-body -->


        </div><!-- /.login-box -->

    </body>
</html>
