<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <title>WORK MANAGIMENT SYSTEM</title>
   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="forgot-logo">
<!--        <b>FORGOT YOUR PASSWORD</b>-->
        <br>
         <p id="forgottext">RESET YOUR PASSWORD?</p>
      </div><!-- /.forgot-logo -->
      <div class="forgot-box-body">
          
        <form method="post" action="<?=$this->url->getBaseUri();?>auth/index/sendmail" id="form_login">
<!--            <label>Don't worry! Just fill in your email and we'll help you reset your password.</label><br><br>-->
             <div class="form-group has-feedback">
                 <div id="profileandname">
                     <label id="saltsuser">SALTS USER</label><br>
                        
               
                 <?php
                      foreach ($Result as $result) {
                ?>
                     <input type="hidden" name="member_mail" id="emailaddress" class="form-control"  value="<?php echo $result ['member_mail']; ?>" />        
                        <?php
                                                    if($result['member_profile']==null){
                                                    $img = "profile1.jpg";}
                                                    else{
                                                        $img=$result['member_profile'];
                                                        if(file_exists('./uploads/'.$img)){                                                            
                                                                $img=$img;                                                            
                                                        }else{  
                                                               $img = "profile1.jpg";                                                                 
                                                        }
                                                    }
                                                  //  echo $img;
                                        ?>                                                 
                                        <img src="../../uploads/<?php echo  $img;?>"  style="width:90px;height:100px;" class="user-image" alt="User Image"/>
                                        <br> <label><?php echo $result ['full_name']; ?> </label>
                 </div>
                 <div id="howreset">
                     <br><br>
                   
                     Email me a link to reset my password   <br>              
                      <span id="textmail">  <img src="../../common/img/message-16.png">  <?php echo $result ['member_mail']; ?></span>
                 </div>
                 
<!--                                        <span id="forgotname">
                                           
                                            
                                        </span>-->
                                       
                <?php
                             }
                ?>
                 
             </div>
          
          <div class="row">  
              
            <div class="backgo">
                
                
               
                <span id="goright">
<!--                    <button type="submit" id="btngo" class="btn  btn-block btn-flat">Send Email</button>-->
                    <input type="submit" class="buttonn" id="btngo" value="Send Email">
                    <a href="../../auth/index/forgotpassword" id="notyou" class="buttonn">Not You?</a>
<!--                    <input type="submit" class="buttonn" id="btngo" value="Send Email">-->
                    
                </span>
            </div><!-- /.col -->
          </div>
        </form>

       

      </div><!-- /.forgot-box-body -->
<!--        <div class="backtologin"><br>
            <a href="../../auth" id="backtologintext">BACK TO LOGIN</a>
      </div> /.backtologin -->
      
    </div><!-- /.login-box -->

<!--     jQuery 2.1.4 
    <script src="../../plugins/jQuery/jQuery-2.1.4.min.js"></script>
     Bootstrap 3.3.2 JS 
    <script src="../../bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
     iCheck 
    <script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>-->
  </body>
</html>
