<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <title>WORK MANAGIMENT SYSTEM</title>
   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="forgot-logo">
<!--        <b>FORGOT YOUR PASSWORD</b>-->
        <br>
         <p id="forgottext">RESET YOUR PASSWORD?</p>
      </div><!-- /.forgot-logo -->
      <div class="forgot-box-body">
          
        <form method="post" action="#" id="form_login">
<!--            <label>Don't worry! Just fill in your email and we'll help you reset your password.</label><br><br>-->
             <div class="form-group has-feedback">
                 <div id="profileandname">
                     <label id="saltsuser">SALTS USER</label><br>

                 <?php
                      foreach ($Result as $result) {
                ?>
                     <input type="hidden" name="member_mail" id="emailaddress" class="form-control"  value="<?php echo $result ['member_mail']; ?>" />    
                      <input type="hidden" name="full_name" id="full_name"  value="<?php echo $result ['full_name']; ?>" />  
                        <?php
                                                    if($result['member_profile']==null){
                                                    $img = "profile1.jpg";}
                                                    else{
                                                        $img=$result['member_profile'];
                                                        if(file_exists('./uploads/'.$img)){                                                            
                                                                $img=$img;                                                            
                                                        }else{  
                                                               $img = "profile1.jpg";                                                                 
                                                        }
                                                    }
                                                  //  echo $img;
                                        ?>                                                 
                                        <img src="<?php echo $baseUri;?>uploads/<?php echo  $img;?>"  style="width:90px;height:100px;box-shadow: 0px 0px 5px #3c8dbc;" class="user-image" alt="User Image"/>
                                         
                 </div>
<!--                                      for email sent 
             
                            <input type="text" value="<?php echo $to; ?>">
                            <input type="text" value="<?php echo $subject; ?>">
                            <input type="text" value="<?php echo $message; ?>">
                            <input type="text" value="<?php echo $from; ?>">-->
                 <div id="howreset">
                     <br><br>
                   
                     Email me a link to reset my password             
                      <span id="textmail">  <img src="<?php echo $baseUri;?>common/img/message.png">  <?php echo $result ['member_mail']; ?></span>
                      <br><br><label><?php echo $result ['member_login_name']; ?> </label>
                 </div>
                 
<!--                                        <span id="forgotname">
                                           
                                            
                                        </span>-->
                                       
                <?php
                             }
                ?>
                 
             </div>
          
          <div class="row">  
              
            <div class="backgo">
                
                
               
                <span id="goright">
<!--                    <button type="submit" id="btngo" class="btn  btn-block btn-flat">Send Email</button>-->
<input type="submit"onclick="return false;" class="buttonn" id="btnemail" value="Send Email" >
                    <a href="../../auth/index/forgotpassword" id="notyou" class="buttonn">Not You?</a>
<!--                    <input type="submit" class="buttonn" id="btngo" value="Send Email">-->
                    
                </span>
            </div><!-- /.col -->
          </div>
        </form>

       

      </div><!-- /.forgot-box-body -->
<!--        <div class="backtologin"><br>
            <a href="../../auth" id="backtologintext">BACK TO LOGIN</a>
      </div> /.backtologin -->
      
    </div><!-- /.login-box -->

  </body>
</html>
