<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>WORK MANAGIMENT SYSTEM</title>

    </head>
    <body class="login-page">
        <div class="login-box">
            <div class="forgot-logo">
                <br>
                <p id="forgottext">ENTER SECURITY  CODE</p>
            </div><!-- /.forgot-logo -->
            <div class="forgot-box-body">

                <form method="post" action="#" id="form_login">
                    <div class="form-group has-feedback">

                        <label>Please check your email for a message with your code. Your code is 6 numbers long.</label><br>
                        <div id="codeerror" style="display: none;">   
                            <label>Please fill in at least one field</label>
                        </div>
                        <div id="checkcodeerror" style="display: none;">   
                            <label>No Match Code</label><br>
                            <span id="onefield">Please check your email.</span>
                        </div>
                        <br>
                        <input type="text" name="code" id="code" class="form-control" placeholder="######"/>

                        <?php
                        foreach ($Result as $result) {
                            ?>      
                            We sent your code to :               
                            <span id="textmail">  <img src="<?php echo $baseUri; ?>common/img/message.png">  <?php echo $result ['member_mail']; ?>    </span>
                            <input type="hidden" name="member_mail" id="emailaddress" class="form-control"  value="<?php echo $result ['member_mail']; ?>" />  

                            <?php
                        }
                        ?>

                    </div>

                    <div class="row">
                        <div class="backgo">
                            <span id="goright"><button onclick="return false;" id="btncontinue" class="btn  btn-block btn-flat">Continue</button></span>
                        </div><!-- /.col -->
                    </div>
                </form>



            </div><!-- /.forgot-box-body -->           

        </div><!-- /.login-box -->

    </body>
</html>
