<!DOCTYPE html>
<?php 
    $to      = $_POST['member_mail'];
    $subject = 'The subject';
    $message = 'hello';
    $headers = 'From: sawzinminmin@gmail.com' . "\r\n" .
        'Reply-To: sawzinminmin@gmail.com' . "\r\n" .
        'X-Mailer: PHP/' . phpversion();

    if(mail($to, $subject, $message, $headers)){
        echo $to ." : " .$subject." : ".$message." : ".$headers;
        echo "Mail Sent";
    }else{
        echo "Email sending failed";
    }
   
?>
<html>
  <head>
    <meta charset="UTF-8">
    <title>WORK MANAGIMENT SYSTEM</title>
   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="forgot-logo">
<!--        <b>FORGOT YOUR PASSWORD</b>-->
        <br>
         <p id="forgottext">ENTER SECURITY  CODE</p>
      </div><!-- /.forgot-logo -->
      <div class="forgot-box-body">
          
        <form method="post" action="<?=$this->url->getBaseUri();?>auth/index/newpassword" id="form_login">
<!--            <label>Don't worry! Just fill in your email and we'll help you reset your password.</label><br><br>-->
             <div class="form-group has-feedback">
                 
                     <label>Please check your email for a message with your code. Your code is 6 numbers long.</label><br>
<!--                 <input type="email" name="member_mail" id="emailaddress" class="form-control" placeholder="Enter Your Email Address"/>           -->
              
                   <input type="text" name="code" id="code" class="form-control" placeholder="######"/>
               
                       <?php
                      foreach ($Result as $result) {
                ?>      
                    We sent your code to : <br>              
                      <span id="textmail">  <img src="../../common/img/message-16.png">  <?php echo $result ['member_mail']; ?>    </span>
                      <input type="hidden" name="member_mail" id="emailaddress" class="form-control"  value="<?php echo $result ['member_mail']; ?>" />  
                     
               <?php 
                      }
               ?>
                 
<!--                                        <span id="forgotname">
                                           
                                            
                                        </span>-->
                                       
                
                 
             </div>
          
          <div class="row">  
              
            <div class="backgo">
                
                
               
                <span id="goright"><button type="submit" id="btngo" class="btn  btn-block btn-flat">Continue</button></span>
            </div><!-- /.col -->
          </div>
        </form>

       

      </div><!-- /.forgot-box-body -->
<!--        <div class="backtologin"><br>
            <a href="../../auth" id="backtologintext">BACK TO LOGIN</a>
      </div> /.backtologin -->
      
    </div><!-- /.login-box -->

<!--     jQuery 2.1.4 
    <script src="../../plugins/jQuery/jQuery-2.1.4.min.js"></script>
     Bootstrap 3.3.2 JS 
    <script src="../../bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
     iCheck 
    <script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>-->
  </body>
</html>
