<?php use Phalcon\Tag as Tag; ?>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<!-- <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" /> -->

 <?php
        //echo $this->session->auth['user_role'];exit;
        // $role="1";
          if($this->session->auth['user_role']==1)
          {
          ?>
  <body class="skin-blue sidebar-mini">
    <?php }
      else {
        ?>
        <body class="skin-blue sidebar-mini" onload=display_ct()>
    <?php
      }
      ?>
    <div class="wrapper">
      <?php
        //echo $this->session->auth['user_role'];exit;
        // $role="1";
          if($this->session->auth['user_role']==1)
          {
          ?>
      <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini">G_NEXT</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">G_NEXT</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">4</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 4 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#" class="notification">
                          <i class="fa fa-users"></i> Su Zin apply for leave
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users"></i> Aung Naing Tun apply for leave
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users"></i> David apply for leave
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="viewall.html">View all</a></li>
                </ul>
              </li>
              
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 <?php echo Tag::image(array('img/profile.png', 'width' => 30)) ?>
                  <span class="hidden-xs">Admin</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                   <?php echo Tag::image(array('img/profile.png', 'width' => 30)) ?>
                    <p>
                      Admin - Web Developer
                      <small>Member since Nov. 2012</small>
                    </p>
                  </li>
                  
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="../administrator/setting" class="btn btn-default btn-flat">Setting</a>
                    </div>
                    <div class="pull-right">
                      <a href="../session/logout" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
              
            </ul>
          </div>

        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
             <?php echo Tag::image(array('img/profile.png', 'width' => 30)) ?>
            </div>
            <div class="pull-left info">
              <p>Admin</p>

              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          
  
          <!-- sidebar menu: : style can be found in sidebar.less -->

          <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
       <li><a href="index"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            
            <li class="treeview">
              <a href="#">
                <i class="fa fa-user"></i>
                <span>Manage User</span>
                
              </a>
              <ul class="treeview-menu">
                <li><a href="userlist"><i class="fa fa-circle-o"></i> User List</a></li>
                <li><a href="adduserlist"><i class="fa fa-circle-o"></i> Add User Form</a></li>
               
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i>
                <span>Attendance List</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="../attendance/todaylist"><i class="fa fa-circle-o"></i> Today list</a></li>
                <li><a href="../attendance/monthlylist"><i class="fa fa-circle-o"></i> Monthly List</a></li>
               
              </ul>
            </li>
            
      <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i>
                <span>Leave days</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="leavelist"><i class="fa fa-circle-o"></i> Leave List</a></li>
                <li><a href="applyleave"><i class="fa fa-circle-o"></i> Apply Leave</a></li>
               
              </ul>
            </li>
            <li>
              <a href="calendar">
                <i class="fa fa-calendar"></i> <span>Calendar</span>
                
              </a>
            </li>
           <li class="treeview">
              <a href="#">
                <i class="fa fa-dollar"></i>
                <span>Salary</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="salaryadd"><i class="fa fa-circle-o"></i> Salary</a></li>
                <li><a href="salarylist"><i class="fa fa-circle-o"></i>Salary List</a></li>
               
              </ul>
          </li>
            
          </ul>
        </section>
       
        <!-- /.sidebar -->
      </aside>
       <?php
      }
      else{
        ?>

        <header class="main-header">
        <a href="index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini">Attendance System</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">Attendance System</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
               <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <?php echo Tag::image(array('img/profile.png', 'width' => 30)) ?>
                  <span class="hidden-xs">Su Zin Kyaw</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <?php echo Tag::image(array('img/profile.png', 'width' => 30)) ?>
                    <p>
                      Su Zin Kyaw- Web Developer
                      <small>Member since May.2014</small>
                    </p>
                  </li>
                    <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="../session/logout" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
             
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <?php echo Tag::image(array('img/profile.png', 'width' => 30)) ?>
            </div>
            <div class="pull-left info">
              <p>Su Zin Kyaw</p>

              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
           <li><a href="index2.html"><i class="fa fa-book"></i> <span>Home</span></a></li>
            <li class="treeview">
               <a href="#">
                <i class="fa fa-edit"></i>
                <span>Attendance List</span>
               </a>
              <ul class="treeview-menu">
                <li><a href="attd.html"><i class="fa fa-circle-o"></i> Today list</a></li>
                <li><a href="attm.html"><i class="fa fa-circle-o"></i> Monthly List</a></li>
              </ul>
            </li>
            <li class="treeview">
                <a href="#">
                <i class="fa fa-edit"></i>
                <span>Leave days</span>
                </a>
              <ul class="treeview-menu">
                <li><a href="leave.html"><i class="fa fa-circle-o"></i> Leave List</a></li>
                <li><a href="applyleave.html"><i class="fa fa-circle-o"></i> Apply Leave</a></li>
              </ul>
            </li>        
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

        <?php
      }
        ?>
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper" style="height:auto;">
       <section class="content">
      <?php echo $this->getContent() ?>
      </section>
      </div><!-- /.content-wrapper -->

      <footer class="main-footer">
        <div class="pull-right hidden-xs">
        
        </div>
        <strong>Copyright &copy; by G_NEXT Myanmar!
      </footer>
   </div><!-- ./wrapper -->
   
  </body>
