 <?php use Phalcon\Tag as Tag; ?>
 <?php
//echo Tag::stylesheetLink('css/fullcalendar.css'); 

 ?>
  <div>
          <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
            
          </div><!-- /.row -->
          <div class="row">
      <div class="col-md-12">
      <div class="top_row"><?php echo Tag::image(array('img/Check-32.png', 'width' => 30)) ?><font style="color:red;">[This Month] Attendance :</font>12</div>
      <div class="top_row"><?php echo Tag::image(array('img/absence.png', 'width' => 30)) ?><font style="color:red;">[This Month]Leave Days :</font> 0</div>
      </div>
               <div class="col-md-12">
              <div class="box">
          <div id="lft">
      <div class="col-md-7 col-md-offset-3">
            <h2>Current Time : <span id='ct' style="color:red;" ></h2>
      </div><br><br>
      <div class="col-md-6 col-md-offset-4">
          <a href="attd.html"  class="btn btn-primary btn-sm btn-flat" style="width: 150px;">Check In </a>
      </div><br><br>
      <div class="col-md-6 col-md-offset-4">
          <a href="attd.html"  class="btn btn-primary btn-sm btn-flat" style="width: 150px;">Check Out </a>
      </div><br><br>
      <div class="col-md-8 col-md-offset-3">
            <h5>If you are Late with Job Case,you can <a href="late.html">check in here</a></h5>
       </div>
      </div>
    <div id="rgt">
    <div id="calendar" style="height:310px; width:100%;"></div></div>
      </div>               
              </div><!-- /.box -->
         </div><!-- /.col -->
       </div><!-- /.row -->
<script>
    $("#calendar").kendoCalendar();

    var calendar = $("#calendar").data("kendoCalendar");

    var current = calendar.current(); //will be today, because value is `null`
</script>
        